### ISSUE TITLE
Add test for RemoteIo::getb()

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#1029]
In #1007 we merged a change proposed by @clanmills which were validated by a test application which is not part of our code base (see [comment](https://github.com/Exiv2/exiv2/issues/910#issuecomment-535542824)).

The idea would be to add a test for `RemoteIo::getb()` (either a unit or system test) to validate that code.

**Comment by clanmills** [comment]
@piponazo I'll deal with this for v0.27.3  I've got code checked into team/book that deals with this.  I'll do a brain refresh and add a unit test.

**Comment by clanmills** [comment]
This is included in #1174 It's in test/iotest.sh and not in the unit_tests.  I didn't add a unit_test for this because it requires a web-server to be running and that's some much simpler to manage from bash.  And I wanted to extend test/iotest.sh to perform some http testing anyway.  You'll see there is a comment in samples/iotest.cpp concerning code that specifically addresses the topic of this issue.
