### ISSUE TITLE
Fix AppVeyor builds on 0.27-maintenance

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#1200]
**Describe the bug**
There is an error in some of the Appveyor jobs when downloading the libcurl dependencies with conan. 

```
WARN: libcurl/7.69.1: requirement zlib/1.2.11 overridden by your conanfile to zlib/1.2.11@conan/stable 
ERROR: Error loading conanfile at 'c:\Users\appveyor\conanCache\nasm\2.14\_\_\export\conanfile.py': Unable to load conanfile in c:\Users\appveyor\conanCache\nasm\2.14\_\_\export\conanfile.py
  File "c:\Users\appveyor\conanCache\nasm\2.14\_\_\export\conanfile.py", line 48
SyntaxError: Non-ASCII character '\xe2' in file c:\Users\appveyor\conanCache\nasm\2.14\_\_\export\conanfile.py on line 48, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**To Reproduce**
Just check some of the Appveyor jobs for the Visual Studio 2013 Images.

**Expected behavior**
Builds should bring the dependencies correctly with conan.

**Desktop (please complete the following information):**
 - OS: Windows
 - Compiler & Version MSVC 2013

**Additional context**
We could try to download a different version of libcurl, or play with the options of the recipe to determine what's happening. Rarely, the builds are passing for VS 2015 & 2017.

**Comment by clanmills** [comment]
VS2013 builds and passes the test suite for me.  By default I don't build WebReady and do not need curl/openssl/libssh.

It's reasonable to say that we shouldn't build WebReady before VS2013 because the feature was developed in 2013 (and shipped in v0.25 June 2015).  The purpose in building with VS2013 (and other legacy compilers) is to be confident that users can take the latest code and security fixes and re-build with their legacy compiler and re-link their application. 

Are you suggesting that we specify a different version of libcurl in conanfile.py (and/or the `conan --install` command)?  I'm happy to investigate this today and let you get on with work.

**Comment by piponazo** [comment]
I think that both approaches would be fine:

1) Find why conan is failing to bring libcurl/7.69.1 in the Appveyor MSVC 2013 image, when it is fine for the 2015 & 2017 images. 
2) Directly disable the webready support for the Appveyor MSVC 2013 image. That should fix the problem immediately. 

Feel free to investigate this during the day. I could not work on this until the evening due to work :+1:

**Comment by clanmills** [comment]
It looks like the case-insensitve file system on Windows is a problem.  It complains that it has been asked for openssl/1.1.1f and can only find OpenSSL.  There's a switch in Windows (since 2018) to enable case-sensitive files on a folder-by-folder basis.  I don't think using that is a good idea.  Anybody using an older Windows without that switch will be in trouble.

It's coming from the bincrafters libcurl. Two possibilities:
1) A more recent libcurl may be all lower case.   
2) We don't necessarily need openssl.  I think curl can be built to use the platform ssl and it looks as though that's what we use on the Mac.

I'm going out to walk.  I will investigate this afternoon.  I think I've also seen conflicts concerning zlib.

**Comment by clanmills** [comment]
@piponazo conan/CMake is really good combination.

In conanfile.py, I've selected winssl for windows (instead of openssl), updated src/CMakeLists.txt and samples/CMakeLists.txt to link Crypt32 (instead of the private conan OpenSSL).

I will investigate what this means for MinGW and Cygwin as they may need help to avoid the "OpenSSL/openssl" disaster.  Incidentally, I believe from conan's bug report that they will avoid this by only using lower-case package names in future.  https://github.com/conan-io/conan/issues/1557

README.md says _**"We recommend that you use Conan to build Exiv2 using Microsoft Visual C++".**_  Users building with CMake on VS (without conan) might need a "tweak" concerning `-DEXIV2_ENABLE_CURL` to say "openssl or winssl".  

Without conan, CMake/VS is a nightmare combination.  Thank goodness you brought conan to the party _**and**_ I was smart enough to listen to you.  This works.  And it makes sense.  **Thank You**.

**Comment by piponazo** [comment]
I am really glad to see you like the combination of these tools 😇 .

I think that whenever you want to bring dependencies in a **non** cross-platform situation, conan makes very easy to handle the dependencies. Also, it is useful if you do not want to install system packages, and you just want to bring dependencies locally to be able to configure/compile a project.

However, when dealing with cross-compilation, things become a bit more trickier. 

As I said earlier, if it is easier to just disabled webready support for that specific case, we should do it, since anyways it is not something critical in our project.
