### ISSUE TITLE
Issue #976 needs to be revisited/reopened 

### ISSUE THREAD

**Issue by tester0077** [Exiv2/exiv2#1251]
**Describe the bug**
The issue which I raised a year ago initially as part of this problem is unfortunately still present inf 0.27.3
The initial issues was the use of the function name free() as a public member of DataBuf in types.hpp

>  /*!
>    @brief Free the internal buffer and reset the size to 0.
>    */
>         void free();

Steps to reproduce the behaviour:
Compile 0.27.3 for windows static linking under MSVC and use the static library in a project.
_
> 8>D:\pkg\C++\MSVC2019\exiv2Git\exiv2\include\exiv2\types.hpp(242,14): warning C4003: not enough arguments for function-like macro invocation 'free' (compiling source file wxIcRemovLocDlg.cpp)
> 8>D:\pkg\C++\MSVC2019\exiv2Git\exiv2\include\exiv2\types.hpp(242,14): error C2059: syntax error: ',' (compiling source file wxIcRemovLocDlg.cpp)
> 9>D:\pkg\C++\MSVC2019\exiv2Git\exiv2\include\exiv2\types.hpp(242,14): warning C4003: not enough arguments for function-like macro invocation 'free' (compiling source file wxIcOptionsUpdateUi.cpp)
> 9>D:\pkg\C++\MSVC2019\exiv2Git\exiv2\include\exiv2\types.hpp(242,14): error C2059: syntax error: ',' (compiling source file wxIcOptionsUpdateUi.cpp)
_

Branch:  `0.27-maintenance`)

**Expected behavior**
User defined libraries are generally not expected/allowed to name publicly accessible functions with names corresponding/conflicting to those of the basic C libraries - in this case Exiv2 defines
  void free()
  void alloc(size_t size)
This causes conflicts with use of this function within regular code in my app.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Compiler & Version MSVC 2019
 - Compilation mode and/or compiler flags 32-bit static linking of Exiv2 lib

When I opened issue #976 - almost exactly a year ago - the discussion quickly ended up diverted towards issues of library initialization & clean up which also existed at the time.
Because I had already 'fixed my 'fork', the original free() issue did not resurface and became lost, hence #976 was closed because the initialization/cleanup issue was resolved. 

Now that I updated my code from Github, it surfaced again

For now, I can rename the function to free_() (as before) and recompile, though that is not a very satisfactory option.

Since both of these functions are used liberally throughout the exiv2 code, I could not make them 'private' to DataBuf, though I tried.

A more permanent solution might be to rename the functions in a way which would not cause conflicts with the standard C library (even C++ has a free() )  or perhaps these ought to be bracketed with some name space  constraints within the exiv2 code.
If there is a generic solution I can apply to my code, I am open to advice and/or suggestions.

**Comment by tester0077** [comment]
For Free, there are only a handful of references which would need to be fixed, for alloc() there are about 40
See the attached file
[FreeAlloc.txt](https://github.com/Exiv2/exiv2/files/4940968/FreeAlloc.txt)

**Comment by FUCKher24** [comment]
You can get me some 

The

**Comment by clanmills** [comment]
Arnold

I don't understand what the problem here, or the other issue you have reported concerning EXV_ICONV_CONST.

There is no rule about libraries not using names such as `free`.  The only rule I know concerning names is that we cannot redefine the 15 keywords in C++  such as `for` and `while`.

Exiv2::DataBuf::free() is in the Exiv2 namespace and defined.  ::free() is undefined in Exiv2 and satisfied by the C-runtime library. 

```
548 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ nm -g --demangle build/lib/libexiv2.0.27.3.2.dylib | grep free
0000000000108260 T Exiv2::DataBuf::free()
                 U ___cxa_free_exception
                 U _free
549 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ nm -g --demangle build/lib/libexiv2.0.27.3.2.dylib | grep malloc
                 U _malloc
``` 

As you know, I am willing to go to any lengths to make users happy.  In this case, I don't know why you are asking for legitimate code to be modified.

Would it be helpful to have a one-to-one discussion about this on Zoom?

**Comment by clanmills** [comment]
Arnold

We need to agree on a definition of the issue here because:
1.  I can't reproduce this.
2. Exiv2::DataBuf::free() and Exiv2::DataBuf.alloc() are in the Exiv2 0.27 API and shouldn't be changed without a very good reason.

We are disussing Exiv2::DataBuf which is defined in include/exiv2/types.hpp, right?

I'm using the following profile: 
```
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\arnold>type %USERPROFILE%\.conan\profiles\msvc2019ReleaseStatic
[build_requires]
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MT
compiler.version=16
os=Windows
arch_build=x86_64
os_build=Windows
[options]
[env]
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\arnold>
```

I have successfully built 0.27.3 as follows:

```cmd
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\arnold>conan install .. --build missing --profile msvc2019ReleaseStatic
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\arnold>cmake .. -G "Visual Studio 16 2019"
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\arnold>cmake --build . --config Release
```

I also used the IDE and build the debug.  I don't believe VS2019 offers 32-bit compilation.  I was a little surprised that the debug version wanted to link /MDd and I changed that the /MTd.  Compiled without incident.

Visual Studio has a feature to rename functions and that would make it easy to change `free` to be `arnolds_free()` and `alloc` to `arnolds_alloc()`.  Perhaps you try that and let me know.

I'm happy to set up a session on Zoom and I can see your screen and understand your issue.

**Comment by tester0077** [comment]
Hi Robin,
I will try to work around this issue outside of Exiv2 and thus will close it.
