### ISSUE TITLE
Adding XMP tag to BigTIFF file

### ISSUE THREAD

**Issue by mr4kbear** [Exiv2/exiv2#1259]
Hi there,

I'm using the simple script:

`#!/bin/bash
echo "The first argument is the path to directory with images"
echo "Second argument is the value of Xmp.Camera.GPSXYAccuracy"

DIR_PATH=$1
VALUE=$2

echo $DIR_PATH
echo $VALUE

for I in $(ls $DIR_PATH); do
    echo $I
    exiv2 -M "reg Camera http://ns.Camera.me/" -M "add Xmp.Camera.GPSXYAccuracy XmpText $VALUE"  $DIR_PATH/$I
done
`
for adding value to XMP.Camera.GPSXYAccuracy tag. 

It works very well with JPG and TIFF files but doesn't work with BigTIFF files. I searched about this issue on different BigTIFF's documentation but didn't find any explanation.

Please, help me to solve this issue or just to find an authoritative body that says that BigTIFF doesn't support adding/editing such an XMP tag.

Thanks,
Andriy

**Comment by clanmills** [comment]
Regrettably, Exiv2 doesn't support BigTiff.  We started to work on that, and the file gets opened without producing an error message.  The project to implement BigTiff has stalled.  We should throw a message an error for BigTiff files.  With which version of Exiv2 are you working?  0.27 or 'master'?

**Comment by mr4kbear** [comment]
> Regrettably, Exiv2 doesn't support BigTiff. We started to work on that, and the file gets opened without producing an error message. The project to implement BigTiff has stalled. We should throw a message an error for BigTiff files. With which version of Exiv2 are you working? 0.27 or 'master'?

Hi,

Oh, okay, thanks for this information.
I'm using a 0.27.3 version of Exiv2.

Andriy

**Comment by clanmills** [comment]
OK.  I'll submit something to the 0.27-maintenance branch to emit an error when you open a BigTiff file.

_**BigTiff Update**_ 

I am writing a book **Image Metadata _and_ Exiv2 Architecture** which is illustrated with 3000 lines of C++ code that handle many things including BigTiff.  https://clanmills.com/exiv2/book

Q. When will Exiv2 support Exiv2?
A. When somebody joins the team and makes it happen!

Thanks for using Exiv2.

**Comment by mr4kbear** [comment]
> OK. I'll submit something to the 0.27-maintenance branch to emit an error when you open a BigTiff file.
> 
> _**BigTiff Update**_
> 
> I am writing a book **Image Metadata _and_ Exiv2 Architecture** which is illustrated with 3000 lines of C++ code that handle many things including BigTiff. https://clanmills.com/exiv2/book
> 
> Q. When will Exiv2 support BigTiff?
> A. When somebody joins the team and makes it happen!
> 
> Thanks for using Exiv2.
> ![tiff](https://user-images.githubusercontent.com/529982/89684512-8697c500-d8f2-11ea-8357-b453fe974fa3.png)

Hi Robin,

Can I ask you, what might cost for you to add the supporting of adding/editing the XMP.Camera.GPSXYAccuracy tag for BigTIFF images using Exiv2? I really need this functionality.

Thanks,
Andriy

**Comment by clanmills** [comment]
I don't know how much time it would take to add BigTiff support to Exiv2.  The TiffParser in Exiv2 is about 10,000 lines of C++.  It's easy to say "not much to that", however nothing turns out to be like that.  The last time we added a new image format (WebP), it took about a month and consumed 100-200 engineering hours.  https://dev.exiv2.org/issues/1199#note-17

The good news is that I totally understand BigTiff and have written a new (read-only) parser which is documented in my book.  https://clanmills.com/exiv2/book

My current status is explained here:  https://github.com/Exiv2/exiv2/issues/1186#issuecomment-670359066

I want to finish my book and retire.  Regrettably, I am declining your offer of consultancy.  I suggest you open a new issue on GitHub with a title such as "Consultant Wanted".  In C-19 times, somebody may be very interested in undertaking your request.  If somebody undertakes the work, I will help by donating 5 hours of free consultancy to assist them.

**Comment by clanmills** [comment]
https://github.com/Exiv2/exiv2/pull/1331
