### ISSUE TITLE
Visual Studio 2019 build notes

### ISSUE THREAD

**Issue by moon6969** [Exiv2/exiv2#1394]
The exiv2 Visual Studio build process described in README-CONAN.md is by far the smoothest I've seen on a non-trivial build process (especially once I discovered step [2.2 Visual Studio Notes](https://github.com/Exiv2/exiv2/blob/master/README-CONAN.md#22-visual-studio-notes)!).
Kudos.

I would like to suggest two small improvements...
#### Update [CMake Generators for Visual Studio](https://github.com/Exiv2/exiv2/blob/master/README-CONAN.md#cmake-generators-for-visual-studio) to include Visual Studio 2019
It looks like the format has changed slightly compared to 2017 and earlier. The architecture is a seperate parameter:
cmake .. -G "Visual Studio 16 2019" -A x64
cmake .. -G "Visual Studio 16 2019" -A Win32
(Source: https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html)

#### Explain where to find exv_conf.h & exiv2lib_export.h
The source include files (exiv2-0.27.3\include) reference generated exv_conf.h & exiv2lib_export.h files in the root of your build folder. It took me a while to figure out where they were since they are not in exiv2-0.27.3\include or the build\include folder
(let's just say I am not best pleased with Windows search indexing!)

**Comment by moon6969** [comment]
Please change label to Documentation.

**Comment by clanmills** [comment]
Thanks for your kind remarks about the documentation.  I put a lot of effort into those documents as it saves the user time and it saves me time having to answer questions.

I didn't document Visual Studio 2019 when I wrote those notes for v0.27 in 2018.  I was mistakenly of the believe that 32bit build support had been removed from VS2019.  Ah, it's the new `-A arch` argument.

I don't understand your comment `Please change label to Documentation.`.

I will give the docs a revision later in the week.  Thank You for your comments. 

I always install Cygwin (or MinGW/msys2) on my Windows machines and have the Unix commands on my PATH.  So the command `$ find . -name exv_conf.h` would do the trick.  Dos affectionados: `> dir/s exv_conf.h`.  I've never made the effort to learn the PowerShell.

**Comment by moon6969** [comment]
> I don't understand your comment Please change label to Documentation..

Already fixed :heavy_check_mark: ↑↑↑  _clanmills added documentation and removed FeatureRequest labels 1 hour ago_

**Comment by clanmills** [comment]
Right.  I changed the label without realising that's what you meant.  Changing that document would be an easier text editing job if Visual Studio 2021 was here because there are tables with 2017 | 2015.  It'd be easier to add 2021 | 2019.  Don't know Microsoft's intention:  https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap

This is a "Friday afternoon" job.

**Comment by clanmills** [comment]
There's a Visual Studio 2019 "Preview" Community Edition.  I'll document "2019 | 2019 Preview" and that will keep the 2-up layout.  That'll work out well.  If Microsoft ship VS2021, Preview will morph.

Lots of good stuff coming up in Visual Studio including C++20 support and native build/debug for Linux on WSL.  I've been using Visual Studio since Visual C++ v2.0 which was about 1996 or so.  I used to develop Exiv2 on Visual Studio and port to the other platforms.  My primary tool today in Xcode on macOS.  For sure Visual Studio is big beast.

**Comment by moon6969** [comment]
Thanks - sounds good.

> I've been using Visual Studio since Visual C++ v2.0 which was about 1996 or so  

Me too! but I abandoned C++ after Y2K for it's managed (and some would say illegitimate) offspring.

**Comment by clanmills** [comment]
I believe you are looking at README.md and README-CONAN.md in the 'master' branch.  Both of those were revised in May for Exiv2 v0.27.3 on the 0.27-maintenance branch to deal with Visual Studio 2019.

I've given those documents a "Friday Afternoon" revision and submitted a PR: #1403  Comments welcome.  I'll send you an invitation to join Team Exiv2, then I can assign you to "approve" the PR.  I'm not going to assign work to you, unless you wish to contribute.

I've added a couple of new profiles for 32 bit support.  I'll test them before I merge this PR.  Friday Night.  Time for Steak 🥩 with 🍷 and perhaps a :beer: and later I will play 🎹 and 🎺
