### ISSUE TITLE
Fix cppcheck performance issues

### ISSUE THREAD

**Issue by heckflosse** [Exiv2/exiv2#1459]
I ran cppcheck on exiv2 source and it found some performance issues which though not critical, can be fixed.

example:

![grafik](https://user-images.githubusercontent.com/13733487/105749764-29e1a280-5f44-11eb-984a-f11635467e13.png)

using std::string a.find(b) == 0 is not efficient to check whether a begins with b
using std::string a.starts_with(b) is only available for C++20

using std::string a.rfind(b, 0) == 0 is more efficient than the currect code for this cases

Any objection to make a pr for this ?

**Comment by clanmills** [comment]
If you know of ways to make things better, I'm happy to accept a PR.

Observations:
1.  The 0.27-maintenance branch is required to build with C++98.
2.  There are std::string and std::wstring versions of that function.
3.  This is an edge case.  However that code is executed every time you open any file, so a little polish is worth-while.  I doubt if you'll be able to measure the performance different.  I might test/document the performance gain on your PR using photo library (of 80,000 images).

**Comment by clanmills** [comment]
Whoops.  Didn't intend to close.  Wrong button.

**Comment by heckflosse** [comment]
> I doubt if you'll be able to measure the performance different.

I doubt this as well. But for me (not being very familare with exiv2 code) I needed a starting point for contribution. Will take a while to make better prs ;-)

**Comment by clanmills** [comment]
It takes a while to find your way around 100k lines of code.  And for sure it's easier to start on something like this that is easy to understand.  Some of the recursive metadata parsing a lot harder to understand.

However, I've written a book to explain how it works.  My tools to understand Exiv2 were bug-reports, the code, the debugger, specifications and my brain.   Andreas had it even harder as he didn't even have the code!

**Comment by heckflosse** [comment]
> The 0.27-maintenance branch is required to build with C++98

Oh, didn't know that. Lot to learn...

**Comment by clanmills** [comment]
0.27-maintenance is a maintenance release and hasn't been "modernised" for C++11.  You can build it with:

```bash
$ cmake .. -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_FLAGS=-Wno-deprecated
```

However, that's using some AutoPtr compatibility magic in C++11/14 that does not ship in C++17 and later.  After we release 0.27.4, the next objective has to be release master as v0.28.  I hope v0.28 will support C++20.  Luis has done the work on 'master' to convert the code to UniquePtr instead of AutoPtr.

I thought of another amazing achievement by Andreas.  He discovered how to decode/encode the manufacturer's (undocumented) binary maker-notes. I don't think there was much ExifTool documentation in 2004/5/6.  Clever guy, Andreas.
