### ISSUE TITLE
Possible null pointer dereference in asfvideo.cpp reported by cppcheck

### ISSUE THREAD

**Issue by heckflosse** [Exiv2/exiv2#1463]
in line 490 test is set to NULL

```
Exiv2::RiffVideo *test = NULL;`
```

and in line 523 it is dereferenced
```
xmpData_["Xmp.audio.Codec"] = test->printAudioEncoding(temp);
```

I don't know how to fix this correctly. @clanmills any idea?

**Comment by clanmills** [comment]
That's clearly a bug and not exercised by the test suite.  Looking at the code, it seems this concerns Audio_Media (sound) and we probably only test Video_Media.

The Video Code is deprecated and has been removed from master.   It was written in 2012 by a GSoC Student who did a half decent job.  In fact he did really well to write 4 image handlers and test code in 10 weeks.  There has always been higher priority issues than giving the video code the attention it deserves. 

I think we should close this as "won't_fix" because:

1. It requires considerable investigation.
2. We should start testing sound files.
3. This code is end of life.

Alternatively, we could throw kerUnsupportedImageType when stream == 2.

**Comment by heckflosse** [comment]
If it's end of life code, I'm fine with closing as `won't fix` :+1:
