### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by heckflosse** [Exiv2/exiv2#1465]
@clanmills 

Here 

https://github.com/Exiv2/exiv2/blob/0.27-maintenance/src/xmpsidecar.cpp#L146

I see room for improvement (faster processing). Though I have no clue whether this part is performance relevant at all

Ingo

**Comment by clanmills** [comment]
@heckflosse The sidecar files are very much a "edge" feature of Exiv2.  XMP can be stored as XML in a stand-alone file.  I think this is used to store metadata if there is no specification to embed the XMP in the image itself.  For example: Windows bmp.  Adobe mention in XMPSpecificationPart3.pdf _Storage in Files_:

**2.2.6 MPEG-2**

_MPEG-2 is a standard for the generic coding of moving pictures and associated audio information. It describes a combination of lossy video compression and lossy audio compression (audio data compression) methods which permit storage and transmission of movies using currently available storage media and transmission bandwidth. It is not the same as MPEG-1 Audio Layer II (MP2)._

_MPEG-2 is a common format for standard definition digital video. It is used for DVD discs, by DV camcorders, for terrestrial (over the air) broadcast, for cable, and direct broadcast satellite. The formal specification for MPEG-2 is ISO/IEC 13818._

_XMP is not directly embedded within MPEG-2 files, but is specified as a sidecar file. This is a separate file containing just the XMP packet, which is stored at the same location as the MPEG-2 file, and uses the same file name, with the file extension .xmp replacing the original file extension._

Most of the code in that file has been untouched since 2008.  I have modified some of that code more recently and you can read the issue reports referenced in the code to learn why.

I would say "If it's not broken, don't fix it.".

**Comment by heckflosse** [comment]
> I would say "If it's not broken, don't fix it.".

Alright.
