### ISSUE TITLE
heap-buffer-overflow Read in Exiv2::WebPImage::doWriteMetadata

### ISSUE THREAD

**Issue by henices** [Exiv2/exiv2#1571]

**Comment by clanmills** [comment]
@henices  Thanks for visiting.  By co-incidence @yuawn _(an engineer in Taiwan)_ is also investigating Exiv2 security matters.  @kevinbackhouse is organising Security Advisories.  So, we are taking your concerns seriously.

Exiv2 has to balance our engineering resources between many matters.  Features, bugs, build, test, documentation, security, user support and so on.  Our schedule is to release v0.27.4 on 2021-05-22.  The next project is Exiv2 v1.0 and scheduled for 2021-12-15.  The fix for any security matters you report during the development of v1.0 will be back-ported into Exiv2 v0.27.5 which will also ship on 2021-1215.

There will be a team meeting to discuss v1.00 on Saturday 2021-04-25.  You and @yuawn are welcome to join us.  https://discuss.pixls.us/t/kick-off-exiv2-v1-0/24610
