### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [Exiv2/exiv2#184]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by D4N** [comment]
Hi, we are actually already using Conan to obtain our build dependencies on Windows. However the Conan support is still experimental and has been only present for a short while.

@piponazo Introduced Conan to the code base. We could put making a conan package on the todo list?

**Comment by clanmills** [comment]
@ZaMaZaN4iK Thanks for bringing up this subject.  Indeed we'd like to adopt Conan in our build system.  @piponazo joined the team in July 2017 and has done very good work to rewrite our CMake support (and lots of other good contributions).

Ultimately, we want to replace the elderly build systems:  config/ contains the code for autotools (./configure).  msvc/ contains Visual Studio solution and project files.  Currently msvc/CMake support of dependencies is supported using scripts in contrib/cmake/msvc.  It has been a long term goal of Exiv2 (since before I joined the project 10 years ago) to drop ./configure and msvc/ support, however we have not yet arrived at the point where I feel CMake is a solid replacement for all platforms.  The effort invested in contrib/cmake/msvc to get CMake/Visual Studio to build successfully on Visual Studio 2005/8/10/12/13/15/17 has been considerable.  I'll be delighted to learn how conan can replace that code.

Our CMake support on Linux, MacOS-X and Cygwin is solid and is my preferred build environment on those platforms.  I've given up supporting MinGW (32 or 64) with CMake.  There's an outstanding request to build on msys/2.0.  http://dev.exiv2.org/issues/1310

If you'd like to help us to work to make conan/CMake a robust replacement for our existing infrastructure, I'd be delighted to accept your contribution.  If you wish to take on this challenge, please discuss it with Luis (@piponazo) to avoid duplication and/or confusion.

**Comment by piponazo** [comment]
Hi @ZaMaZaN4iK, thanks for bringing this topic to discussion. 

I actually started to contribute in Exiv2 with the objective of creating a conan package for it. I even have an skeleton of the recipe on this repository:

https://github.com/piponazo/conan-exiv2

As @D4N mentioned, I introduced some experimental conan support internally to bring the Exiv2 dependencies (this is used on all the platforms when we run the CI jobs on travis-ci and AppVeyor).

At some point I will resume the work on that conan-exiv2 repository to have a conan recipe for Exiv2, but I cannot guarantee when this will be.

Meanwhile, any help over there would be more than welcomed ;)

**Comment by ZaMaZaN4iK** [comment]
I recommend you push ypur conan recipe to Bincrafters repo.

**Comment by piponazo** [comment]
That's a good idea although I would like to target the conan-central repository (that should be the one were official recipes should be maintained). I will try to give a push to conan during the next weeks.

**Comment by piponazo** [comment]
I am closing this issue. Now that I have a version of the conan recipe that is working with the standard combination of Operative Systems and Compilers for conan recipes:

https://github.com/piponazo/conan-exiv2/tree/testing/0.27

As soon as we release the final version of 0.27, I'll move the recipe to the stable channel and I'll ask for place it in the **conan-center** conan repository.
