### ISSUE TITLE
JP2 images are not consistently reading exif, iptc, and xmp.

### ISSUE THREAD

**Issue by henryborchers** [Exiv2/exiv2#185]
The latest bug patches involving the jp2 files helped me read a number of our jp2 files. Thanks for that.

Good news. I can now extract ICC header from everything I've thrown at it. The bad news is that I'm still having issues trying to read Exif, IPTC, and XMP with the majority of the jp2 files I throw at it. 

With these problematic jp2 files, I can get the ICC profile, pixel height, and pixel width but calls to iptcData(), exifData(), and xmpData() return no results.  I also get the message "Error: XMP toolkit error 201: XML parsing failure. Warning: failed to decode XMP metadata" printed to stderr.  

I've tested these files with exiftool, and they all do have metadata.

**Comment by clanmills** [comment]
I seem to recall that the XMP in your JP2 file is malformed.  It's lot legal XMP and that's why the XMPsdk (which is embedded in Exiv2) is complaining.  That exiftool doesn't complain is curious, however that's not make the XMP valid.

Can you attach a couple of JP2 files and I will investigate.

**Comment by henryborchers** [comment]
@clanmills, you are the best person on the Internet!
Free free to use the following files.
[test_files.zip](https://github.com/Exiv2/exiv2/files/1532315/test_files.zip)

One thing I just noticed was when I ran exiftool on my files, it reported "XMP Toolkit : XMP Core 5.1.2" However, the XMP_API_VERSION macro in xmpsdk/include/XMP_Version.h is defined as 4.4. Any way this could be the issue?

**Comment by clanmills** [comment]
Ah, Henry.  Flattery will get you everywhere!

I can't comment on the XMP_Version as I don't know much about the XMPsdk.  We have an on-going project to enable Exiv2 to be built with a choice of XMPsdk 2013/14/16 (and the existing 4.4 code that is in the Exiv2 code base).  Because of other commitments, _**at the earliest**_, that project will not be released in the Exiv2 code base until v0.28 (scheduled late 2018).

I think you sent me a huge zip before with GBytes of data and I noticed that the XMP was malformed.  However, at that time, I was focused on our discussion about ColorSpace and ICC, so I avoided discussing XMP.

There isn't any XMP data in your test files:
```
508 rmills@rmillsmbp:~/Downloads/test_files $ exiv2 -pR *.jp2
STRUCTURE OF JPEG2000 FILE: 00000001.jp2
 address |   length | box       | data
       0 |       12 | jP        | 
      12 |       20 | ftyp      | 
      32 |       71 | jp2h      | 
      40 |       22 |  sub:ihdr | .............
      62 |       15 |  sub:colr | ....... | pad: 1 0 0 | iccLength:17
      77 |       26 |  sub:res  | ....resd.<...<....
     103 |        1 | uuid      | ????: 
     104 |      373 | uid      | 
     477 | 978543985 | >
<      | 
STRUCTURE OF JPEG2000 FILE: 00000002.jp2
 address |   length | box       | data
       0 |       12 | jP        | 
      12 |       20 | ftyp      | 
      32 |       71 | jp2h      | 
      40 |       22 |  sub:ihdr | .............
      62 |       15 |  sub:colr | ....... | pad: 1 0 0 | iccLength:17
      77 |       26 |  sub:res  | ....resd.<...<....
     103 |        1 | uuid      | ????: 
     104 |      373 | uid      | 
     477 | 978543985 | >
<      | 
STRUCTURE OF JPEG2000 FILE: 00000003.jp2
 address |   length | box       | data
       0 |       12 | jP        | 
      12 |       20 | ftyp      | 
      32 |       71 | jp2h      | 
      40 |       22 |  sub:ihdr | ...K.........
      62 |       15 |  sub:colr | ....... | pad: 1 0 0 | iccLength:17
      77 |       26 |  sub:res  | ....resd.<...<....
     103 |        1 | uuid      | ????: 
     104 |      373 | uid      | 
     477 | 978543985 | >
<      | 
509 rmills@rmillsmbp:~/Downloads/test_files $ 
```
Can you provide me with a single test file that generates the message:  'Error: XMP toolkit error 201: XML parsing failure. Warning: failed to decode XMP metadata'.

**Comment by henryborchers** [comment]
oops. Sorry. sent the wrong set

**Comment by henryborchers** [comment]
Here we go again. 
[test_files2.zip](https://github.com/Exiv2/exiv2/files/1532651/test_files2.zip)

**Comment by henryborchers** [comment]
```
C:\Users\hborcher>C:\Users\hborcher\Downloads\2015\Win32\dll\Release\bin\exiv2.exe -pa D:\hathigood\2693684\00000003.jp2
Error: XMP Toolkit error 201: XML parsing failure
Warning: Failed to decode XMP metadata.
```

**Comment by henryborchers** [comment]
If these errors are truly due to a malformed xml, I'd be happy to simply capture that error instead of it simply printing to stderr.  However, I couldn't find a way to do so.

**Comment by clanmills** [comment]
I've reproduced your error.  I'm debugging and messing about with this at the moment.  From memory, I think readMetadata() gets very upset by XMPsdk errors and rejects the whole file.  However let me spend a little more time to understand the situation.  I'm quite confident that we'll find an easy fix.  Relax.  All will be good (tomorrow).

**Comment by henryborchers** [comment]
You truly are the best!

**Comment by clanmills** [comment]
Henry

I know what's wrong here.  Together we'll figure out a fix.  However let's first discuss what's wrong.

The XML in your file is malformed.  Here's what you have:
```
547 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ bin/exiv2 -pR ~/Downloads/test_files2/00000001.jp2 
STRUCTURE OF JPEG2000 FILE: /Users/rmills/Downloads/test_files2/00000001.jp2
 address |   length | box       | data
       0 |       12 | jP        | 
      12 |       20 | ftyp      | 
      32 |     7328 | jp2h      | 
      40 |       22 |  sub:ihdr | .............
      62 |     7272 |  sub:colr | ......]Lino....mntrRGB XYZ .. | pad: 2 0 0 | iccLength:7261
    7334 |       26 |  sub:res  | ....resd.(...(....
    7360 |     7637 | uuid      | XMP : <?xpacket begin="..." id="W5M0MpCehiHzre
   14997 |        0 | jp2c      | 
```

When I extract the "raw XMP" and pipe it to xmllint, disaster:
```
548 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ bin/exiv2 -pX ~/Downloads/test_files2/00000001.jp2 | xmllint -
-:9: parser error : error parsing attribute name
   <photoshop:ColorMode>3</photoshop:ColorMode>
   ^
-:9: parser error : attributes construct error
   <photoshop:ColorMode>3</photoshop:ColorMode>
...
```

The XML is incorrect.  You can extract it with Exiv2 of course.  However to prove beyond doubt that the issue is in your file, I've extracted it with dd (the disk death and destruction utility):
```
549 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ dd bs=1 count=$((7637-21)) skip=$((7363+21)) if=~/Downloads/test_files2/00000001.jp2 of=foo.xmp
7616+0 records in
7616+0 records out
7616 bytes (7.6 kB) copied, 0.085954 s, 88.6 kB/s
550 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ 
```
The values 7363 and 7637 come from the output of `$ exiv2 -pR` above (it's the offset and length of the XMP block).  21 is the size of the jp2+XMP header

When you examine foo.xmp, you'll see:
```
<?xpacket begin="Ôªø" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.1.2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:aux="http://ns.adobe.com/exif/1.0/aux/"
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"

   <photoshop:ColorMode>3</photoshop:ColorMode>
   <photoshop:ICCProfile>sRGB IEC61966-2.1</photoshop:ICCProfile>    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
...
   <tiff:Model>P65+</tiff:Model>
</rdf:Description>
</rdf:RDF>
</x:xmpmeta>
```
The tag <rdf:Description ..... isn't closed!  We need a '>' between photoshop/1.0/" and <photoshop:ColorMode>

Why does exiftool forgive this?  I don't know, ask Phil.

How can we fix this?  Lots of ways.  The most obvious is to use a utility to repair your files.  I think you can fix it with a sed script:
```
558 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ od -a foo.xmp | head -30
0000000    <   ?   x   p   a   c   k   e   t  sp   b   e   g   i   n   =
0000020    "   ?   ?   ?   "  sp   i   d   =   "   W   5   M   0   M   p
0000040    C   e   h   i   H   z   r   e   S   z   N   T   c   z   k   c
0000060    9   d   "   ?   >  nl   <   x   :   x   m   p   m   e   t   a
0000100   sp   x   m   l   n   s   :   x   =   "   a   d   o   b   e   :
0000120    n   s   :   m   e   t   a   /   "  sp   x   :   x   m   p   t
0000140    k   =   "   X   M   P  sp   C   o   r   e  sp   5   .   1   .
0000160    2   "   >  nl  sp   <   r   d   f   :   R   D   F  sp   x   m
0000200    l   n   s   :   r   d   f   =   "   h   t   t   p   :   /   /
0000220    w   w   w   .   w   3   .   o   r   g   /   1   9   9   9   /
0000240    0   2   /   2   2   -   r   d   f   -   s   y   n   t   a   x
0000260    -   n   s   #   "   >  nl  sp  sp   <   r   d   f   :   D   e
0000300    s   c   r   i   p   t   i   o   n  sp   r   d   f   :   a   b
0000320    o   u   t   =   "   "  nl  sp  sp  sp  sp   x   m   l   n   s
0000340    :   x   m   p   =   "   h   t   t   p   :   /   /   n   s   .
0000360    a   d   o   b   e   .   c   o   m   /   x   a   p   /   1   .
0000400    0   /   "  nl  sp  sp  sp  sp   x   m   l   n   s   :   a   u
0000420    x   =   "   h   t   t   p   :   /   /   n   s   .   a   d   o
0000440    b   e   .   c   o   m   /   e   x   i   f   /   1   .   0   /
0000460    a   u   x   /   "  nl  sp  sp  sp  sp   x   m   l   n   s   :
0000500    p   h   o   t   o   s   h   o   p   =   "   h   t   t   p   :
0000520    /   /   n   s   .   a   d   o   b   e   .   c   o   m   /   p
0000540    h   o   t   o   s   h   o   p   /   1   .   0   /   "  nl  nl    <---- change nl nl to >nl
0000560   sp  sp  sp   <   p   h   o   t   o   s   h   o   p   :   C   o
0000600    l   o   r   M   o   d   e   >   3   <   /   p   h   o   t   o
0000620    s   h   o   p   :   C   o   l   o   r   M   o   d   e   >  nl
0000640   sp  sp  sp   <   p   h   o   t   o   s   h   o   p   :   I   C
0000660    C   P   r   o   f   i   l   e   >   s   R   G   B  sp   I   E
0000700    C   6   1   9   6   6   -   2   .   1   <   /   p   h   o   t
0000720    o   s   h   o   p   :   I   C   C   P   r   o   f   i   l   e
559 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ 
```
I don't want to offer you the code for that script because I might fix one file and damage the rest of your archive.

Here are other possibilities.  I'm sure you'll think of other fixes:

1) I could add code to jp2image.cpp "sniff the XML" and fix it "on the fly".  I strongly dislike such hacks.  It could work for you and cause trouble for others.  
2) Exiv2 could ignore the illegal XML, proceed to do Exif, IPTC, ICC processing.  That may cause a warning, however it will probably enable you to achieve your goals.  If you rewrite the file (with writeMetadata()), I could either write the broken XML, not write any XML, fix it "on the fly", or refuse to rewrite the file.

I'm hoping you'll be able to either repair the files (with sed or other magic), or accept option 2 (ignore the bad XML and NOT rewrite the files).

Over to you buddy.  What cha' wanna do 'bout this?

**Comment by henryborchers** [comment]
Hi Robin,

Thank you for going above and beyond with this. More open source projects need people like you.

Anyways, I was doing my own sleuthing last night with a hex editor and came to this exact realization that the xml is malformed. Thank you for confirming this and I really appreciate the advice on how to fix our images. However, I'm actually not interested in "fixing" these images right now. After all, these images are just part of test collection I'm using. (they were supposed to be the good ones, but we seem to have discovered otherwise...) I'm actually more interesting in detecting when something going wrong from images produced by our in-house student image scanning technicians or our digitization vendors (Since we are a state university with limited budget going to the library, we are often forced to work with the lowest bid vendors who often cut corners).

Of your suggestions, number 2 seems the most useful since I'm only interested in reading the metadata.

The biggest issue that I have is that when I call readMetadata() on one of these files, the message "Error: XMP Toolkit error 201: XML parsing failure" only prints to standard error but doesn't throw an exception for this error not does the method have a return value. If there was a high level way of capturing this information instead of losing it to stderr, I'd could do everything that I needed for image quality control. 

Am I wrong? Is there another place that this error/warning is being stored and I have to access it manually?

**Comment by clanmills** [comment]
The reason you have no IPTC and EXIF data is because your file doesn't contain that data:
```
533 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ bin/exiv2 -pS ~/Downloads/test_files2/00000001.jp2
STRUCTURE OF JPEG2000 FILE: /Users/rmills/Downloads/test_files2/00000001.jp2
 address |   length | box       | data
       0 |       12 | jP        | 
      12 |       20 | ftyp      | 
      32 |     7328 | jp2h      | 
      40 |       22 |  sub:ihdr | .............
      62 |     7272 |  sub:colr | ......]Lino....mntrRGB XYZ .. | pad: 2 0 0 | iccLength:7261  <--- The ICC profile
    7334 |       26 |  sub:res  | ....resd.(...(....
    7360 |     7637 | uuid      | XMP : <?xpacket begin="..." id="W5M0MpCehiHzre   <--- Here's the XMP
   14997 |        0 | jp2c      | 
534 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ 
```
Here's a test file with "the works"
```
534 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ bin/exiv2 -pS ../test/data/Reagan.jp2 
STRUCTURE OF JPEG2000 FILE: ../test/data/Reagan.jp2
 address |   length | box       | data
       0 |       12 | jP        | 
      12 |       20 | ftyp      | 
      32 |       45 | jp2h      | 
      40 |       22 |  sub:ihdr | .............
      62 |       15 |  sub:colr | ....... | pad: 1 0 0 | iccLength:16
      77 |     1342 | uuid      | Exif: II*...........................>........
    1419 |      942 | uuid      | IPTC: ............040621-N-6536T-062.....5...
    2361 |     5590 | uuid      | XMP : <?xpacket begin="..." id="W5M0MpCehiHzre
    7951 |    32658 | jp2c      | 
535 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ 
```

I haven't understood your request "to access it manually".  The error is occurs here in jp2image.cpp#400
```
                        if(bIsXMP)
                        {
#ifdef DEBUG
                           std::cout << "Exiv2::Jp2Image::readMetadata: Xmp data found" << std::endl;
#endif
                            rawData.alloc(box.length - (uint32_t)(sizeof(box) + sizeof(uuid)));
                            bufRead = io_->read(rawData.pData_, rawData.size_);
                            if (io_->error()) throw Error(14);
                            if (bufRead != rawData.size_) throw Error(20);
                            xmpPacket_.assign(reinterpret_cast<char *>(rawData.pData_), rawData.size_);

                            std::string::size_type idx = xmpPacket_.find_first_of('<');
                            if (idx != std::string::npos && idx > 0)
                            {
#ifndef SUPPRESS_WARNINGS
                                EXV_WARNING << "Removing " << static_cast<uint32_t>(idx)
                                            << " characters from the beginning of the XMP packet" << std::endl;
#endif
                                xmpPacket_ = xmpPacket_.substr(idx);
                            }

                            if (xmpPacket_.size() > 0 && XmpParser::decode(xmpData_, xmpPacket_))
                            {
#ifndef SUPPRESS_WARNINGS
                                EXV_WARNING << "Failed to decode XMP metadata." << std::endl;
#endif
                            }
                        }
                    }
                    break;
                }
```
When the code calls XmpParser::decode(...), that descends into the XMPsdk which writes the message to stderr and returns false (meaning decode failed).

I think the fix for you is to modify the xmpData_ and xmpPacket_ on the fly to perform a change something like (in sed syntax) s:#photoshop/1.0/"\n\n#photoshop/1.0/">\n#

I'm not sure, without walking the code in the debugger, why this function expects a buffer and a string.  Please be careful not to change the size of the buffer.

I'm quite confident that you'll be able to get this to work, however I'm unwilling to include such a hack in the Exiv2 code base.  However, this is open-source and you are welcome to change it on your local machines. 

I think you have to fix your input files.  The file is malformed and should be fixed before being presented to Exiv2 (or any other image processing code).

Please be aware that when you've fixed the error in the XMP, your progress is small.  I'm not sure what you're doing with those files.  You may be no closer to your goal.

---------------------------

On the subject of resources, I can say I've never worked anywhere in which there we sufficient resources.  And the bigger the organisation, the harder it is to get resources.  The world is actually operated by a small number of people (like you and I) who take ownership.  When things are broken, we figure out a fix/solution/work-around.

**Comment by henryborchers** [comment]
Oh I think I see. 

Let me see if I got this right.  The warning message "Failed to decode XMP metadata" is being sent to a log handler and the default behavior is to send EXV_WARNING and EXV_ERROR log messages to stderr.

If this is assumption is correct, all I would need to do is to redirect the log handler to go into my own variable.

**Comment by clanmills** [comment]
You can suppress the message by rebuilding the library with the compiler flag: -DSUPPRESS_WARNINGS.  Like this:
```
538 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ bin/exiv2   ~/Downloads/test_files2/00000001.jp2 
Error: XMP Toolkit error 201: XML parsing failure
Warning: Failed to decode XMP metadata.
File name       : /Users/rmills/Downloads/test_files2/00000001.jp2
File size       : 4996717 Bytes
MIME type       : image/jp2
Image size      : 2011 x 3000
/Users/rmills/Downloads/test_files2/00000001.jp2: No Exif data found in the file
539 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ cd .. ; rm -rf build ; mkdir build ; cd build
540 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ env CXXFLAGS=-DSUPPRESS_WARNINGS cmake .. 
561 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ env CXXFLAGS=-DSUPPRESS_WARNINGS make 
....
562 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ bin/exiv2 ~/Downloads/test_files2/00000001.jp2 
File name       : /Users/rmills/Downloads/test_files2/00000001.jp2
File size       : 4996717 Bytes
MIME type       : image/jp2
Image size      : 2011 x 3000
/Users/rmills/Downloads/test_files2/00000001.jp2: No Exif data found in the file
561 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $
```
I'm not sure what benefit this brings to you.  We've only made the message disappear.  The behaviour of the library hasn't changed.  readMetadata() will no longer write a warning on errout, however you will not have any Exif or IPTC data because the file contains neither.

I have a suggestion to make.  Would it help to discuss your application on Skype (or FaceTime or Google Hangout).  Can you suggest a couple of possible times for us to talk 1-to-1 on Thursday or Friday?

**Comment by henryborchers** [comment]
I can't full express how much that would mean to me. I'll send you an email. 

I'll close this issue since it seems like it's no longer relevant.

**Comment by kamiccolo** [comment]
Mhm. I've just hit another case of this error with different image format (.IIQ) and valid (from the looks) XML. And it does not work with exiv2, but dumps correctly using XMP-Toolkit-SDK directly.

Culprint seems to be different versions of libexpat in use.
Non-working (exiv2 I've built with) - 2.2.5-3ubuntu0.2
Working (XMP-Toolkit-SDK is recommended to build with) - 2.1.0

o_0

**Comment by kamiccolo** [comment]
Mhm. Weird, I've just took exiv2 built based on expat 2.4.1, and still can get an XMPValidator error o_0
I do suspect a regression, but still need to investigate further.
