### ISSUE TITLE
"Nightly" vs "0.27-nightly" builds

### ISSUE THREAD

**Issue by jim-easterbrook** [Exiv2/exiv2#1945]
I've successfully compiled and used the various nightly releases and v0.27.5-RC3, but I've noticed that "0.27-nightly" appears to actually be using the v1.0.0 code. It has the -std=c++11 stuff like unique ptr instead of auto ptr, and versionString() returns "1.0.0". The "0.27.5-RC3" release goes back to auto ptr and versionString() returns "0.27.5".

Should I just ignore "0.27-nightly" releases?

PS I've written a Python interface to libexiv2 (https://github.com/jim-easterbrook/python-exiv2) which uses SWIG to create Python classes for each of the libexiv2 top level classes. This all seems to be working nicely, but SWIG can't parse the "static constexpr auto" expression in datasets.hpp (v1.0.0). I've got a workaround, but (as a non C++ programmer) I wonder if private data declarations need to be in the .hpp files at all.

**Comment by clanmills** [comment]
@jim-easterbrook Good to hear from you.  Hope everything's good with you.  I'm retiring from Exiv2.  When v0.27.5 reaches GM (scheduled 2021-10-22), I'm finished.

Exiv2 has been running two major branches since v0.27 shipped in December 2018.  Branch `0.27-maintenance` continues to use C++98 and auto\_ptr.  Branch `main` uses C++11 (and later) and unique\_ptr.

I haven't been involved with the nightly release builds.  I thought they were only on `main`.

I like the sound of using SWIG.  gexiv2 uses reflexion to wrap exiv2 for use from python.  I've never got it to work.  When I joined exiv2 in 2008, I ported pyexiv2 to Visual Studio and Xcode for use on Windows and macOS.  Regrettably, pyexiv2 has fallen into disrepair.  There is a py3exiv2 wrapper which I've never got to build on Windows or macOS.  I don't know the meaning of `static constexpr auto` in datasets.hpp.   Sounds C++11 magic and can probably be replaced with something that SWIG understands.  I've tried `static const std::string familyName_ = "Iptc";` however the compiler refuses accept that.  I'm sure there will be a work-around, but I'm too old to understand C++11.

**Comment by jim-easterbrook** [comment]
Hi Robin, thanks for all your work on Exiv2 over the years, and enjoy your retirement from it.

All the Python wrappers I've tried over the years have had their problems, which is why I decided to have a go at doing a better job. SWIG is what I know so it's the tool I use. I'm also doing "binary wheels" to make installation easy on Windows and Linux. (If I had a copy of MacOS I could probably do them for Mac as well.)

I get past the `static constexpr auto` problem by replacing `auto` with `std::string`. It doesn't need to be valid C++ as SWIG ignores the private members anyway. I just need to persuade SWIG not to bail out when it sees the expression.

I don't expect Exiv2 to drop use of `static constexpr auto` - that would be the tail wagging the dog. Ideally SWIG will fix the bug, but that might take a while.

**Comment by clanmills** [comment]
@jim-easterbrook Can you try this patch to address your SWIG situation.  If this fixes SWIG, I'll leave it to Team Exiv2 to decide about accepting this in `main`.

```diff
diff --git a/include/exiv2/datasets.hpp b/include/exiv2/datasets.hpp
index 02bad185..298e4f20 100644
--- a/include/exiv2/datasets.hpp
+++ b/include/exiv2/datasets.hpp
@@ -332,7 +332,7 @@ namespace Exiv2 {
         IptcKey* clone_() const override;
 
         // DATA
-        static constexpr auto familyName_ = "Iptc";
+        static const char* familyName_;
 
         uint16_t tag_;                 //!< Tag value
         uint16_t record_;              //!< Record value
diff --git a/src/datasets.cpp b/src/datasets.cpp
index 9cd62df5..c55c826f 100644
--- a/src/datasets.cpp
+++ b/src/datasets.cpp
@@ -39,6 +39,8 @@
 // *****************************************************************************
 // class member definitions
 namespace Exiv2 {
+    const char* IptcKey::familyName_ = "Iptc";
+    
     constexpr RecordInfo IptcDataSets::recordInfo_[] = {
         {IptcDataSets::invalidRecord, "(invalid)", N_("(invalid)")},
         {IptcDataSets::envelope, "Envelope", N_("IIM envelope record")},
```

**Comment by clanmills** [comment]
@jim-easterbrook I'm happy to give you SSH access to my MacMini to build/test your code.  The GitHub CI provides macOS builder nodes.  I can't remember how that works because Luis set it up for macOS.  I set up appveyor to build Cygwin/64 and MinGW/msys2 on Windows.

**Comment by jim-easterbrook** [comment]
Robin, your patch fixes the SWIG problem, as expected, and appears to work correctly.

That's a very generous offer to use your MacMini. Once I've understood the MacOS build process I would set up a GitHub Action to build the MacOS wheels, as I've done for Linux and Windows.

Or I could just wait until a MacOS user wants to use python-exiv2 and then work with them to set up the build process.

**Comment by clanmills** [comment]
Remind me early next year to look at your code and I'll work with you on that.  I have also been very frustrated by the python wrappers.  I have a full load of other commitments for the rest of 2021.  You're welcome to come to Camberley for lunch in January and we'll fix this together.  robin@clanmills.com

As my patch passes the test suite.  I think Team Exiv2 will accept it into `main`.

Another possibility is that there's a define when SWIG is running, so you could hide `static constipation` from SWIG.  Something like:

```
#ifndef SWIG_RUNNING
        static constexpr auto familyName_ = "Iptc";
#endif
```

**Comment by jim-easterbrook** [comment]
That's probably a better solution. SWIG already defines `SWIG` for that purpose.
http://www.swig.org/Doc4.0/Preprocessor.html#Preprocessor_condition_compilation

**Comment by clanmills** [comment]
That's the way to go.  Submit a PR to main. I'm sure it will be accepted.

I have never submitted anything into `main`.  That's the hand-shake with Team Exiv2.  I maintain 0.27-maintenance (with lots of help from the gang) and never touch `main` (and/or `old-master`).

**Comment by kevinbackhouse** [comment]
@jim-easterbrook: The 0.27-nightly workflow is run manually, so maybe it was run incorrectly last time. I have just triggered it again, so maybe that will fix it. Are the artifacts for [v0.27.5-RC3](https://github.com/Exiv2/exiv2/releases/tag/v0.27.5-RC3) ok?

**Comment by jim-easterbrook** [comment]
The RC3 build is as I would have expected - still on c++98 and using auto_ptr. I've just tried the new 0.27-nightly and it's got the "static constexpr auto" from v1.0.0. It's just occurred to me that maybe the problem is I'm downloading the source code tar.gz, not one of the builds. (I can't use the Linux build as it uses a too modern version of glibc for my old openSUSE main machine.)

The 0.27-nightly Linux build has the expected c++98 header files, so it's just the "source code" archive that's wrong, if anything is. Maybe this is just user error (or user misunderstanding) on my part.

**Comment by jim-easterbrook** [comment]
Thank you @clanmills, but I think you may need to temper your enthusiasm a little. Don't rewrite the CLI program!

There may well be nasty little things like memory leaks waiting to trip me up - the project's still at an early stage and hasn't been rigorously tested. (If it works in my application I tend to assume that's good enough - rather slapdash I know.) I may still make some API changes as new ideas occur to me.

SWIG is probably the most powerful tool for making wrappers for a variety of languages. I'm happy to help anyone who wants to do wrappers for their preferred language.

**Comment by clanmills** [comment]
I attended PyCon2010 in Atlanta, Georgia.  On the Saturday morning, I attended a presentation by Dave Beazley _(of SWIG fame)_ talking about the Python Global Lock _(GIL)_.  The audience laughed a lot, however I wasn't listening because I was working on my slides having won a lottery to give a "lightning" presentation about Exiv2 and Python.  5 minutes of fun:  http://clanmills.com/2010/PyCon/RobinPyCon2010.mov Enjoy!

I'm not offering to rewrite the exiv2 command-line program.  However you've demonstrated that SWIG could make this possible and simplify the Exiv2 test harness.
