### ISSUE TITLE
Using exiv2.exe on msvc and mingw with greek letters on path

### ISSUE THREAD

**Issue by Sparsh-Bansal** [Exiv2/exiv2#1996]
##### **Describe the bug**
exiv2 can't read exif/meta information from filename having Chinese/Greek characters in it .
Command: exiv2 .\Εκκρεμότητες\VB5_4591.jpg
It says: Failed to open the file 
Also on using pyexiv2 python wrapper for exiv2, Used different encodings like utf-8, GBK, ISO-8859-1, but still the same error -> Failed to open the data source: No such file or directory (errno = 2)

Example of such words -> Βάπτιση, Εκκρεμότητες, Κάλια Μανινάκη

**Comment by kmilos** [comment]
In order to expect any assistance, please also provide more details about your environment: OS, output of `exiv2 -vV`, where you got the exiv2 binary, or how you built it yourself...

**Comment by Sparsh-Bansal** [comment]
I just downloaded the exiv2 (exiv2-0.27.4-2019msvc64) binary for windows from [here](https://exiv2.org/download.html) 
Output of exiv2 -vV:
```exiv2 0.27.4
exiv2=0.27.4
platform=windows
compiler=MSVC
bits=64
dll=1
debug=0
cplusplus=201402
version=13.28 (2019/x64)
date=Jun 15 2021
time=15:10:10
processpath=D:\exiv2-0.27.4-2019msvc64\exiv2-0.27.4-2019msvc64\bin
package_name=exiv2
curl=0
executable=D:\exiv2-0.27.4-2019msvc64\exiv2-0.27.4-2019msvc64\bin\exiv2.exe
library=C:\WINDOWS\SYSTEM32\ntdll.dll
library=C:\WINDOWS\System32\KERNEL32.DLL
library=C:\WINDOWS\System32\KERNELBASE.dll
library=C:\WINDOWS\System32\ucrtbase.dll
library=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
library=C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
library=C:\WINDOWS\SYSTEM32\MSVCP140.dll
library=D:\exiv2-0.27.4-2019msvc64\exiv2-0.27.4-2019msvc64\bin\exiv2.dll
library=C:\WINDOWS\System32\PSAPI.DLL
library=C:\WINDOWS\System32\WS2_32.dll
library=C:\WINDOWS\System32\RPCRT4.dll
library=C:\WINDOWS\System32\SHELL32.dll
library=C:\WINDOWS\System32\msvcp_win.dll
library=C:\WINDOWS\System32\USER32.dll
library=C:\WINDOWS\System32\win32u.dll
library=C:\WINDOWS\System32\GDI32.dll
library=C:\WINDOWS\System32\gdi32full.dll
library=C:\WINDOWS\System32\IMM32.DLL
have_inttypes=0
have_libintl=0
have_lensdata=1
have_iconv=0
have_memory=1
have_lstat=0
have_regex=0
have_regex_h=0
have_stdbool=1
have_stdint=1
have_stdlib=0
have_strlib=0
have_strerror_r=0
have_strings_h=0
have_mmap=0
have_munmap=0
have_sys_stat=1
have_unistd_h=0
have_sys_mman=0
have_libz=1
have_xmptoolkit=1
adobe_xmpsdk=0
have_bool=0
have_strings=0
have_sys_types=1
have_unistd=0
have_unicode_path=0
enable_bmff=0
enable_video=0
enable_webready=0
enable_nls=0
use_curl=0
use_ssh=0
config_path=C:\Users\spars\exiv2.ini
xmlns=DICOM:http://ns.adobe.com/DICOM/
xmlns=GPano:http://ns.google.com/photos/1.0/panorama/
xmlns=Iptc4xmpCore:http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/
xmlns=Iptc4xmpExt:http://iptc.org/std/Iptc4xmpExt/2008-02-29/
xmlns=MP:http://ns.microsoft.com/photo/1.2/
xmlns=MPRI:http://ns.microsoft.com/photo/1.2/t/RegionInfo#
xmlns=MPReg:http://ns.microsoft.com/photo/1.2/t/Region#
xmlns=MicrosoftPhoto:http://ns.microsoft.com/photo/1.0/
xmlns=acdsee:http://ns.acdsee.com/iptc/1.0/
xmlns=album:http://ns.adobe.com/album/1.0/
xmlns=asf:http://ns.adobe.com/asf/1.0/
xmlns=audio:http://www.audio/
xmlns=aux:http://ns.adobe.com/exif/1.0/aux/
xmlns=bmsp:http://ns.adobe.com/StockPhoto/1.0/
xmlns=creatorAtom:http://ns.adobe.com/creatorAtom/1.0/
xmlns=crs:http://ns.adobe.com/camera-raw-settings/1.0/
xmlns=crss:http://ns.adobe.com/camera-raw-saved-settings/1.0/
xmlns=dc:http://purl.org/dc/elements/1.1/
xmlns=dcterms:http://purl.org/dc/terms/
xmlns=digiKam:http://www.digikam.org/ns/1.0/
xmlns=dwc:http://rs.tdwg.org/dwc/index.htm
xmlns=exif:http://ns.adobe.com/exif/1.0/
xmlns=exifEX:http://cipa.jp/exif/1.0/
xmlns=expressionmedia:http://ns.microsoft.com/expressionmedia/1.0/
xmlns=iX:http://ns.adobe.com/iX/1.0/
xmlns=jp2k:http://ns.adobe.com/jp2k/1.0/
xmlns=jpeg:http://ns.adobe.com/jpeg/1.0/
xmlns=kipi:http://www.digikam.org/ns/kipi/1.0/
xmlns=lr:http://ns.adobe.com/lightroom/1.0/
xmlns=mediapro:http://ns.iview-multimedia.com/mediapro/1.0/
xmlns=mwg-kw:http://www.metadataworkinggroup.com/schemas/keywords/
xmlns=mwg-rs:http://www.metadataworkinggroup.com/schemas/regions/
xmlns=pdf:http://ns.adobe.com/pdf/1.3/
xmlns=pdfaExtension:http://www.aiim.org/pdfa/ns/extension/
xmlns=pdfaField:http://www.aiim.org/pdfa/ns/field#
xmlns=pdfaProperty:http://www.aiim.org/pdfa/ns/property#
xmlns=pdfaSchema:http://www.aiim.org/pdfa/ns/schema#
xmlns=pdfaType:http://www.aiim.org/pdfa/ns/type#
xmlns=pdfaid:http://www.aiim.org/pdfa/ns/id/
xmlns=pdfx:http://ns.adobe.com/pdfx/1.3/
xmlns=pdfxid:http://www.npes.org/pdfx/ns/id/
xmlns=photoshop:http://ns.adobe.com/photoshop/1.0/
xmlns=plus:http://ns.useplus.org/ldf/xmp/1.0/
xmlns=png:http://ns.adobe.com/png/1.0/
xmlns=rdf:http://www.w3.org/1999/02/22-rdf-syntax-ns#
xmlns=stArea:http://ns.adobe.com/xmp/sType/Area#
xmlns=stDim:http://ns.adobe.com/xap/1.0/sType/Dimensions#
xmlns=stEvt:http://ns.adobe.com/xap/1.0/sType/ResourceEvent#
xmlns=stFnt:http://ns.adobe.com/xap/1.0/sType/Font#
xmlns=stJob:http://ns.adobe.com/xap/1.0/sType/Job#
xmlns=stMfs:http://ns.adobe.com/xap/1.0/sType/ManifestItem#
xmlns=stRef:http://ns.adobe.com/xap/1.0/sType/ResourceRef#
xmlns=stVer:http://ns.adobe.com/xap/1.0/sType/Version#
xmlns=tiff:http://ns.adobe.com/tiff/1.0/
xmlns=video:http://www.video/
xmlns=wav:http://ns.adobe.com/xmp/wav/1.0/
xmlns=xml:http://www.w3.org/XML/1998/namespace
xmlns=xmp:http://ns.adobe.com/xap/1.0/
xmlns=xmpBJ:http://ns.adobe.com/xap/1.0/bj/
xmlns=xmpDM:http://ns.adobe.com/xmp/1.0/DynamicMedia/
xmlns=xmpG:http://ns.adobe.com/xap/1.0/g/
xmlns=xmpGImg:http://ns.adobe.com/xap/1.0/g/img/
xmlns=xmpMM:http://ns.adobe.com/xap/1.0/mm/
xmlns=xmpNote:http://ns.adobe.com/xmp/note/
xmlns=xmpRights:http://ns.adobe.com/xap/1.0/rights/
xmlns=xmpT:http://ns.adobe.com/xap/1.0/t/
xmlns=xmpTPg:http://ns.adobe.com/xap/1.0/t/pg/
xmlns=xmpidq:http://ns.adobe.com/xmp/Identifier/qual/1.0/```

**Comment by clanmills** [comment]
I think there are two issues which may be causing this:

1.  This build has not set -DEXIV2_ENABLE_UNICODE=ON
I know this from the output `have_unicode_path=0` (and because I did the build)

2. The command-line program exiv2 isn't linked to use wmain() and I think you need that to use UNICODE paths.

The sample program sample/exifprint.cpp was modified to use wmain() and other MSVC wide support (tchar, etc).  Please build exiv2 with -DEXIV2_ENABLE_UNICODE=1 and see if bin/exifprint.exe can read the metadata in your image when using a Greek path.

_**Background Explanation**_

The exiv2 library is passed the path and opens it with good old `fopen()`.  When ENABLE_UNICODE is set and you will be using `_wfopen`.

I'm a native english speaker and don't understand Greek.  Write a simple version of `wc` to count the bytes in a file using `fopen()`.  When you know how to get that to behave correctly with your Greek path, you should link/build exiv2 in a similar manner.

```bash
671 rmills@rmillsm1:~/temp $ cat wc.cpp
#include <stdio.h>

int main(int argc, const char* argv[])
{
	int result = 1;
	if ( argc != 2 ) {
	    printf("Syntax: %s path\n",argv[0]);
	    result = 1;
	} else {
	    FILE* f = fopen (argv[1],"rb") ;
	    if ( !f) {
	       fprintf(stderr,"Unable to open %s\n",argv[1]);
	       result = 2 ;
	    } else {
			int wc = 0 ;
			while ( fgetc(f) != EOF ) wc++ ;
			printf("%d\n",wc);
		}
	}
	return result ;
}
672 rmills@rmillsm1:~/temp $ make wc
c++     wc.cpp   -o wc
673 rmills@rmillsm1:~/temp $ ls -l wc.cpp
-rw-r--r--@ 1 rmills  staff  411 12 Nov 16:13 wc.cpp
674 rmills@rmillsm1:~/temp $ wc wc.cpp
411
675 rmills@rmillsm1:~/temp $ 
```

**Comment by clanmills** [comment]
I am 100% certain about this.  I attach a WIN_UNICODE build of v0.27.5.  The build of exifprint.exe understands the Greek path.  The build of exiv2.exe does not.  This is because exiv2.cpp has not had the treatment given to exifprint.cpp to work with msvc/unicode support (tchar etc). 

```cmd
C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin>exiv2 -vV | grep uni
have_unistd_h=0
have_unistd=0
have_unicode_path=1

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin>mkdir Εκκρεμότητες

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin>cd Εκκρεμότητες

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin\Εκκρεμότητες>curl -LO http://clanmills.com/Stonehenge.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6597k  100 6597k    0     0  2650k      0  0:00:02  0:00:02 --:--:-- 2657k

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin\Εκκρεμότητες>..\exiv2.exe -g original/i Stonehenge.jpg
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
Exif.Photo.SubSecTimeOriginal                Ascii       3  00

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin\Εκκρεμότητες>cd ..

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin>exiv2.exe -g original/i Εκκρεμότητες\Stonehenge.jpg
????e╡?t?te?\Stonehenge.jpg: Failed to open the file

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin>exifprint Εκκρεμότητες\Stonehenge.jpg
Exif.Image.Make                              0x010f Ascii      18  NIKON CORPORATION
Exif.Image.Model                             0x0110 Ascii      12  NIKON D5300
...
Exif.Thumbnail.YCbCrPositioning              0x0213 Short       1  1

C:\Users\rmills\issue_1996\exiv2-0.27.5-2019msvc64\bin>
```
[exiv2-0.27.5-2019msvc64-2021-11-13_07:02:00.zip](https://github.com/Exiv2/exiv2/files/7531599/exiv2-0.27.5-2019msvc64-2021-11-13_07.02.00.zip)

**Comment by kmilos** [comment]
We should probably build w/ unicode/wide char support by default on Windows.

**Comment by clanmills** [comment]
I agree, @kmilos

I was _wrongly_ of the believe that when `#define EXV_UNICODE_PATH` was set at compile time (by the CMake option `-DEXIV2_ENABLE_WIN_UNICODE`), the library was totally wchar and char was not available.  I discovered when documenting this in my book that the API is augmented with the wchar variants for `ImageFactory::open` et al.

About 2015, I modified samples/exifprint.cpp to use the wchar interface when EXV_UNICODE_PATH is used.  I added that in response to a bug raised by a Canadian user.  I think that may have been something similar to this Greek issue.

I didn't upgrade exiv2.cpp at that time because I didn't want to distribute builds with exclusive wchar API because I _wrongly_ thought the `UNICODE=1` and `UNICODE=0` libraries were incompatible.

You are correct.  We should always set EXV_UNICODE_PATH when building on MSVC.

The other part of the ugly twins (unicode and wmain) is that we should:

1.  port the `tchar` magic from samples/exifprint.cpp into exiv2.cpp and every sample applications
2. add appropriate tests to the test suite
3. review/revise README.md concerning EXV_UNICODE_PATH

I know @postscript-dev will be interested in this matter.  However he may not have time to work on this.

@Sparsh-Bansal are you willing to work on porting the `tchar` magic into exiv2.cpp and other samples?

**Comment by clanmills** [comment]
I've updated the release script svn://dev.exiv2.org/svn/team/contrib/buildserver/build.sh release as follows:

1. Add option `--unicode` to set `-DEXIV2_ENABLE_WIN_UNICODE=1`
2. Hardwire `-DEXV_UNICODE_PATH=1` for MSVC builds
3. Hardwire `-DEXV_DYNAMIC_RUN_TIME=1` for MSVC builds (evades an expat link issue with static builds)

Please note that this is only used by the release scripts.  Changes have not been made to CMakeLists.txt and/or README.md

Setting `-DEXIV2_ENABLE_WIN_UNICODE=1` changes the build of the library and the sample `exifprint`.  In this issue, the user's issue concerns the exiv2 command-line program which will require exiv2.cpp to be modified.  exiv2.cpp must use `tchar` and other msvc/unicode magic similar to that found in samples/exifprint.cpp

**Comment by postscript-dev** [comment]
I have thought a little about this recently.

It has concerned me that we aren't running the CI on the Unicode versions of the functions. I don't know of any problems but I think that it is worth testing to make sure that everything works. One of the limiting factors to this has been that the exiv2 sample program, which we use to test, did not support Unicode. Once the exiv2 sample conversion has taken place, I think that it would be helpful to run the CI on both the Unicode and non-Unicode versions on Windows. Any tests which makes use of the Unicode features, could be skipped when running the non-Unicode Windows version. Both `exiv2 --verbose --version --grep unicode` and `exiv2 --verbose --version --grep platform` could help create Python variables which can be used to skip tests as appropriate.

Perhaps the website API docs could be generated from the Windows Unicode build. Currently only the non-Unicode functions are displayed on <nolink>exiv2.org</nolink> and I think that it would be useful to include the Unicode versions too.

Another problem that occurred to me this morning is that the lens configuration file doesn't supports Unicode. I haven't looked extensively at it, but I think that there are two issues. First that the path could contain Unicode characters and second that the contents of the file could. The path can be fixed by using `_wgetcwd()` but the `INIReader` class doesn't support Unicode. Unless someone want to fix this, I could add something to the manpage to document the current limitations.

I realise that this a substantial list of problems and I am sorry that I don't have time to contribute code to solve them. I had hoped to look at some of this, sometime next year.

**Comment by clanmills** [comment]
@postscript-dev Thank for your useful observations.  Please don't apologise for finding issues which have been in the code for 15+ years.  I'm sure you already know that `#define EXV_UNICODE_PATH` only deals with UNICODE in path names and has nothing to do with any metadata character handling.

I updated build.sh today, and believe doxygen might generate web API documents for both char and wchar APIs for `Exiv2::ImageFactory::open()` et al.  However the docs are generated by doxygen running on macOS (or Linux).  It's possible that EXV_UNICODE_PATH hides those APIs from doxygen!  It would be simpler and better to add a new section to README.md to discuss UNICODE paths **AND** _(as recommended by @kmilos)_ build every MSVC library with both char and wchar support.

It's straightforward to add a test that creates a directory with a Greek name, copy an image and test exifprint.exe works correctly.  The test suite has machinery to sniff the output from `$ exiv2 -vV` and skip irrelevant tests.  For example, this is used to skip BMFF tests when the library has not been build with `-DEXIV2_ENABLE_BMFF`

The reason I modified samples/exifprint.cpp was because I had no way to test UNICODE at that time.  As you can see from the transcript above in which I use `mkdir Εκκρεμότητες`, I was able to test the UNICODE build today without modifying anything.  If I had known that the UNICODE feature augments the API, I would have modified all the samples when I modified samples/exifprint.cpp to respect UNICODE.

I added the INIReader about 5 years ago.  It's a "bought in class".  I cut'n'pasted it from another project and put it into the Exiv2 namespace.  https://github.com/benhoyt/inih  INI-Reader was added in a morning and has delivered happiness to many.  I suspect it can be "beefed up" to use std::wstring.  There is an existing issue about servicing that code.  #1811.

**Comment by kmilos** [comment]
> build every MSVC library with both char and wchar support

Note that I mentioned Windows, not just MSVC. This is a platform thing, not a compiler thing ;)

**Comment by clanmills** [comment]
Ah.  I didn't realise that, @kmilos.  It's Windows-wide and not only MSVC.  Generating the on-line docs by running doxygen on MinGW/msys2 sounds good.  A section about UNICODE_PATH should be added to README.md.

**Comment by kmilos** [comment]
Also note that we've been building the [exiv2 MINGW-packages w/ unicode](https://github.com/msys2/MINGW-packages/blob/00cce3637f4abd66ae6119e5059c9df52e2f380d/mingw-w64-exiv2/PKGBUILD#L51) support for a while now...

**Comment by clanmills** [comment]
I've updated the release script build.sh to use UNICODE_PATH support on MinGW and Cygwin.

```bash
rmills@rmillsmm-w10 MINGW64 ~/temp/exiv2-0.27.5-MinGW64
$ ls -l bin/Eκκρεμότητες/Stonehenge.jpg
-rw-r--r-- 1 rmills rmills 6755901 Nov 14 19:27 bin/Eκκρεμότητες/Stonehenge.jpg

rmills@rmillsmm-w10 MINGW64 ~/temp/exiv2-0.27.5-MinGW64
$ ./exifprint.exe bin/Eκκρεμότητες/Stonehenge.jpg
Exif.Image.Make                              0x010f Ascii      18  NIKON CORPORATION
...
```

However, there is an issue with samples/exifprint.cpp because of this code in samples/exifprint.cpp causing it to ignore the UNICODE_PATH.  So the library has been correctly build with UNICODE support.  The executable bin/exifprint.exe uses the ascii API and fails on Greek paths.

```
// https://github.com/Exiv2/exiv2/issues/468
#if defined(EXV_UNICODE_PATH) && defined(__MINGW__)
#undef  EXV_UNICODE_PATH
#endif
```

I edited out that code and compiled it (as documented in ReadMe.txt)

```
349 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.5-MinGW64 $ g++ -std=c++98 samples/exifprint.cpp -I/usr/local/include -L/usr/local/lib -lexiv2 -o exifprint
w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
350 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.5-MinGW64 $
```

The fix for this is to use the g++ option `-municode`.  So build thus:
```
350 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.5-MinGW64 $ g++ -std=c++98 samples/exifprint.cpp -municode -I/usr/local/include -L/usr/local/lib -lexiv2 -o exifprint
351 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.5-MinGW64 $ ./exifprint.exe --version | grep unicode
have_unicode_path=1
352 MSYS rmills@rmillsmm-w10:~/temp/exiv2-0.27.5-MinGW64 $
```

I can fix this in build.sh of course by setting `-DCMAKE_CXX_FLAGS=-municode` in build.sh.

I don't think fixing this in ./build.sh is a satisfactory solution because I am the only person who uses the script. 

We should do some maintenance on CMakeLists.txt to build both the library and our samples with UNICODE support on Windows platforms.

1.  Set EXV_UNICODE_PATH for all Windows builds (msvc, mingw, cygwin)
2. Remove the unicode blocker in samples/exifprint.cpp and set -municode when compiling samples/exifprint.cpp
3. Upgrade every sample to use the UNICODE_PATH magic from exifprint.cpp (below)
4. Document UNICODE_PATH in ReadMe.txt

I'm not going to undertake this project as I have retired.  I'm happy to help/mentor a volunteer.

```cpp
#ifdef  EXV_UNICODE_PATH
#define _tchar      wchar_t
#define _tstrcmp    wcscmp
#define _t(s)       L##s
#define _tcout      wcout
#define _tmain      wmain
#else
#define _tchar      char
#define _tstrcmp    strcmp
#define _t(s)       s
#define _tcout      cout
#define _tmain      main
#endif
```

**Comment by clanmills** [comment]
Good news about Cygwin.  I believe cygwin `fopen()` supports UTF-8 in the path.  So the "vanilla" build of exiv2 (and the samples) supports Greek characters in the path:

```
306 rmills@rmillsmm-w10:/tmp $ exiv2 -vVg unicode
exiv2 0.27.2
have_unicode_path=0
307 rmills@rmillsmm-w10:/tmp $ exiv2 -g original/i Εκκρεμότητες/Stonehenge.jpg
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
Exif.Photo.SubSecTimeOriginal                Ascii       3  00
308 rmills@rmillsmm-w10:/tmp $
```

_**Discussion**_

I was surprised yesterday when the Cygwin build didn't appear from the build server yesterday.  It failed as follows:

```
/home/rmills/gnu/github/exiv2/buildserver/src/basicio.cpp: In member function 'int Exiv2::FileIo::Impl::switchMode(Exiv2::FileIo::Impl::OpMode)':
/home/rmills/gnu/github/exiv2/buildserver/src/basicio.cpp:226:21: error: '::_wfopen' has not been declared; did you mean 'fopen'?
  226 |             fp_ = ::_wfopen(wpath_.c_str(), s2ws(openMode_).c_str());
      |                     ^~~~~~~
      |                     fopen
 ```
 
` _wfopen()` is not supported on Cygwin.


I will modify build.sh to ignore the UNICODE_PATH setting.

**Comment by kmilos** [comment]
[Cygwin/MSYS are not "native Windows"](https://en.wikipedia.org/wiki/MinGW#Comparison_with_Cygwin), they're POSIX (Unix) virtual emulation environments. Only MinGW is Windows.

**Comment by clanmills** [comment]
Yes.  You are correct.  Cygwin in POSIX and `fopen()` provides a user experience which is similar to macOS.  So Greek is handled correctly.  (_under the hood_, the cygwin DLL probably converts UTF-8 to UTF-16 and uses `_fwopen()`). 

```bash
521 rmills@rmillsmm-local:~/temp $ uname -a
Darwin rmillsmm-local.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64 x86_64 i386 Macmini6,2 Darwin
522 rmills@rmillsmm-local:~/temp $ mkdir Εκκρεμότητες
523 rmills@rmillsmm-local:~/temp $ cd Εκκρεμότητες
524 rmills@rmillsmm-local:~/temp/Εκκρεμότητες $ curl -O http://clanmills.com/Stonehenge.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6597k  100 6597k    0     0   693k      0  0:00:09  0:00:09 --:--:-- 1258k
525 rmills@rmillsmm-local:~/temp/Εκκρεμότητες $ cd ..
526 rmills@rmillsmm-local:~/temp $ exiv2 -g original/i Εκκρεμότητες/Stonehenge.jpg 
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
Exif.Photo.SubSecTimeOriginal                Ascii       3  00
527 rmills@rmillsmm-local:~/temp $ exiv2 -vVg unicode
exiv2 0.27.5.3
have_unicode_path=0
528 rmills@rmillsmm-local:~/temp $ 
```

MinGW/sys2 is Windows and requires _wfopen().

I'm not sure what you mean by MSYS.  For sure, we dumped support for the original msys (msys/1.0) about 5 years ago.

**Comment by kmilos** [comment]
> I'm not sure what you mean by MSYS

Was just mentioning for generality here. MSYS is derived from Cygwin, and is just another environment to provide the Unix-like experience and tools. [It is still an available and crucial environment in the MSYS2 installation, which all the native MINGW environments have to lean on for the Unix-y build tools...](https://www.msys2.org/docs/environments/)

**Comment by clanmills** [comment]
This isn't a localisation issue.  I consider localisation to be converting strings in the exiv2 command-line utility into other natural languages.  I prefer to keep the label "bug" for errors in the code.

I believe Greek will work on Posix platforms (linux, macOS and Cygwin), so it's an enhancement to the path handling on Windows (msvc and MinGW/msys2).  

This is a build issue.  We should also add a test and discuss this in the  documentation.  https://github.com/Exiv2/exiv2/issues/1996#issuecomment-968358977

**Comment by kmilos** [comment]
Robin, I never said this is a localisation issue, but it is indeed an internationalisation issue. There is a distinct difference between the two terms, and why I created separate L10n and i18n labels.

**Comment by clanmills** [comment]
You're right.  I mis-read that.  It is indeed an i18n and we agree that it's not an L10n (NLS) issue.

In my mind, I've always thought of i18n as being exclusively NLS.  Wrong way round.  L10n is NLS.  i18n is L10n+lots of other stuff such as this path issue.

**Comment by neheb** [comment]
Windows 10 has a registry setting that makes fopen calls used uft8 by default. It might work here as well: https://superuser.com/questions/1033088/is-it-possible-to-set-locale-of-a-windows-application-to-utf-8

**Comment by kmilos** [comment]
Possibly, but you'd need to link against the new UCRT instead of legacy MSVCRT for this to work. We don't currently (apart from the ucrt64 package in the Msys2 repo).

**Comment by neheb** [comment]
The registry setting also works with the legacy MSVC runtime last time I tested. But for platforms before Windows 10 or old Windows 10 builds, UCRT is needed.

If I had to guess,  @Sparsh-Bansal is talking about binaries created with MSVC. No idea how to migrate to UCRT in visual studio.

**Comment by kmilos** [comment]
> No idea how to migrate to UCRT in visual studio.

Actually, should be the default in VS since 2017 I think.

**Comment by neheb** [comment]
oh OK so just a setlocale call is needed.

**Comment by clanmills** [comment]
Uh?  Amazing!  What's the fix?

**Comment by clanmills** [comment]
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170

_**UTF-8 Support**_

_Starting in Windows 10 version 1803 (10.0.17134.0), the Universal C Runtime supports using a UTF-8 code page. This means that char strings passed to C runtime functions will expect strings in the UTF-8 encoding. To enable UTF-8 mode, use ".UTF8" as the code page when using setlocale. For example, setlocale(LC_ALL, ".UTF8") will use the current default Windows ANSI code page (ACP) for the locale and UTF-8 for the code page._

_The string to specify UTF-8 mode is:_
_* case-insensitive_
_* the hyphen (-) is optional_
_* It must be in the code page part of the locale name, so must have a leading period (.) as in these examples: "en_US.UTF8" or ".utf8"_

**Comment by clanmills** [comment]
This works on macOS and not on Windows/MSVC.  I have Windows 10/1903 (installed 2021-03-27).  Perhaps I need to upgrade Visual Studio.

```
C:\temp>dir Εκκρεμότητες\wc.cpp
 Volume in drive C has no label.
 Volume Serial Number is 0899-EF40
 Directory of C:\temp\Εκκρεμότητες
2022-01-08  15:36               676 wc.cpp
               1 File(s)            676 bytes
               0 Dir(s)  13,150,990,336 bytes free
C:\temp>wc Εκκρεμότητες\wc.cpp
Unable to open ????e
C:\temp>
```

```cpp
#include <stdio.h>

#ifdef _MSC_VER
#include <locale.h>
#include <direct.h>
#else
#include <sys/stat.h>
#endif

int main(int argc, const char* argv[])
{
#ifdef _MSC_VER
    setlocale(LC_ALL, ".UTF8");
    _mkdir("??");
#else 
    mkdir("??",0x777);
#endif

    int result = 0;
    if ( argc != 2 ) {
        printf("Syntax: %s path\n",argv[0]);
        result = 1;
    } else {
        FILE* f = fopen (argv[1],"rb") ;
        if ( !f) {
           fprintf(stderr,"Unable to open %s\n",argv[1]);
           result = 2 ;
        } else {
            int wc = 0 ;
            while ( fgetc(f) != EOF ) wc++ ;
            printf("%d\n",wc);
        }
    }
    return result ;
}
```

**Comment by kmilos** [comment]
Indeed, this is already done in `src/basicio.cpp`, so still not sure where exactly is the problem, it seems we're just missing a bit of plumbing somewhere...

**Comment by neheb** [comment]
Since this is C++17 now, I looked at https://github.com/jarro2783/cxxopts . It seems to use ICU though...

**Comment by piponazo** [comment]
I think I know how to deal with this!

```
F:\projects\wmain\build\bin>utf8_echo.exe f:\Εκκρεμότητες\Stonehenge.heic
ANSI Code Page = 1252
OEM  Code Page = 437
Old Console CP = 437
New Console CP = 65001
argv[0] = "utf8_echo.exe"
argv[1] = "f:\Εκκρεμότητες\Stonehenge.heic"
```

This project seems to have the answer to properly get UTF-8 encoded `argv` without messing with the argument parsing part. I'll try to bring this into exiv2.

**Comment by clanmills** [comment]
Well Done, Luis.  You are a wizard.  Take the rest of the day off.

**Comment by piponazo** [comment]
@Sparsh-Bansal I just merged a change that should fix this bug. Tomorrow you should be able to download the automatically generated nightly build from:
https://github.com/Exiv2/exiv2/releases

Please let us know if it fixes your issue.
