### ISSUE TITLE
Contributor documentation for running tests does not work

### ISSUE THREAD

**Issue by mallman** [Exiv2/exiv2#2082]
Hello.

I am working on a PR and following the contributor guidelines in [CONTRIBUTING.md](https://github.com/Exiv2/exiv2/blob/4ae42b107dca8daf2a1877d3c3e6d4f5c22ab322/CONTRIBUTING.md). At step 7 of the instructions for submitting a PR, the contributor is instructed to run the tests as follows

```
 $ make tests         # Integration tests
 $./bin/unit_tests    # Unit tests
```

However, I'm unable to get either of these to work. What I do see is

```
[msa@hoodoo build]$ make tests
make: *** No rule to make target `tests'.  Stop.
[msa@hoodoo build]$ ls bin/
exiv2
[msa@hoodoo build]$ 
```

I'd like to exercise my due diligence in running the relevant tests before submitting a PR, but I don't know how. Does the documentation need to be updated? Am I doing something wrong?

**Comment by clanmills** [comment]
@mallman Michael.  That documentation concerning test is out of date.  Quite recently, we upgraded our test environment to use `ctest` and this is documented in `README.md`.

We'll need a PR to fix `CONTRIBUTING.md`.  Rather than getting into a documentation _race condition_, CONTRIBUTING.md should say something generic such as:

> _Please see **4 Test Suite** in [README.md](README.md) for details._

----
The basic command to builds and test are:

```bash
$ cmake ....
$ cmake --build .
$ ctest
```

Although I wrote `README.md` and recently updated it concerning `ctest`, the details are already slipping from memory _(which is why it's documented)_.  As a summary, it's something like:

```bash
$ ctest                       # run all tests and print summary
$ ctest -N                    # dry-run (No execution) this will reveal test names (bashTests, bugfixTests etc)
$ ctest --help                # list ctest options
$ ctest -R version            # will run a single test
$ ctest --verbose -R version  # run a test and display full transcript
```

**Comment by mallman** [comment]
Hi @clanmills. I got the tests to run. The missing magic was

```
-DEXIV2_BUILD_SAMPLES=ON
-DEXIV2_BUILD_UNIT_TESTS=ON
```

🤦

**Comment by piponazo** [comment]
Please note that I am making some changes at the moment that are related to how to run the tests at #2080.

Basically we want to be able to run more tests without needing to enable the sample applications (`-DEXIV2_BUILD_SAMPLES=ON`).

**Comment by clanmills** [comment]
I'm going to re-open this issue.  @piponazo has made the build changes concerning the sample programs #2080.  The documents README.md and CONTRIBUTING.md should be reviewed and corrected.

**Comment by clanmills** [comment]
Luis has stepped into this one.  Thanks.
