### ISSUE TITLE
https://pre-release.exiv2.org/ offline?

### ISSUE THREAD

**Issue by paolobenve** [Exiv2/exiv2#2095]
I get:

```
404
There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up
GitHub Pages for your repository, organization, or user account.
```

**Comment by nehaljwani** [comment]
Thank you for reporting.

Fixed via https://github.com/Exiv2/team/commit/7933b345b9c36e4d26d2ea17af8b0066c5d16c8b .

**Comment by paolobenve** [comment]
I'd say that `https://pre-release.exiv2.org/` is now identical to `https://exiv2.org/`, is it ok?

**Comment by nehaljwani** [comment]
The pre-release web pages have:

- The 'Pre-Release' slanting text in background on each page, and
- The download page on pre-release points to the last release candidate

Isn't the rest supposed to be identical?

**Comment by clanmills** [comment]
0.27.5 RC3 is Release Candidate 3 for v0.27.5.  It's older than v0.27.5.  We call it a "candidate" because it will morph into v0.27.5 if no bugs are reported.

Our number system is conventional and documented here:  https://github.com/Exiv2/exiv2/security/policy

**Comment by clanmills** [comment]
There is a little error on https://pre-release.exiv2.org.  It is correctly labelled "Pre-Release".  The footer says "Exiv2 v0.27.5.3" and it should say "Exiv2 v0.27.5 RC3". 

We are in a transition and moving the web-site to GitHub.  I think Nehal had to regenerate the site yesterday because every page is dated: 'Last modified 2022-02-14 01:42 UTC'.  We're also in the transition as Nehal steps into the role of Release Engineer.

I can't think of any reason why you'd want to use pre-release at this time.  These are intended for users to try new releases before we declare them complete and released.  There are no code changes between 0.27.5.3 and 0.27.5.  The only change is the "tweak" (fourth digit) of the revision which at '3' indicates RC3.

**Comment by clanmills** [comment]
Nehal (@nehaljwani).  I've made a zip of the backup of pre-release.exiv2.org on 2021-10-04.  RC3 was created on 2021-10-01 and released on 2021-10-02.  https://clanmills.com/exiv2/pre-release-2021-10-04.zip

Can you could deploy this on pre-release.org.   This is a 417mb download.  It's big because it has copies of every release of Exiv2 going back to 2004.  Let me know when I can delete this from clanmills.com   Thank You Very Much.
