### ISSUE TITLE
Add FreeBSD to CI

### ISSUE THREAD

**Issue by diizzyy** [Exiv2/exiv2#2104]
Hi,

Not sure if this is categorized correctly but it would be appreciated if you could at least add one BSD-distro to CI such as FreeBSD (I know MacOS is kinda BSD-ish though).

I'd also like to thank everyone for their work and effort on exiv2.

Best regards,
Daniel

**Comment by piponazo** [comment]
Hi @diizzyy , you are in the right place. I just added an additional `CI` tag to your issue. 

Would/Could you contribute to add such platform to our CI pipeline? It is not a difficult task, it normally involves touching just 2 files:

```
.github/workflows/nightly_Linux_distributions.yml
ci/install_dependencies.sh
```

**Comment by clanmills** [comment]
@diizzyy Thanks for brining up this matter.

When we shipped 0.27 (December 2018), I installed FreeBSD, NetBSD and Solaris VMs on my MacMini and updated README.md to document my experience.  I did this because @[lantw44](https://github.com/lantw44) reported several build issues on FreeBSD on Exiv2 v0.27.0 RC1.  All were fixed and tested and no further FreeBSD issues have been reported since.

I was 71 last month and am retiring from Exiv2.  I would like to find a volunteer to support any/all of these platforms.  I don't believe there is much effort required and the reward is well .... _you'll have your reward_.

Team Exiv2 is an enthustic team of engineers and I know they will make you very welcome.  As Luis (@piponazo) has said it would be very helpful if you can deal with the CI for FreeBSD.

**Comment by diizzyy** [comment]
Hi,

I tried looking at this and I have no experience with docker and no ability to test anything so I have to pass on this. I can help with whats needed on the FreeBSD side of things (basically pkg install <list of deps)>). Feel free to close the PR if there's no interest.

Best regards,
Daniel

**Comment by piponazo** [comment]
Hi @diizzyy,

Let's leave the issue open, I think it is interesting to add CI support for any system in which exiv2 might be used. If at some point I decide to work on this and I have doubts, I'll ping you 😉

**Comment by neheb** [comment]
@diizzyy I looked into this and saw https://github.com/vmactions/freebsd-vm

Then I saw that it downloads a 1.1GB iso...
