### ISSUE TITLE
Permissive license

### ISSUE THREAD

**Issue by ribtoks** [Exiv2/exiv2#215]
First of all thanks for the excellent library (I've been fixing some bugs as well in v0.25 when it wasn't hosted at GitHub).

Though it is a speculative topic I would like to register this issue because maybe there would be interest from other members of the community in the same thing.

So what I would like to request is either providing exiv2 library as dual-licensed with some permissive license like Apache, MIT or BSD or relicense it to be provided under this license. I've switched to MIT permissive license for [my project](https://github.com/ribtoks/xpiks/) (because of religious conflicts with GPL) and I cannot use exiv2 library anymore, because it's GPLv2.

I believe that this also will make it even more popular and will allow people like me to contribute into it again/too (well, that was the reason to move to GitHub - to get some more visibility for this project).

Thanks

**Comment by clanmills** [comment]
Over the last 10 years, I've put about 10,000 hours of effort into the support and maintenance of Exiv2.  I'm delighted to say that in the last 6 months, a few more volunteers have become actively involved in the maintenance of the code, build systems and test machinery.

The code is published under GPLv2.  I have very little knowledge of software licenses.  I believe changing from GPLv2 to any other license is difficult.

I am sure you know that folks frequently ask request new features (in addition to user help and bug reports).  My usual reaction is to invite the person making the request to undertake the work required to develop the feature, test it, include it in the build system and to maintain it on an on-going basis.  I can't remember anybody accepting such as invitation.  However, I make the same offer to you.  If you believe that the license should (and can) be changed, you are welcome to join the team and undertake the work involved.

**Comment by ribtoks** [comment]
@clanmills Hi Robin. I was asking same thing from Andreas over email a year ago and he was against it. That's why I've put here this "public request" for anybody else to support. If you believe this is not a problem from ownership point of view, I will gladly inspect code for compliance and submit pull request with license change.

**Comment by clanmills** [comment]
Hi Taras  Good to hear from you again.  I hope everything's well with you.  I don't know what's involved in changing the license.  You are welcome to inspect the code.  I feel we'd need professional legal advice.  Perhaps you know someone willing to contribute their time and expertise.

**Comment by clanmills** [comment]
Taras.  I will not accept a PR in which the code prologs state the code is being offered with a  different license.  We need a written legal opinion stating what we need to do.  Please remember that up-to-and-including v0.26, Exiv2 offered a Commercial License and the legal opinion has to consider and respect existing licenses.

**Comment by ribtoks** [comment]
@clanmills Unfortunately I don't know any legals, but I will try to ask around. Thanks!

**Comment by D4N** [comment]
@ribtoks As you seem interested in using exiv2, note that you can use exiv2 in your MIT/BSD licensed project if you use it as a plugin. Since I am not a lawyer, I cannot give you a definitive answer, but judging from the [official docs](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins), you might be able to use exiv2 as long as you just invoke the main exiv2 executable and parse its output. We also have a sample program that outputs everything as json, which might be even better for parsing. However we provide that only as a sample, so your mileage may vary.

Please also make your own research, all the info from me is without any warranty.

Concerning a license change: that is unlikely to happen in the foreseeable future as @clanmills said. We would need a lawyer to figure everything out and probably also contact everyone that ever submitted a patch to exiv2.

Just out of interest, would the situation change if exiv2 was licensed under the LGPL? I am only asking for personal projects, as I do not want to use very permissive licenses, but would not like to prevent open source projects from using my software.

**Comment by ribtoks** [comment]
@D4N Thanks for the advice, but I would better use `exifool` as a plugin. The point was to link it to the code, not to call it as another process.

**Comment by mmatrosov** [comment]
@clanmills 
> Please remember that up-to-and-including v0.26, Exiv2 offered a Commercial License
We purchased the license for version 0.25. Could you please clarify, whether it is applicable for version 0.26?

**Comment by D4N** [comment]
Please note, the following is not legal advice. Consult a lawyer if you
are unsure.

It is applicable for 0.26, but not for anything beyond that, as we have
moved the GPL licensed code to GitHub and developed solely that.

You can use the current code base under the terms of the GPL license,
but not under the terms of the commercial license, as the provider of
the commercial license has no copyright for the commits provided beyond
0.26. Imho you can consider this a fork of the original Exiv2, but
without the option for a commercial license.

(Again, please consult a lawyer, as this is not legal advice)

**Comment by mmatrosov** [comment]
@D4N 

> It is applicable for 0.26

Thanks, this is helpful.

**Comment by clanmills** [comment]
Thanks @D4N for commenting on this.  As will all legal matters, you should seek professional advice.

My understating of your Commercial License is that is valid for v0.26.  The Exiv2 Project on GitHub is licensed under GPLv2.  The Commercial License does _**NOT**_ cover any changes since v0.26 was released in April 2017.

**Comment by mmatrosov** [comment]
> I'd like to stress out, that therefore you can only use everything up to the v0.26 tag, but not the patches from the 0.26 branch nor those from the 0.25 branch, as they were added to the GPL licensed code only.

I downloaded this version: https://github.com/Exiv2/exiv2/releases/tag/v0.26 So I hope this should be fine.

> Nevertheless, please find a way how to include the upcoming GPL licensed releases in your code base

How would we do this? We have a proprietary closed-source software.

**Comment by D4N** [comment]
> I downloaded this version: https://github.com/Exiv2/exiv2/releases/tag/v0.26 So I hope this should be fine.

That should be fine from my point of view.

> How would we do this? We have a proprietary closed-source software.

Afaik you'd have to re-license your program to a GPL compatible license. That's as far as I know the only way.

I know that that's probably not an option for you. However, I'd like to point out, that only because you open sourced your software, doesn't mean that you have to make it publicly available for everyone on GitHub/GitLab/etc. With most FOSS licenses you only have to provide the source code to users who paid for your application (if you sell it).

In the end you have to evaluate for yourself what is the better solution: the security risks of running a vulnerable version of exiv2 or changing the license.

**Comment by emmenlau** [comment]
Dear @clanmills and all,

I know this is an old topic, and also a sensitive one. But its also a topic that has been on my mind since basically 2012 when I missed my chance to buy a license from Andreas.

My use case is a bit specific: We like exiv2 because it gives a helpful abstraction in reading microscopy meta data. Its certainly not essential to our product, and customers would not pay extra for having it. But its nice to have, and I would be willing to invest a bit of money, time or resources into the project (for example we're pretty strong in providing build system help to open source projects).

I understand that most of the work on exiv2 has been contributed by a small amount of people. So I can see that this may not necessarily change a lot in the future. Meaning, relicensing may not necessarily open up more contributions. But what it can do is help in keeping projects alive in the long run. exiv2 seems pretty mature now. Maybe there will be times when contributions focus on fixing the one or other bug, or updating the build system. And this is something that companies have a significant incentive to do.

Basically, I would like to iterate one more time on the question of relicensing exiv2 under a more permissive license. From what I found so far, it seems the relevant points about relicensing an open source project are summarized pretty well in https://opensource.stackexchange.com/questions/33/how-can-a-project-be-relicensed (quoting here):

> As long as you are the only contributor: You can do it, without further problem.
> Otherwise: It is difficult.
> 
> If others contributed to your project, you have to respect their rights. So you can only assume the rights given to you by the open source license. Your options are:
> 1. contact all contributors and ask for their permission
> 2. switch to a compatible license (this means, if your original license is permissive, it might have a lot compatible options, if it is copyleft, the compatible options may be limited)
> 3. remove contributions of others before switching
> 
> As a note: your old version of the software released under the old license can still be used under the terms of the old license. If that license is pretty permissive that may include the relicensing under some other licenses.

So before boing any further, I think the key relevant point is the permission of contributors. Currently there are 66 contributors for exiv2 that have changes in the git history. Its possible that not all these changes are currently still included in the head development branch. But for the sake of simplicity, lets move that question away for later. Of the 66 contributors, roughly 40 have made changes that are below 100 lines changed. I would assume that (in case some of these authors are unreachable) there is at least an option to re-create these changes from scratch with moderate effort. This would certainly not be ideal, but it may be an option in case only a small number of contributors is unreachable.

So if my pre-assumptions are correct, the relevant first question would be the stance of the 26 remaining contributors to the question of relicensing. Im under the impression that the first step boils down to:
 - if any of the 26 core contributors is *against* relicensing, then its unlikely it can move forward (with moderate effort).
 - if all 26 26 core contributors are ok with relicensing, then the effort for the remaining steps may be reasonable. It would remain to legally confirm that the findings from above are correct, and it would remain to contact the remaining contributors and/or re-create their contributions from scratch.

What do others think? Most importantly, are there any core contributors reading along here that can already chip in with their gut feeling towards relicensing, specifically objections towards relicensing?

**Comment by clanmills** [comment]
I am 100% unwilling to get involved with this.  This project will use a lot of my time and I can think of no benefit to me.  I will be 70 next Monday (2020-01-18) and have been wanting to retire from Exiv2 for several years.  I've volunteered to do "one more project" which is scheduled to ship on 2021-05-22.  https://github.com/Exiv2/exiv2/issues/1018#issuecomment-757979745

To give Exiv2 the best possibility of survival in the future, I have been writing a book during the last 9 months.  I hope the book will be finished by the end of February 2021.  The book contains a program **tvisitor** which is modelled on Exiv2.  The book and code are both licensed under GPLv2.  If your application only involves reading metadata, **tvisitor** is probably suitable to your needs and the work in 100% mine.  https://clanmills.com/exiv2/book/

I hope the book will ensure the survival of Exiv2 for many years to come.  Another possibility is that somebody is inspired by the book to create a new metadata library.  The licensing of such a library may be suitable for your needs.

I know one member of Team Exiv2 who believes that he could totally rewrite Exiv2 in one year.  If you were willing to employ him to undertake that task, I am willing to ask him if he is willing and available.  However, I do not wish any involvement beyond making an introduction.  The only compensation I want for making the introduction is to be allowed to peacefully retire.

**Comment by rohit220594** [comment]
Is Exiv2 v0.27.x operates under a dual-licensing scheme, utilizing both the GNU Lesser General Public License (LGPL) and the GNU General Public License (GPL). 
Core Exiv2 Functionality (LGPL-2.1-only): The fundamental components and features of Exiv2 are licensed under LGPL-2.1-only. 

Is this statement true and if can I have any specific documentation to support this statement.
