### ISSUE TITLE
OpenCamera Yaw/Pitch/Roll EXIF.Photo.UserComment Field rendered incorrectly

### ISSUE THREAD

**Issue by Saijin-Naib** [Exiv2/exiv2#2230]
##### **Describe the bug**
OpenCamera-written EXIF.Photo.UserComment field is not rendered properly by exiv2. Instead of the literal text string, it only renders as ```ASCII```.

##### **To Reproduce**
1. PoC Image:  
[20210531_205332_DRO.jpg.zip](https://github.com/Exiv2/exiv2/files/8625672/20210531_205332_DRO.jpg.zip)

2.
 ```
exiv2 -pa 20210531_205332_DRO.jpg 
Exif.Image.Artist                            Ascii      21  USERNAME
Exif.Image.Compression                       Short       1  JPEG (old-style)
Exif.Image.ImageLength                       Long        1  3024
Exif.Image.Make                              Ascii       9  Teracube
Exif.Image.Orientation                       Long        1  (0)
Exif.Image.DateTime                          Ascii      20  2021:05:31 20:53:32
Exif.Image.GPSTag                            Long        1  704
Exif.GPSInfo.GPSLatitude                     Rational    3  41deg 3' 24"
Exif.GPSInfo.GPSAltitude                     Rational    1  0 m
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSProcessingMethod             Ascii       7  CELLID
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  West
Exif.GPSInfo.GPSTimeStamp                    Rational    3  00:53:32
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2021:06:01
Exif.GPSInfo.GPSLongitude                    Rational    3  75deg 19' 13"
Exif.GPSInfo.GPSImgDirection                 Rational    1  30434/100
Exif.GPSInfo.GPSImgDirectionRef              Ascii       2  Magnetic direction
Exif.Image.Copyright                         Ascii      21  USERNAME
Exif.Image.ImageWidth                        Long        1  4032
Exif.Image.Model                             Ascii      13  Teracube One
Exif.Image.Software                          Ascii      28  MediaTek Camera Application
Exif.Image.ImageDescription                  Ascii       1  
Exif.Image.ExifTag                           Long        1  282
Exif.Photo.ExposureBiasValue                 SRational   1  0 EV
Exif.Photo.ExposureProgram                   Short       1  Not defined
Exif.Photo.UserComment                       Ascii      72  ASCII
Exif.Photo.ColorSpace                        Short       1  sRGB
Exif.Photo.ISOSpeedRatings                   Short       1  4500
Exif.Photo.ComponentsConfiguration           Ascii       4  (63)(63)(63)
Exif.Photo.FocalLengthIn35mmFilm             Short       1  Unknown
Exif.Photo.SubSecTimeDigitized               Ascii       3  28
Exif.Photo.DateTimeOriginal                  Ascii      20  2021:05:31 20:53:32
Exif.Photo.DigitalZoomRatio                  Rational    1  1.0
Exif.Photo.SubSecTimeOriginal                Ascii       3  28
Exif.Photo.WhiteBalance                      Short       1  Auto
Exif.Photo.DateTimeDigitized                 Ascii      20  2021:05:31 20:53:32
Exif.Photo.FocalLength                       Rational    1  3.9 mm
Exif.Photo.ExposureMode                      Short       1  Auto
Exif.Photo.MeteringMode                      Short       1  Center weighted average
Exif.Photo.ExposureTime                      Rational    1  0.0499 s
Exif.Photo.Flash                             Short       1  No flash
Exif.Photo.SceneCaptureType                  Short       1  Standard
Exif.Photo.SubSecTime                        Ascii       3  28
Exif.Photo.LightSource                       Short       1  Other light source
Exif.Photo.FNumber                           Rational    1  F1.7
```
3. Mention the branch/commit in which you observed the issue (e.g., `main`, `0.27-maintenance`, `commit 9f721b40`)
0.27.5

##### **Expected behavior**
I'd expect the EXIF Comment field to be rendered properly as it is by Thunar and other programs (as well as other platforms [Android, Windows, etc]):  
![image](https://user-images.githubusercontent.com/19295950/166748991-bc408074-fba9-4e57-b596-818bb5201fcb.png)

##### **Desktop (please complete the following information):**
- OS and version: Alpine Linux Edge (v3.15 x86_64)
- Compiler and version: GCC 11.2.1
- Compilation mode and/or compiler flags: https://git.alpinelinux.org/aports/tree/community/exiv2/APKBUILD

##### **Additional context**
This has ripple-effects as many other programs use exiv2 for handling metadata, so their display is similarly broken due to this (GIMP, ShotWell, etc)

**Comment by postscript-dev** [comment]
@Saijin-Naib:
I don't know much about Exiv2 comments but I have taken a look at your test file and have found out where the problem lies.

Your test file displays:
```bash
$ exiv2 --key Exif.Photo.UserComment 20210531_205332_DRO.jpg
Exif.Photo.UserComment                       Ascii      72  ASCII
```
but the actual value is `ASCII\0\0\0Yaw:304.33597,Pitch:-11.097873152128953,Roll:1.3714360717677891`. The reason the output is wrong is because the tag is set to the wrong type. The `Ascii` type is NULL-terminated (as defined in the Exif specification) and this truncates the output to the first `\0` in the string

If you refer to the list of [Exif tags supported by Exiv2](https://exiv2.org/tags.html), you can see that the `Exif.Photo.UserComment` tag is defined as:

| Tag (hex) | Tag (dec) | IFD | Key | Type | Tag description |
|:--- |:--- |:--- |:--- |:--- |:--- |
| 0x9286 | 37510 | Photo | Exif.Photo.UserComment | Comment | A tag for Exif users to write keywords or comments on the image  besides those in <ImageDescription>, and without the character  code limitations of the <ImageDescription> tag.

The `Comment` type is an Exiv2 shortcut which is saved as an `Undefined` type - as per the Exif Specification.

The truncation issue can be fixed if I add an `Exif.Photo.UserComment` tag with the correct `Comment` type. This time, the full value is displayed:

```bash
$ exiv2 --Modify "set Exif.Photo.UserComment Comment charset=Ascii Yaw:304.33597,Pitch:-11.097873152128953,Roll:1.3714360717677891" 20210531_205332_DRO.jpg

$ exiv2 --key Exif.Photo.UserComment 20210531_205332_DRO.jpg
Exif.Photo.UserComment                       Undefined  71  charset=Ascii Yaw:304.33597,Pitch:-11.097873152128953,Roll:1.3714360717677891
```

For more information on Exiv2 comments, see [Exif 'Comment' values](https://github.com/Exiv2/exiv2/blob/main/exiv2.md#exif_comment_values). Apart from a couple of small exceptions, the new manpage on the `main` branch still works with the latest Exiv2 release.

I am not familiar with the OpenCamera project, but if the correct type is used then I would expect this to fix the problem.

I hope this helps.

**Comment by Saijin-Naib** [comment]
This is a wealth of information! If this could stay open while I upstream this to OpenCamera, that'd be appreciated. Of course, the Issue is tagged wrong as this is not an exiv2 bug 😬

**Comment by Saijin-Naib** [comment]
Upstreamed to OpenCamera:  
https://sourceforge.net/p/opencamera/tickets/956/

Thanks for the correction!
