### ISSUE TITLE
ISO Media / ISO/IEC 14496-12 support.

### ISSUE THREAD

**Issue by LebedevRI** [Exiv2/exiv2#235]
(Cross-reference with https://github.com/darktable-org/rawspeed/issues/121)
Required for https://github.com/Exiv2/exiv2/issues/236

**Comment by clanmills** [comment]
Roman:  Good to hear from you.  I hope everything's good with you.  I replied to #236 without realising that you initiated that report.

**Comment by clanmills** [comment]
I think I've got a good understanding about the scope of this project and documented my investigation #236  We're having a team meeting in May #225 when we'll discuss the specification and schedule for v0.27.

Read/write support for WebP was added for v0.26 in August/September 2016 and took about 4 weeks for two engineers (that's totally finished with test harness and building on all platforms).

**Comment by LebedevRI** [comment]
Hopefully the same mistake won't be repeated yet over again, and there won't be a write support for CR3.

**Comment by clanmills** [comment]
I'm not sure I've understood what you've said.  We support read/write on most formats.  Why would we not support read/write for CR3?  Even to change the timestamp in an image requires read-write support.

If you're wondering why WebP took that 4 weeks, it's because it's 1000 lines of C++, plus test and build support.  Neither Ben nor I were working full-time.  Perhaps about 100 hours each over about 1 month.  So, the effort required to implement CR3 is probably 100-200 hours.

On the subject of changing the timestamps in a file, it would be possible to implement a much faster method than the current code.  A user in Canada has implemented his own stand-alone program to achieve this.  The feature - **_turbo update time-stamps_** - is below the horizon.  By that I mean that I have thought about it and discussed it with a user.  However it's only "**_an idea_**" at the moment.

**Comment by LebedevRI** [comment]
> Why would we not support read/write for CR3?

That was exactly the point.
I'm not against write support for TIFF/etc.
I (we, any dt dev, any sane person working with the raw processing, ...) is against writing into the raw files.
There has been way more than one bugreport with raws becoming broken after such manipulations.

But i'm going to stop with my offtopic/hijacking comments now, sorry.

**Comment by clanmills** [comment]
Ah, yes.  I now understand your point of view.  We could declare CR3 as readonly because editing the image makes it no longer RAW.  You've reduced the effort of this project by 70%! 

Exiv2 knows nothing about pixels.  It only reads/write/modifies metadata.  Image data (pixels) are preserved.  Exiv2 should enable CR3 read/write for time-stamps and other non-image metadata.

Incidentally, in Googling into CR3, some folks believe CR3 = Compressed Raw 3.  I'm not convinced.  I think CR3 = Canon Raw 3.  However, I suspect it's **either** 14 bit colour **or** uses lossless compression.  However it isn't _**RAW at 14 bits/channel**_.

**Comment by LebedevRI** [comment]
>  >  There has been way more than one bugreport with raws becoming broken after such manipulations.

> Ah, yes. I now understand your point of view. We could declare CR3 as readonly because editing the image makes it no longer RAW. You've reduced the effort of this project by 70%!

https://bugs.kde.org/show_bug.cgi?id=387351#c1 (that whole bug, really)
It [looks](https://bugs.kde.org/show_bug.cgi?id=387351#c9) digiKam / @cgilles has finally come to their senses.

**Comment by clanmills** [comment]
Shipped in v0.27.4 RC1.
