### ISSUE TITLE
wrong error message?

### ISSUE THREAD

**Issue by paolobenve** [Exiv2/exiv2#2350]
I have a python app that uses GExiv2 to add gps info to the images.

It modifies the image with teself.exif.set_gps_info(self.longitude, self.latitude, self.altitude)

```
self.exif[IPTC + 'City'] = self.names[0] or ''
self.exif[IPTC + 'ProvinceState'] = self.names[1] or ''
self.exif[IPTC + 'CountryName'] = self.names[2] or ''
self.exif['Iptc.Envelope.CharacterSet'] = '\x1b%G'
```

then it saves the file.

When trying to write a CR3 raw image I get the error "**Setting Image comment in BMFF images is not supported**".

However, the image hasn't any comment changed.

I'd expect a "Setting metadata in BMFF images is not supported" error message.

**Comment by postscript-dev** [comment]
@paolobenve:
> I'd expect a "Setting metadata in BMFF images is not supported" error message.

You are correct, the error message is wrong. Currently we are throwing a [kerInvalidSettingForImage](https://github.com/Exiv2/exiv2/blob/d2253c91f59be50d58a387b17f37a38c2d2025f7/include/exiv2/error.hpp#L196) which has an error message of 

https://github.com/Exiv2/exiv2/blob/d2253c91f59be50d58a387b17f37a38c2d2025f7/src/error.cpp#L51

Instead this should be a [kerWritingImageFormatUnsupported](https://github.com/Exiv2/exiv2/blob/d2253c91f59be50d58a387b17f37a38c2d2025f7/include/exiv2/error.hpp#L195) id which has an error message of 

https://github.com/Exiv2/exiv2/blob/d2253c91f59be50d58a387b17f37a38c2d2025f7/src/error.cpp#L50

I will try and find time during the week to work on this. Once the fix for the `main` branch has been merged, I will add it to the `0.27-maintenance` branch and then this issue can close.

Thanks for reporting this.
