### ISSUE TITLE
Segfault when reading EXIF data from `Exiv2::ExifData` object

### ISSUE THREAD

**Issue by minorsecond** [Exiv2/exiv2#2414]
I'm trying to figure out how to get EXIF values but I think I'm not understanding completely. Sorry for this being marked as a bug, I wasn't sure which option to choose when submitting this.

I have a struct that maps to `ExifKey` values like this:

```
struct Tags {
    static inline const Exiv2::ExifKey CameraMake = Exiv2::ExifKey("Exif.Image.Make");
    static inline const Exiv2::ExifKey CameraModel = Exiv2::ExifKey("Exif.Image.Model");
    static inline const Exiv2::ExifKey CameraOrientation = Exiv2::ExifKey("Exif.Image.Orientation");
    ...
```

In my `ExifData` class, the constructor looks like this:

```
ExifData::ExifData(const std::string &file_path) {
    std::unique_ptr<Exiv2::Image> image{Exiv2::ImageFactory::open(file_path)};
    image->readMetadata();

    if (!image->exifData().empty()) {
        this->Data = image->exifData();
        image_path = file_path;
    } else {
        const std::string error{"No exif data found in file"};
        throw Exiv2::Error(Exiv2::kerErrorMessage, error);
    }
}
```

Then, I have a function that I'm trying to get to return the EXIF value for the key:

```
std::string ExifData::ExifTagValue(const Exiv2::ExifKey &tag) const {
    const auto pos{Data.findKey(tag)};
    const std::unique_ptr<Exiv2::Value> val{pos->getValue()};
    return val->toString();
}
```

I then have getters in my ExifData class (I know I should rename this class as it is also in the Exiv2 namespace):

```
std::string ExifData::camera_make() const {
    return ExifTagValue(Tags::CameraMake);
}

std::string ExifData::camera_model() const {
    return ExifTagValue(Tags::CameraModel);
}

std::string ExifData::camera_orientation() const {
    return ExifTagValue(Tags::CameraOrientation);
}
```

I'm getting a segfault at `const std::unique_ptr<Exiv2::Value> val{pos->getValue()};`. I suspect that this function is all wrong and I'm going about the wrong way at trying to get the EXIF value. I want to be able to pass in a tag from the `Tags` struct, and return the value of that tag for the `Data` object, which is an `Exiv2::ExifData`. Can someone please show me where I'm going wrong?

**Comment by minorsecond** [comment]
I also tried

```
std::string ExifData::ExifTagValue(const Exiv2::ExifKey &tag) const {
    Exiv2::Value::AutoPtr v{Exiv2::Value::create(Exiv2::asciiString)};

    const auto pos{Data.findKey(tag)};
    v = pos->getValue();
    return v->toString();
}
```

but it dies at `v = pos->getValue();`

**Comment by postscript-dev** [comment]
@minorsecond 
After looking at your code examples, I think that the segmentation fault occurs because the file you are using does not contain the metadata tags you are searching for. According to the Exiv2::ExifData Class Reference, the result of [findKey()](https://exiv2.org/doc/classExiv2_1_1ExifData.html#a96c38cbd300ebdfa05f849864b380690) is an iterator but this could point to the end of the STL container rather than a valid element. Calling functions on the end of the container will cause a segmentation fault but can be prevented by adding a simple test. For example,
```
std::string ExifData::ExifTagValue(const Exiv2::ExifKey &tag) const {
    const auto pos{Data.findKey(tag)};
    if (pos == Data.end())                              // New test
        return "";
    const std::unique_ptr<Exiv2::Value> val{pos->getValue()};
    return val->toString();
}
```

Using the Exiv2 command line app (download: [released version](https://exiv2.org/download.html); [nightly builds](https://github.com/Exiv2/exiv2/releases)), you can view the tags in your test file. For example, to display the key, type, vanilla value and translated value of certain tags in a file:

```shell
$ curl --silent -O https://www.exiv2.org/Stonehenge.jpg
$ exiv2 --Print kyvt --key Exif.Image.Make --key Exif.Image.Model --key Exif.Image.Orientation Stonehenge.jpg
Exif.Image.Make                              Ascii      NIKON CORPORATION  NIKON CORPORATION
Exif.Image.Model                             Ascii      NIKON D5300  NIKON D5300
Exif.Image.Orientation                       Short      1  top, left
```

For help using the exiv2 app, see the [manpage](https://github.com/Exiv2/exiv2/blob/main/exiv2.md) on the `main` branch as it contains more examples and explanations of basic concepts.

Exiv2 provides the value of a tag in two different formats, 'vanilla' is the raw data and 'translated' attempts to interpret the value in a meaningful way. As in the example above, the `Exif.Image.Orientation` vanilla value is `1` but the translated output is `top, left`. The translated value is available in multiple languages but can change over time. At the moment, only the vanilla value can be used when writing to a tag.

When writing code, there are also several [sample](https://exiv2.org/doc/examples.html) programs that demonstrate how to use the library. The [addmoddel.cpp](https://exiv2.org/doc/addmoddel_8cpp-example.html) example contains the code change that I mentioned above.

Different tags in a file's metadata can contain the same or similar translated values. The [EasyAccess API](https://exiv2.org/doc/namespaceExiv2.html#ade21436d5ab749937db1de309a880cf3) was added to make it easier for users to find a useful tag. This is demonstrated in the `samples/easyaccess-test.cpp` test file and this mechanism may be useful to you.

If you need help or would like to ask a question, then we usually use the [Matrix](https://matrix.to/#/#exiv2-chat:matrix.org) chat service. I use the [Element](https://element.io/get-started#download) client but others are available. Alternatively, you can ask for help at [Exiv2's GitHub discussions](https://github.com/Exiv2/exiv2/discussions).

**Comment by minorsecond** [comment]
You were correct. Adding some checks to make sure the tag exists, and returning `"Unknown"` if it doesn't, fixed the issue. Thank you!
