### ISSUE TITLE
`AnyError` class removed from `main` branch but still used

### ISSUE THREAD

**Issue by postscript-dev** [Exiv2/exiv2#2460]
#### **Describe the bug**
The [AnyError](https://github.com/Exiv2/exiv2/blob/eae83b44507d2a08636532142e611a642139f494/include/exiv2/error.hpp#L174) class in the `0.27-maintenance` branch has been replaced with the [Error](https://github.com/Exiv2/exiv2/blob/842ef05ee60bff765c0402a211971aed53b728cc/include/exiv2/error.hpp#L235) class in the `main` branch

However, there are still references to `AnyError` on the `main` branch in [contrib/organize/helpers.cpp](https://github.com/Exiv2/exiv2/blob/842ef05ee60bff765c0402a211971aed53b728cc/contrib/organize/helpers.cpp#L1) and [contrib/organize/organize.cpp](https://github.com/Exiv2/exiv2/blob/842ef05ee60bff765c0402a211971aed53b728cc/contrib/organize/organize.cpp#L1).

#### **Expected behavior**
Either:
1. If this code is no longer needed, remove it.
2. Otherwise, update the code.

#### **Desktop (please complete the following information):**
- Exiv2 version and source: `main` branch from git

#### **Additional context**
As this code is not being tested, it is possible that more problems will be uncovered.

I have other projects to work on so don't intend to investigate further.

**Comment by clanmills** [comment]
I think you should remove contrib/organize from 'main' for the following reasons:

1.  contrib applications are not supported by Team Exiv2.  The original author should maintain it.
2.  It's really old and there's no evidence that anybody uses it.
3.  I don't believe there is any test code or user documentation.
4.  It's in contrib because it uses Boost, which would have been a major complication for the build code at that time.
5.  If anybody requests restoration, they should undertake the work and maintain it.

**Comment by clanmills** [comment]
@postscript-dev @kmilos @1div0 Happy New Year.

I've submitted PR #2461 to remove directory contrib/organize from main.

Let's leave contrib/organize in 0.27-maintenance because there's no reason to remove it.  If anybody requests restoration, we can point them to 0.27-maintenance and ask them to port, build, test and document this artefact.

I'm not returning to the project.  I was sniffing around, and enthusiasm took advantage of me.

**Comment by kmilos** [comment]
Happy New Year Robin, hope you're enjoying your retirement!

TBH, I'd rather we removed contrib entirely, i.e. move it to a new, separate Exiv2/contrib repository...

**Comment by clanmills** [comment]
@kmilos  Retirement's the happiest time in life for Alison and I.  We're in good health and excellent spirits.  Life is good. 

Exiv2 has a 'contrib' directory because it's normal and conventional.  Actually, 'contrib' means something like:
1.  This is useful and might help somebody.  However, it's not essential.
2.  Thank you, we don't want this in our codebase.

Delete 'contrib'?  Team Decision.  I'd vote to keep it because it's less effort than a separate Exiv2/contrib repos.

Delete 'contrib/organize?'  We all agree 'Yes'.  I see PR #2461 has failed irrelevant http tests.  Can you approve and merge #2461.  Thanks.

**Comment by clanmills** [comment]
Closed: #2461
