### ISSUE TITLE
Missing Exif.Fujifilm.Rating tag for Fujifilm XT-5 RAF files

### ISSUE THREAD

**Issue by cytrinox** [Exiv2/exiv2#2610]
#### **Describe the bug**
The sample file  **_DSF0052.RAF** has a 4-star rating added via camera X-T5. When importing into darktable, the image as no rating. I've tracked down this to libexiv2. exiv2 reports no **Exif.Fujifilm.Rating** for any of my XT-5 files, for example by using `exiv2 -pt _DSF0052.RAF`.
I validated via exiftool that the rating is indeed encoded:

````
exiftool -Rating _DSF0052.RAF
Rating                          : 4
````

#### **To Reproduce**
 1. Download the https://chaospixel.com/pub/temp/_DSF0052.RAF file (CC0 licensed, shoot by me, feel free to use it in any way).
 2. Run `exiv2 -pt _DSF0052.RAF`
 3. Search or grep for **Exif.Fujifilm.Rating**, it's not available.

#### **Expected behavior**
The output of exiv2 should print **Exif.Fujifilm.Rating** and the rating should be applied during import into darktable.

#### **Desktop (please complete the following information):**
- OS and version: Linux Debian Bullseye with exiv2 built from source (0.27.6)
- Exiv2 version and source: 0.27.6 (tried 0.28.0 as well)
- Compiler and version: gcc version 10.2.1 20210110 (Debian 10.2.1-6)
- Compilation mode and/or compiler flags: -O3 -DNDEBUG

**Comment by postscript-dev** [comment]
@cytrinox 

> I validated via exiftool that the rating is indeed encoded:

I looked at the ExifTool output and the `Rating` tag is actually an XMP tag rather than a FujiFilm tag:

```shell
$ exiftool -g -Rating _DSF0052.RAF
---- XMP ----
Rating                          : 4
```
This explains why `Exif.Fujifilm.Rating` is not found in your file, but does not explain why the XMP rating tag is missing from Exiv2 output. It is worth noting that Exiv2 does not output an XMP validation error or indeed any error when printing all the tags.

I then used ExifTool to add an `Xmp.dc.description` tag (with `exiftool -Description="Test Description" _DSF0052.RAF`) which ExifTool also outputs. For some reason, both XMP tags are invisible to Exiv2.

I looked in our test files (https://github.com/Exiv2/exiv2/tree/main/test/data) and we don't any `.RAF` files that contain XMP data. This could mean that it doesn't work and up until now, we haven't detected the problem. However, we have documented that `.RAF` files have read-only XMP support.

I am sorry but I only have time to have a quick look at your issue, I can't commit to investigating further.

**Comment by kmilos** [comment]
Dumping the embedded JPEG separately w/ e.g. `dd`, and running exiv2 on it I see no fundamental problem, so it could be just something RAF recursion related:
```
exiv2 -pS DSCF0022.JPG
STRUCTURE OF JPEG FILE: DSCF0022.JPG
 address | marker       |  length | data
       0 | 0xffd8 SOI
       2 | 0xffe1 APP1  |   65448 | Exif..II*......................
   65452 | 0xffe1 APP1  |   12288 | http://ns.adobe.com/xap/1.0/.<?x
   77742 | 0xffc4 DHT   |     418
   78162 | 0xffdb DQT   |     132
   78296 | 0xffdd DRI   |       4
   78302 | 0xffc0 SOF0  |      17
   78321 | 0xffda SOS
```

```
Xmp.xmp.Rating                               XmpText     1  0
```

**Comment by cytrinox** [comment]
@kmilos Already have a PR in the pipeline for this :smile:
