### ISSUE TITLE
Bug with file mask

### ISSUE THREAD

**Issue by megadalp** [Exiv2/exiv2#2633]
#### **Describe the bug**
Version
>exiv2 -V                                                                                                                   
exiv2 0.28.0

It is not possible to specify a file mask.

#### **To Reproduce**
Check files:
>ls -1 1/\*.jpg
1/IMG20230506184919.jpg
1/IMG20230506184935.jpg
1/IMG_20230505_175906_596.jpg
1/IMG_20230505_180827.jpg
1/IMG_20230507_110733_631.jpg
1/IMG_20230507_111634.jpg
1/IMG_20230507_133357_288.jpg

Not working:
>exiv2 print 1/\*.jpg
1/\*.jpg: Failed to open the file

For a specific filename everything works:
exiv2 print 1/IMG20230506184919.jpg

#### **Desktop (please complete the following information):**
- OS and version: Windows 10
- Exiv2 version and source: 0.28.0 from exiv2.org, windows binary

#### **Additional context**
in version 0.25 it still worked, it broke since version 0.27.7

**Comment by neheb** [comment]
You can probably work around with

```
exiv2 print $(ls -1 1/*.jpg)
```

**Comment by postscript-dev** [comment]
@megadalp 
I tried to recreate your problem. I used Windows 11 and `exiv2-0.28.0-2019msvc64.zip`/`exiv2-0.27.7-2019msvc64.zip` versions downloaded from https://exiv2.org/download.html . I created a similar directory with 5 well-formed JPEGs and ran the same command as your above example.

When I used Windows' `cmd.exe`, I received the same error as you. I then repeated the same test with the same binaries using [MSYS2](https://www.msys2.org/) (ucrt64) and this time it worked! In the MSYS2 command line, I used `/` instead of `\`.

For `cmd.exe`, in 

https://github.com/Exiv2/exiv2/blob/22b65ccfea31921ef9f96d5ec627433d932364bb/src/futils.cpp#L225-L230

`fs::exists(path);` returns false. This is consistent with https://en.cppreference.com/w/cpp/filesystem/exists which states

> No filesystem exception is thrown if object does not exist (use return value). 

but doesn't explain the problem. I am sorry but I don't have more time to look into this. @neheb do you have any thoughts?

**Comment by neheb** [comment]
No real idea. I know std::filesystem differs between MSVC and GCC but that's about it.

For the MSYS2 case, I'm pretty sure the shell takes care of expanding *.

**Comment by postscript-dev** [comment]
@kmilos 
> It says Windows commands themselves must implement the globbing - I don't think exiv2 did something specific like this for Windows, ever?

I repeated the same test with [exiv2-0.27.5-2019msvc64.zip](https://github.com/Exiv2/exiv2/releases/download/v0.27.5/exiv2-0.27.5-2019msvc64.zip) and it didn't work for me. Perhaps the user had used this version with a different OS.

**Comment by neheb** [comment]
Closing this. There's no bug here.
