### ISSUE TITLE
Why does the unit tests only link to a GTest shared library?

### ISSUE THREAD

**Issue by henryborchers** [Exiv2/exiv2#281]
I'm currently doing some minor tweaking of the CMake script to allow Exiv2 to be build as a subproject. (I'll send a pull request when I'm done if you are interested).  

I do have a question though. Is there a reason why the CMake build script only links the unit tests to GTest when it's is a shared library? Please correct me if I'm wrong but I was under the impression that best practice for GTest was to link it as a static library.

**Comment by clanmills** [comment]
@henryborchers Good to hear from you again, Henry.  Hope all's good with you in Illinois.

I'm going to leave Luis (our CMake expert) to answer this.  Dan added GTest, so it's possible that he'll have something to say about this.

It would be helpful if you were explain what you're thinking about using GTest in a shared library. 

There is an outstanding PR concerning CMake/Exiv2 sub-projects.  https://github.com/Exiv2/exiv2/pull/233

**Comment by henryborchers** [comment]
@clanmills Thanks the greeting back.  

I saw that PR but also noticed that the fix should be very simple. All you really have to do is is replace CMAKE_SOURCE_DIR with PROJECT_SOURCE_DIR for all the BUILD_INTERFACE target_include_directories().  It's working so far for me, I just want to run the unit_tests to make sure that I didn't break anything along the way and it's handling the DLL is a little irritating to manage.

**Comment by piponazo** [comment]
Hi guys. The only reason why I chose to use GTest as a dynamic library was to speed up the linking. When I work in some personal projects where I have several test runners, I tend to use GTest as a dynamic library just to speed up the linking phase.

In this project we only have 1 test runner, and we could switch to the usage of a static version of GTest if this simplifies our lives. 

I just need to adapt the `conanfile.py` and revert the change introduced in 2bad771. I will create a PR as soon as I find some spare time

**Comment by D4N** [comment]
Is there an advantage when linking statically? If there is none, why
change it?

**Comment by henryborchers** [comment]
If I use static linking, I don't have to relocate the gtest dll onto the path before I run it. It's one less step that I need to do. 

Anyways, why hard code the linking type for this in the CMakeLists.txt? Why not let it work with whatever the type of library the user wants to use? Static or dynamic?

**Comment by piponazo** [comment]
Right, for us, the relocation of the DLLs is done automatically when using **conan**. 

Any decision taken about the GTest linking would be a hard code. In the current configuration we are forcing the usage of GTest as a dynamic library. If we remove this code from the CMake I would be forcing the usage of GTest as a static library:

```
target_compile_definitions(unit_tests
    PRIVATE
        GTEST_LINKED_AS_SHARED_LIBRARY=1
)
```

If you know how to make the CMake code flexible enough to support both cases, I invite you to create a patch. I would be happy to review it. Otherwise, I will look into this when I have some spare time.

**Comment by henryborchers** [comment]
Thanks, I'll be happy to give it try

**Comment by piponazo** [comment]
@henryborchers We recently added gitlab CI script to build Exiv2 in the most known linux distributions and all of them use GTest as a SHARED library by default. As you can see I created a PR (#321) trying to switch to STATIC gtest, but @D4N pointed out the previous fact.

I do not think we should spend any minute more in this topic, since giving the option for supporting both kind of libraries would make the CMake code more convoluted. Therefore I'm closing this issue.
