### ISSUE TITLE
Please create a new release from 0.26 branch

### ISSUE THREAD

**Issue by dirkmueller** [Exiv2/exiv2#336]
There have been a lot of commits flowing into the 0.26 branch: 

$ git log --no-merges v0.26..upstream/0.26 --pretty=oneline | wc -l
57

can you please create a new release/tag from it and push it?

**Comment by D4N** [comment]
Sorry to disappoint you, but we currently lack the resources for a full 0.26.1 release, as that would require creating builds for every platform and the required scripts & utilities for that have not been ported to the github + git infrastructure yet. Doing this work now will delay 0.27 RC (planed for autumn) further, which we consider the current top priority.

Since you are the package maintainer for OpenSUSE, I guess you cannot simply pull in the current 0.26 branch and build from that? Or apply all pull requests as patches on top of v0.26? (I only know the Fedora packaging guidelines and they surely wouldn't allow the first option.)

Sorry again for not really helping you. We intend to get better with 0.27 and release frequent bugfix releases with that.
