### ISSUE TITLE
XMP uses incorrect bit-width integers on LP64 data model systems (linux, unix)

### ISSUE THREAD

**Issue by smr99** [Exiv2/exiv2#363]
The file XMP_Const.h typedefs specific bit-width integers: XMP_Int32, etc.  If "XMP_MacBuild" is defined, then <stdint.h> is included and the standard types (e.g. int32_t) are used; if not, XMP_Int32 is typedef'd as "signed long".  This fails on a linux 64 bit machine because long is 64 bits, not 32.

The best fix is to use the standard types.  Newer versions of XMP do this.

Note also that there are assertions within XMPMeta.cpp that check these typedefs.  The XMP assertions can be enabled using -DXMP_DebugBuild=1.  I would suggest that the travis and appveyor builds use this.

More information in the threads:
* https://github.com/Exiv2/exiv2/pull/289
* https://github.com/Exiv2/exiv2/pull/284

This issue written up at the request of @D4N .

**Comment by clanmills** [comment]
Thanks for reporting this.  Something very similar was reported in the last few weeks.  I've been contributing to Exiv2 for 10 years, and during that time, the code in xmpsdk/ has been almost untouched.  In v0.27, we will offer a build option to build with XMPsdk/2016.

I see you've already spoken to @D4N about this matter.  Have you agreed on what's to be done about this?

**Comment by piponazo** [comment]
I have re-read this again and I think we do not need to take any action for 0.27. Maybe we could address this issue on 0.28 since we will require c++11 and then every compiler will provide the **cstdint** header. At that point we could make the fix in the old version of XMP that is living inside the exiv2 repo.

**Comment by emmenlau** [comment]
May I kindly ask whether this fix may be reconsidered soon?

I've just hit this very same block, and was so confused by it that I wasted a whole afternoon trying to figure out what was going on. It seemed virtually impossible that XMP support had such an cruel issue: exiv2 builds successfully on LP64 platforms with XMP enabled, but every attempt at using XMP crashes and burns. For me, this renders the library basically useless, because every other "file open" operation may crash, depending on if a file has XMP detected.

The fix in `XMP_Const.h` was almost trivial. And in my humble opinion, any change is likely better than the current state on Linux. Therefore I'd like to kindly suggest a re-evaluation. A non-intrusive improvement would be to enable the `typedef`s at least on MacOS *and* Linux, where both `stdint.h` and the `intxx_t` types should be available.

But according to what I could find (on https://stackoverflow.com/a/2628014/7200132), `stdint.h` is provided since at least Visual Studio 2010. So requiring it by default on all platforms might actually be fine nowadays?

**Comment by clanmills** [comment]
Folks:

Can you help me understand what's being discussed here.  We've been building 32 and 64 bit versions of Exiv2 with XMP support on Mac/Windows/Linux for about 10 years and nobody has reported:  __*every attempt at using XMP crashes and burns*__ on any platform.

Can we have a "top level" description of the issue.  By "top-level" I mean, please defined the exiv2 version/platform/command-line and test file explanation of the user issue.

Then we can dive down into stdint.h on Windows, XMP_Const.h and other nuts-n-bolts.

**Comment by emmenlau** [comment]
@clanmills , sorry I assumed that everything was already known and I'm just late to the party! :-)

So here is a hopefully better issue report: I build exiv2-0.26, exiv2-0.26.1 and exiv2 master from today on Ubuntu 18.04 Linux x86_64 with XMP enabled. When I use my image reader (that includes an exiv2 binding) on various images I get exception:
```
.../exiv2-0.26/xmpsdk/src/XMPMeta.cpp:734: static bool XMPMeta::Initialize(): Assertion `sizeof(XMP_Int32) == 4' failed.
```
I get the same exception also on a major part of the exiv2 test suite. So I assume that my images are not to blame.

Furthermore, looking at the `xmpsdk` code in the exiv2 repository this assertion makes perfect sense to me, since `XMP_Const.h` defines `XMP_Int32` as `signed long` in https://github.com/Exiv2/exiv2/blob/beab2898caeaecef5a276955f73248c759b0bb0c/xmpsdk/include/XMP_Const.h#L53

And since `sizeof(signed long)` is `8` on Linux LP64 the code should actually never work in this setup? I've tried to find another explanation for my problem but to the best of my knowledge, `XMP_Const.h` seems broken for Linux LP64.

Does that make sense? Is there anything I can further do to help better understand this issue?

**Comment by clanmills** [comment]
Where's the problem?

```
720 rmills@rmillsmbp:~/gnu/exiv2/team/book $ exiv2 --verbose --version --grep bits
exiv2 0.27.2.1
bits=64
721 rmills@rmillsmbp:~/gnu/exiv2/team/book $ exiv2 -px http://clanmills.com/Stonehenge.jpg
Xmp.xmp.Rating                               XmpText     1  0
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
Xmp.dc.description                           LangAlt     1  lang="x-default" Classic View
722 rmills@rmillsmbp:~/gnu/exiv2/team/book $ 
```

__*I get the same exception also on a major part of the exiv2 test suite.*__ Where?

**Comment by clanmills** [comment]
On Ubuntu:
```
rmills@rmillsmm-ubuntu:~$ uname -a
Linux rmillsmm-ubuntu 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
rmills@rmillsmm-ubuntu:~$ exiv2 --verbose --version --grep bits --grep platform
exiv2 0.27.2.2
platform=linux
bits=64
rmills@rmillsmm-ubuntu:~$ exiv2 -px http://clanmills.com/Stonehenge.jpg
Xmp.xmp.Rating                               XmpText     1  0
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
Xmp.dc.description                           LangAlt     1  lang="x-default" Classic View
rmills@rmillsmm-ubuntu:~$ 
```

**Comment by emmenlau** [comment]
I get the exceptions in the test suite in thousands of places, so I'll just paste a few examples here, ok? With `libexiv2.so.0.27.2.2` for example, I get:
```
cd /home/ciusr/GIT-exiv2/test && env EXIV2_BINDIR="/data/Debug/exiv2/bin" make test
make[2]: Entering directory '/home/ciusr/GIT-exiv2/test'
mkdir -p tmp
rm -rf tmp/test-failed
Running addmoddel.sh ...
all testcases passed.
Running conversions.sh ...
Files /home/ciusr/GIT-exiv2/test/tmp/conversions.out and /home/ciusr/GIT-exiv2/test/data/conversions.out differ
3,4c3,6
< exiv2: /home/ciusr/GIT-exiv2/xmpsdk/src/XMPMeta.cpp:738: static bool XMPMeta::Initialize(): Assertion `sizeof(XMP_Int32) == 4' failed.
< ./functions.source: line 6: 23220 Aborted                 (core dumped) $VALGRIND $bin$prog "$@"
---
> Xmp.dc.description                           LangAlt     1  lang="x-default" The Exif image description
> Exif.Image.ImageDescription                  Ascii      27  The Exif image description
> Iptc.Application2.Caption                    String     26  The Exif image description
> Iptc.Envelope.CharacterSet                   String      3  
8,9c10,13
< exiv2: /home/ciusr/GIT-exiv2/xmpsdk/src/XMPMeta.cpp:738: static bool XMPMeta::Initialize(): Assertion `sizeof(XMP_Int32) == 4' failed.
< ./functions.source: line 6: 23235 Aborted                 (core dumped) $VALGRIND $bin$prog "$@"
---
> Xmp.dc.description                           LangAlt     1  lang="x-default" The Exif image description
> Exif.Image.ImageDescription                  Ascii      27  The Exif image description
> Iptc.Envelope.CharacterSet                   String      3  
> Iptc.Application2.Caption                    String     26  The Exif image description
13,14c17,20
< exiv2: /home/ciusr/GIT-exiv2/xmpsdk/src/XMPMeta.cpp:738: static bool XMPMeta::Initialize(): Assertion `sizeof(XMP_Int32) == 4' failed.
< ./functions.source: line 6: 23254 Aborted                 (core dumped) $VALGRIND $bin$prog "$@"
---
> Xmp.dc.description                           LangAlt     1  lang="de-DE" The Exif image description
> Exif.Image.ImageDescription                  Ascii      27  The Exif image description
> Iptc.Envelope.CharacterSet                   String      3  
> Iptc.Application2.Caption                    String     26  The Exif image description
18,19c24,26
< exiv2: /home/ciusr/GIT-exiv2/xmpsdk/src/XMPMeta.cpp:738: static bool XMPMeta::Initialize(): Assertion `sizeof(XMP_Int32) == 4' failed.
< ./functions.source: line 6: 23265 Aborted                 (core dumped) $VALGRIND $bin$prog "$@"
---
> Warning: Failed to convert Xmp.dc.description to Iptc.Application2.Caption
> Warning: Failed to convert Xmp.dc.description to Exif.Image.ImageDescription
> Xmp.dc.description                           LangAlt     2  lang="it-IT" Ciao bella, lang="de-DE" The Exif image description
```
Thousands of similar lines follow.

**Comment by emmenlau** [comment]
Would it be possible for you to check if your binary actually executes the assertion in `xmpsdk/src/XMPMeta.cpp:738` or not? I think this might go a long way, since if it does, I do not see how it can work.
So without better clues I would assume that `static bool XMPMeta::Initialize()` around line `738` is not executed for you. Would that make sense?

**Comment by clanmills** [comment]
I've been building and running the test suite dozens of times every day for 10 years and never seen those errors.

How are you building the library?

**Comment by piponazo** [comment]
In #289 it was discussed that one possible way to reproduce the issues was to define `DEBUG` or `XMP_DebugBuild=1`. @emmenlau Are you defining any of those ? You can see all the compilation flags if running `make VERBOSE=1`.

**Comment by emmenlau** [comment]
Argh! Yes, I have a default set of `cflags/cxxflags` that includes `DEBUG`. Dammit. This used to work fine in an earlier version of exiv2, something around v0.25. I updated a longer while ago but must have been lucky not to run into the XMP issue until now, probably because we typically do not have too many files with XMP content.

I see that exiv2 really does not digest the `DEBUG` flag all too well :-( I will disable it now.

**Comment by piponazo** [comment]
I'm happy to see that we have reached the root of your issue :grinning: . If you want to know more why we dropped that **custom** `DEBUG` flag, you can see the reasoning of the change in #272

**Comment by smr99** [comment]
You will only see assertion failures if you enable them.  The current Travis runs do not.
  See the initial post on this thread.

On July 17, 2019 9:20:33 p.m. GMT+01:00, Robin Mills <notifications@github.com> wrote:
>I've been building and running the test suite dozens of times every day
>for 10 years and never seen those errors.
>
>How are you building the library?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Exiv2/exiv2/issues/363#issuecomment-512552929

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmenlau** [comment]
So for the sake of completeness, maybe it would be a good idea if someone from the dev team would check in `static bool XMPMeta::Initialize()` what they get for `sizeof(XMP_Int32)`? If `XMP_Int32` is 8 bit as I would assume on LP64 Linux, it may still be worthwhile to switch to `int32_t` instead to be sure.

**Comment by clanmills** [comment]
@emmenlau I'll look at that tomorrow (or more likely Saturday as we have friends visiting tomorrow and Friday).  I'm talking on the phone to a user in Arkansas while trying to release Exiv2 v0.27.2-RC3 at the moment.  I'm talking on Slack to Exiv2 Team Members in Spain and Germany.  So, I'm feeling a little pressured at the moment.

We're making progress with your issue.  Feel free to ping me if I forget to investigate: robin@clanmills.com

**Comment by clanmills** [comment]
I've modified xmpsdk/src/XMPMeta.cpp as follows:
```
	XMP_Assert ( ! XMP_PropIsAlias  ( ~kXMP_PropIsAlias ) );

	printf("sizeof(XMP_Int32) = %lu\n",sizeof(XMP_Int32));

	#if 0	// Generally off, enable to hand check generated code.
```
And when I run it, I get:
```
512 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -px http://clanmills.com/Stonehenge.jpg
sizeof(XMP_Int32) = 4
Xmp.xmp.Rating                               XmpText     1  0
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
Xmp.dc.description                           LangAlt     1  lang="x-default" Classic View
513 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I don't know what problem we're investigating.  Why would XMP_Int32 not be 4 bytes (as asserted).

Adobe's code has been in Exiv2 for at least 10 years and given excellent service.  I can hardly remember changing anything in the xmpsdk/ directory.

**Comment by smr99** [comment]
The problem is the following.  

The file XMP_Const.h typedefs specific bit-width integers: XMP_Int32, etc. If "XMP_MacBuild" is defined, then <stdint.h> is included and the standard types (e.g. int32_t) are used; if not, XMP_Int32 is typedef'd as "signed long". This fails on a linux 64 bit machine because long is 64 bits, not 32.


On July 18, 2019 12:10:07 a.m. GMT+01:00, Robin Mills <notifications@github.com> wrote:
>I've modified xmpsdk/src/XMPMeta.cpp as follows:
>```
>	XMP_Assert ( ! XMP_PropIsAlias  ( ~kXMP_PropIsAlias ) );
>
>	printf("sizeof(XMP_Int32) = %lu\n",sizeof(XMP_Int32));
>
>	#if 0	// Generally off, enable to hand check generated code.
>```
>And when I run it, I get:
>```
>512 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $
>bin/exiv2 -px http://clanmills.com/Stonehenge.jpg
>sizeof(XMP_Int32) = 4
>Xmp.xmp.Rating                               XmpText     1  0
>Xmp.xmp.ModifyDate                           XmpText    25 
>2015-07-16T20:25:28+01:00
>Xmp.dc.description                           LangAlt     1 
>lang="x-default" Classic View
>513 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
>```
>
>I don't know what problem we're investigating.  Why would XMP_Int32 not
>be 4 bytes (as asserted).
>
>Adobe's code has been in Exiv2 for at least 10 years and given
>excellent service.  I can hardly remember changing anything in the
>xmpsdk/ directory.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Exiv2/exiv2/issues/363#issuecomment-512601425

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmenlau** [comment]
> And when I run it, I get:
> ```
> 512 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -px http://clanmills.com/Stonehenge.jpg
> sizeof(XMP_Int32) = 4
> ```
Am I correctly assuming that the `mbp` in `rmillsmbp` is short for MacBookPro? The issue will not show on MacOS.

So here are the results I would anticipate:
 * On MacOS: `sizeof(XMP_Int32) = 4` (good)
 * On Linux i686: `sizeof(XMP_Int32) = 4` (good)
 * On Linux x86_64: `sizeof(XMP_Int32) = 8` (possibly bad?)
 * On Windows x86: `sizeof(XMP_Int32) = 4` (good)
 * On Windows x64 with Microsoft or Intel compilers: `sizeof(XMP_Int32) = 4` (good)
 * On Windows x64 with GNU or Clang compilers: `sizeof(XMP_Int32) = 8` (possibly bad?)

Other flavors of Unix should follow the scheme for Linux, unless they are a MacOS-flavor.

One thing I would like to add: By now I'm under the impression that `sizeof(XMP_Int32)` has been `8` on Linux x86_64 since forever. So maybe this is not an actual problem. Or at least it seems not to have manifested in actual issues, except for this one here? Its possible that Adobe's XMP was coded under the assumption that `sizeof(XMP_Int32)` would be `4`, but that there is no actual problem if its bigger(?)

**Comment by clanmills** [comment]
I've built/run this on Linux (both 32 bit and 64 bit).  You're quite correct: `sizeof(XMP_Int32)` is 4 on 32 bit Linux and 8 on 64 bit Linux.  Clearly the XMP_Assert() is hollow.  This is rather odd.  However, the code has been there for a long time without causing any issues.

Please understand that I am reluctant to change any of the Adobe code.  For v0.27, it is possible to build Exiv2 using Adobe's XMPsdk/2016.  This is documented in README-CONAN.md.  If anything has to be changed in XMPsdk, I would like us adopt XMPsdk as an external library and report bugs/issues to Adobe.

**Comment by emmenlau** [comment]
I can perfectly relate to this, never change a running system. However it may also be worthwhile to improve the behavior with respect to this known issue. What do you think about adding a more helpful diagnostic message before the assertion?
Something like:
```
#ifdef DEBUG
    if(sizeof(XMP_Int32) != 4) {
        std::cerr << "Warning: this code has a known limitation on LP64 architecture for your platform when built with DEBUG enabled." << std::endl;
        std::cerr << "Please build without -DDEBUG unless you know what you are doing." << std::endl;
    }
#endif
```
in `XMPMeta::Initialize()`?

This may serve as a sufficiently helpful pointer for other people experiencing this issue, while at the same time it comes at zero cost for everyone else.

Of course that's just my two cents... :-)

**Comment by clanmills** [comment]
No.  I will not do that.  Somebody will open another bug report if I put that in the code.

**Comment by smr99** [comment]
Maybe it causes no issues that you know about.  But (a) it is clearly wrong that an "int32" has 64 bits, (b) it has 32 bits on many architectures, (c) prevents you from running complete test suite with assertions, and (d) has been fixed by Adobe in current upstream to use <stdint.h> on Linux (thus correctly using 32 bits).  So I have difficulty understanding the reluctance to fix an obvious bug.  There is a vanishingly small chance of any repercussions  of using 32 bits on Linux 64 -- any such would  almost certainly have been seen already in the other architectures that use 32 bits.  Moreover, using your suggestion of an out of tree build with latest xmpsdk would trigger the same issues for those users.

Best,
Steve

On July 18, 2019 11:00:22 a.m. GMT+01:00, Robin Mills <notifications@github.com> wrote:
>I've built/run this on Linux (both 32 bit and 64 bit).  You're quite
>correct: `sizeof(XMP_Int32)` is 4 on 32 bit Linux and 8 on 64 bit
>Linux.  Clearly the XMP_Assert() is hollow.  This is rather odd. 
>However, the code has been there for a long time without causing any
>issues.
>
>Please understand that I am reluctant to change any of the Adobe code. 
>For v0.27, it is possible to build Exiv2 using Adobe's XMPsdk/2016. 
>This is documented in README-CONAN.md.  If anything has to be changed
>in XMPsdk, I would like us adopt XMPsdk as an external library and
>report bugs/issues to Adobe.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Exiv2/exiv2/issues/363#issuecomment-512750652

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by clanmills** [comment]
@smr99 You know there are always unseen repercussions of changing code.  Nothing is free.  Nothing is trivial.  Nothing is "can't go wrong".

One day I hope to remove the xmpsdk code from the code base.  We've had numerous requests to support Adobe XMPsdk as an external library  We added support for Adobe XMPsdk/2016 in v0.27 via Conan.  I don't know if anybody has used that because I only hear about things being broken!

Team Exiv2 is a happy little band of C++ Engineers.  If you'd like to join the team and be "King XMPsdk", you can submit a PR for that code and it'll go into v0.27.3 (scheduled 2019-09-30).

I'm hoping we'll have a Team Meeting next year in France.  https://github.com/Exiv2/exiv2/issues/911#issuecomment-511090735
