### ISSUE TITLE
www.exiv2.org is down

### ISSUE THREAD

**Issue by supertobi** [Exiv2/exiv2#385]
I know, its not a code issue but www.exiv2.org is down.

**Comment by clanmills** [comment]
There's a problem with the web-site.  In the meanwhile, there happens to be a pre-release of the website available here on which you can access most (but not all) of the content on the main web-site.

http://clanmills.com/exiv2/exiv2/index.html

Andreas received this email on Wednesday from Amazon Web Services:

_Unfortunately, the maintenance of your EC2 instance i-da301d51 in region 'eu-west-1',
has failed, causing the instance to stop. Please accept our apologies for this issue._

_As this instance is EBS-backed for its root volume, you are able to stop
and then start it as per normal for EBS-backed instances. This will
migrate it to new, healthy hardware and your instance should work as before.
If you have an EIP on a classic instance you will need to manually associate
the EIP after the instance has started._

_No data will be lost when you stop and start because your volumes are EBS
backed. However, we can also see that this instance has instance-store
volume(s). Do you require the data on these instance-store volume(s)? If
so, then please let us know as soon as possible, so that we can attempt
to recover this data._

_If not, please feel free to stop/start an instance which will resolve the
current issue. More information about stopping and starting EC2 instances
is available here:_

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Stop_Start.html

_Please let us know if you have any questions._

Andreas emailed me about this and hopes to fix it in the next few days.

**Comment by clanmills** [comment]
@supertobi  Thanks to miracles by Andreas and Amazon, the web-site is back on-line.
