### ISSUE TITLE
[Question] Length of description in XMP 

### ISSUE THREAD

**Issue by ulkesh11** [Exiv2/exiv2#396]
What is the maximum length of string that can be accepted by `XMP.dc.description`?

**Comment by clanmills** [comment]
@vacky11 It appears that the XMP dislikes empty strings and doesn't store them.  I'm a little surprised!

Here's a test:
```
811 rmills@rmillsmbp:~/temp $ curl --silent -O http://clanmills.com/Stonehenge.jpg
812 rmills@rmillsmbp:~/temp $ exiv2 -px --grep desc/i Stonehenge.jpg 
Xmp.dc.description                           LangAlt     1  lang="x-default" Classic View
813 rmills@rmillsmbp:~/temp $ exiv2 -pX Stonehenge.jpg | xmllint -format - 
<?xml version="1.0"?>
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/" rdf:about="" xmp:Rating="0" xmp:ModifyDate="2015-07-16T20:25:28+01:00">
      <dc:description>
        <rdf:Alt>
          <rdf:li xml:lang="x-default">Classic View</rdf:li>
        </rdf:Alt>
      </dc:description>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
```
Now we'll set description to the empty string and the description disappears completely!
```
814 rmills@rmillsmbp:~/temp $ exiv2 -M"set Xmp.dc.description ''" Stonehenge.jpg 
815 rmills@rmillsmbp:~/temp $ exiv2 -px --grep desc/i Stonehenge.jpg 
816 rmills@rmillsmbp:~/temp $ exiv2 -pX Stonehenge.jpg | xmllint -format - 
<?xml version="1.0"?>
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" rdf:about="" xmp:Rating="0" xmp:ModifyDate="2015-07-16T20:25:28+01:00"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
```
Yet, we set it to a single space:
```
817 rmills@rmillsmbp:~/temp $ exiv2 -M"set Xmp.dc.description ' '" Stonehenge.jpg 
818 rmills@rmillsmbp:~/temp $ exiv2 -px --grep desc/i Stonehenge.jpg 
Xmp.dc.description                           LangAlt     1  lang="x-default"  
819 rmills@rmillsmbp:~/temp $ exiv2 -pX Stonehenge.jpg | xmllint -format - 
<?xml version="1.0"?>
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/" rdf:about="" xmp:Rating="0" xmp:ModifyDate="2015-07-16T20:25:28+01:00">
      <dc:description>
        <rdf:Alt>
          <rdf:li xml:lang="x-default"> </rdf:li>
        </rdf:Alt>
      </dc:description>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
820 rmills@rmillsmbp:~/temp $ 
```
Is this the behaviour that is of interest/concern to you?

The XMP processing is performed by Adobe's XMPsdk which is embedded in Exiv2.  I don't know why it would remove `description` when we use the empty string.

For v0.27, we have a feature to enable you to build Exiv2 with the existing XMPsdk, or Adobe XMPsdk 2016.  I can build and test this behaviour with XMPsdk 2016 later today to see if this behaviour changes.

**Comment by vacky11** [comment]
@clanmills  Thank you for your quick reply. 
Actually my question is, is there a limit in size of string that can be stored in `XMP.dc.description`? Or we can store unlimited characters in `XMP.dc.description`? I hope im being clear now

**Comment by clanmills** [comment]
Thanks for the clarification.  There are two kinds of limits:
1) Imposed by File Format Specifications

If you are storing XMP in a JPEG, the whole XMP packet must fit into a JPEG chunk which mustn't exceed 64k bytes.

Adobe extended their specification to enable XMP packets to span multiple chunks.  I believe this is supported by XMPsdk 2016, however I haven't tested that feature.  I can't remember how "Extended XMP" is defined, however I think it's likely that no single data element span multiple chunks. So the `Xmp.dc.description` will be limited to about 65000 bytes.

2) Imposed by the implementation (caused by buffers and the like).

If you're passing the description on the bash command-line, bash will impose an argument for the maximum size of an argument.  And there's (unlikely, yet possible) buffer sizes in the implementation.

Here's what I see:
```
511 rmills@rmillsmbp:~ $ x='1234567890'; for i in {1..10}; do x=$x$x; done ; echo ${#x}
10240
512 rmills@rmillsmbp:~ $ exiv2 -M"set Xmp.dc.description $x" ~/Stonehenge.jpg 
513 rmills@rmillsmbp:~ $ x='1234567890'; for i in {1..12}; do x=$x$x; done ; echo ${#x}
40960
514 rmills@rmillsmbp:~ $ exiv2 -M"set Xmp.dc.description $x" ~/Stonehenge.jpg 
515 rmills@rmillsmbp:~ $ x='1234567890'; for i in {1..14}; do x=$x$x; done ; echo ${#x}
163840
516 rmills@rmillsmbp:~ $ exiv2 -M"set Xmp.dc.description $x" ~/Stonehenge.jpg 
Exiv2 exception in modify action for file /Users/rmills/Stonehenge.jpg:
Size of XMP JPEG segment is larger than 65535 bytes
517 rmills@rmillsmbp:~ $ x='1234567890'; for i in {1..16}; do x=$x$x; done ; echo ${#x}
655360
518 rmills@rmillsmbp:~ $ exiv2 -M"set Xmp.dc.description $x" ~/Stonehenge.jpg 
-bash: /usr/local/bin/exiv2: Argument list too long
519 rmills@rmillsmbp:~ $ 
```
So, no problem with strings of 40k.  After that you can expect difficulties.

How big is the string have in mind?

**Comment by vacky11** [comment]
@clanmills Thanks for the detailed and clear explaination. 
I was looking for a way to add metadata strings to an image (jepg/tiff) without any limit. But I guess this is not possible?

**Comment by clanmills** [comment]
I have good and bad news for you.

**_Good News_**: Tiff is a 32 bit file format and can hold lots of data.  We're working on our BigTiff support which is a 64 bit implementation of tiff.

**_Bad News_**: JPEG is really a 16 bit format.  The file is "chunked" and each "chunk" has a 2 byte length.  No chunk can exceed 65535 bytes.  Some metadata (such as ICC profiles) span multiple "chunks".  However, the JPEG format is a relic of 16 bit computing.

I'm not too sure about how to proceed.  I believe it's very important to adhere to standards, or common-practice.  Perhaps the XMP sidecar file (using extended XMP) would enable you to store large amounts of data.

**Comment by vacky11** [comment]
@clanmills 
Thank you very much for your time in explaining all the details. I really appreciate it.

**Comment by boardhead** [comment]
The extended XMP specification completely removes the length limitation in JPEG images.  Any single XMP tag may have an arbitrarily large size.

**Comment by vacky11** [comment]
@boardhead  Thank you for your input. Can I use extended XMP specification through exiv2 library? If yes, can you please give me a example of it.

**Comment by clanmills** [comment]
For v0.27, we provide an option to build Exiv2 with Adobe's XMPsdk 2016.  I haven't investigated Extended XMP in Exiv2 with XMPsdk 2016.  I'll build that now and report back.

Thanks very much to Phil for this input.  As always, very helpful.  Thanks.

**Comment by piponazo** [comment]
I followed the instructions available in the document `WORK-IN-PROGRESS` and I could compile it without problems:

```
    mkdir build && cd build
    conan install .. --options xmp=True
    cmake -DCMAKE_BUILD_TYPE=Release -DEXIV2_ENABLE_XMP=OFF -DEXIV2_ENABLE_EXTERNAL_XMP=ON -DBUILD_SHARED_LIBS=ON ..
```
Remember that I did some work to bring the XMP 2016 dependency with conan.

**Comment by clanmills** [comment]
Thanks @piponazo You are right.  I had forgotten that we were building that with conan.  I think we should remove the relic xmpsdk/buildXMPsdk.sh.

@vacky11 I'm still getting linker errors on my machine.  I'm going out to have some fun (in Glacier National Park, Montana).  I'll spend more time on this later today.
![org_dsc00160](https://user-images.githubusercontent.com/529982/43788156-fb273996-9a29-11e8-96ce-48307e48f838.JPG)

**Comment by clanmills** [comment]
@vacky11 I've tried to build on a different Mac and getting the same linker errors.  I'm surprised because I'm sure I built this a couple of months ago.   I'll try tomorrow on Linux.

**Comment by clanmills** [comment]
Progress:
1) I've got exiv2 + Adobe xmpsdk 2016 built and working
2) I still get the message:
```
Exiv2 exception in modify action for file Stonehenge.jpg:
Size of XMP JPEG segment is larger than 65535 bytes
```

I'm not worried by this message.  It's coming from src/jpgimage.cpp `void JpegBase::doWriteMetadata(BasicIo& outIo)`
```
                        if (exifSize + 8 > 0xffff) throw Error(kerTooLargeJpegSegment, "Exif");
                        us2Data(tmpBuf + 2, static_cast<uint16_t>(exifSize + 8), bigEndian);
                        std::memcpy(tmpBuf + 4, exifId_, 6);
                        if (outIo.write(tmpBuf, 10) != 10) throw Error(kerImageWriteFailed);
```

Exiv2 is writing the metadata to the JPEG and is hard-wired to throw if the XMP overflows a single 64k chunk.  So although the Adobe XMPsdk handles "Extended XMP", Exiv2 doesn't deal with it gracefully.

There's almost certainly something to be done in readMetadata() to read in from multiple "chunks".  I'll also have to investigate and verify TIFF and PNG handling, however as those formats allow XMP to exceed 64k, I expect they'll be OK.

When I get home from vacation, I'll fix this for JPEG and verify it's OK for other formats (TIFF, PNG and sidecar).

**Comment by boardhead** [comment]
Wow Alan, you're definitely spending too much time on your computer when you could be out hiking on that picturesque glacier.  But since we're sharing vacation pics, here is a pic of me from the vacation I was on when this thread started:
![manitoumountaintrail](https://user-images.githubusercontent.com/596983/43851342-65fa5bac-9b08-11e8-87ec-a3fe0c9e7bd9.jpg)

**Comment by clanmills** [comment]
Thanks, Phil.  One day we'll have a hike or run together in Canada, or England, or somewhere else.

You're right.  Neither of us should be solving software puzzles while on vacation.  Let's keep that fun for home in winter!  Today we travel to Mt St Helens to start this (crazy) adventure:  http://clanmills.com/Homepages/2018/plan.shtml

**Comment by boardhead** [comment]
Wow again.  That's a big commitment and quite an adventure.

**Comment by vacky11** [comment]
@clanmills and @boardhead  Thank you for your valuable inputs even while on vacation. Hope you guys enjoy rest of your vacation.

**Comment by clanmills** [comment]
There is insufficient time remaining in the v0.27 project to support Extended XMP.

**Comment by viskin** [comment]
We use this great library in our project, and sadly from time to time we encounter jpegs that have XMP region > 64K. For now, we just ignore XMP data for such images.
Is improvement in this area planned?

**Comment by clanmills** [comment]
For sure this is on the TODO list.  When will it get done?  Hard to say.  We only have 3 engineers working steadily on Exiv2 and a few friends and occasional contributors.

2 years ago, the security folks starting hitting us with fuzzed files.  These are files which violate format specifications and can cause the code to crash.  We are having a series of quarterly "dot" releases to provide a stream of security fixes while major work is done to prepare for the future.  Managing frequent releases and user correspondence consumes lots of my time.

Dan and Luis are working on v0.28 which will be released in 2020.  This is a considerable reworking of the code into C++11.

I don't believe the effort required to implement XMP > 64k is very large.  It might appear from the C++11/v0.28 project, however it has not been done as this time.

I'm delighted by the work done by @D4N and @piponazo to deal with the assault of the security people.  And, along with @kevinbackhouse, I believe we are responding effectively to security issues.  None-the-less, they have dominated the development of Exiv2 for the last couple of years and many ideas could not be persued because security has consumed our engineering resources.

I would like to retire.  I'll be 70 in January 2021, and hope to leave Exiv2 with a strong team to take the project into the next decade.  I'm writing a book about Metadata and Exiv2 Architecture.  I will run a work-shop next year in Rennes and to pass on my knowledge.  https://github.com/Exiv2/exiv2/issues/911

If you, or any of your friends, would like to get involved with Exiv2 development by undertaking XMP > 64k project, I would be happy to mentor.  And, of course, you could join us in Rennes next spring and meet other contributors and users.

**Comment by dgtlmoon** [comment]
@clanmills thanks to you (and the rest of the team) for your hardwork, I know that maintaining such opensource projects can be challenging! (and rewarding!)

**Comment by dgtlmoon** [comment]
@viskin is it worth to make a new 'task' and link it in?

**Comment by clanmills** [comment]
@viskin I am writing a book "Image Metadata and Exiv2 Architecture".  It will be finished _(and printed in colour at my expense)_ for the LGM Conference in Rennes at the end of May 2021. https://clanmills.com/exiv2/book/

The book is based around a 4000 line program tvisitor.cpp which is a _**stripped down**_ version of Exiv2.  It handles JPEG>64k (and BigTiff and ISOBMFF and lots of other stuff not in Exiv2).

The purpose of the book is allow me to retire as I will be 70 in two weeks.  I have tried to leave all possible documentation to ensure the survival and future development of Exiv2.  Or perhaps, the book will inspire somebody to write a new library.

When I say _**stripped down**_, I mean that about 50,000 lines of Exiv2 have been shortened to 4000 which I hope will be easier to understand.  Exiv2 can update and modify files, is thoroughly tested and runs on many 64 and 32 bit platforms.  The metadata parsing, I/O and memory strategy of tvisitor.cpp and Exiv2 are basically the same.

**Comment by viskin** [comment]
@clanmills Thank you for your hardwork indeed

**Comment by clanmills** [comment]
I've opened an issue for the v1.00 project to implement Adobe Exif > 64k in JPEG. #1549

I'm going to close this issue the consequential work will be in #1549.
