### ISSUE TITLE
Structure of a v0.27 tarball

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#446]
Here's the structure of the tarball for v0.26
http://www.exiv2.org/builds/exiv2-0.26-linux.tar.gz

The first version of exiv2-0.27.0-Darwin/ has the essential output of the build.  However, the v0.26 tarballs have more content:
```
569 rmills@rmillsmbp:~/Downloads/dist $ dir
-rw-r--r--@  1 rmills  staff   5.4K 17 May  2017 ReadMe.txt
drwxr-xr-x@  3 rmills  staff    96B 17 May  2017 contrib/
drwxr-xr-x@ 41 rmills  staff   1.3K 17 May  2017 samples/
drwxr-xr-x@  6 rmills  staff   192B 17 May  2017 linux/
drwxr-xr-x@  4 rmills  staff   128B 17 May  2017 logs/
570 rmills@rmillsmbp:~/Downloads/dist $ 
```
The ReadMe.txt is generated by the buildserver from contrib/buildserver/dailyReadMe.txt

contrib/ is a straight copy of the contrib/ directory in the repos
samples/ is a straight copy of the samples/directory
linux/ contains bin, include, lib, share (this is the stuff that CPack is packaging at the moment).
logs/ contains build.log and test.log

**Testing the build**
Jenkins did the build and runs the test suite.

There's another script run after the build to test the tarball.  It compiles and executes one of the samples to be certain that the build is good.

I don't think we need to test the build automatically.  Once our build process is stable, the builds will be OK and we can inspect GM builds manually before release.

**Comment by piponazo** [comment]
I see that here you are doing a comparison between what the 0.26 tarball had and what the 0.27 tarballs generated by CPack have.

I am wondering if we want to keep the same structure of the 0.26 tarballs or not. These are my opinions about each item:

1. For me, it does not make much sense to place the **contrib** & **samples** directories there since those things are already available in the source repository (and in the source tarball that CPack can also generate). 
2. The ReadMe.txt file is out of date and I do not see much value in placing a file like that in the tarball with binaries. Some of the details in that file can be found in other documents in the repository. Maybe we could have a README file just explaining the structure of the tarball. 
3. **logs**: It could be interesting to have a log detailing how the binaries for a particular release where compiled (Which options where enabled in CMake, version of the compiler, OS, etc).

**Comment by clanmills** [comment]
I think it's essential to have ReadMe.txt in the tarball.  Otherwise, the user has the following directories with no information about how to use it!  What you have in the tarball is more-or-less what I have in the dist/linux directory.
```
562 rmills@rmillsmm:~/temp/exiv2-0.27.0.0-Darwin $ dir
drwxr-xr-x+ 36 rmills staff 1.2K Sep 16 07:19 bin/
drwxr-xr-x+  3 rmills staff  102 Sep 16 07:19 include/
drwxr-xr-x+  7 rmills staff  238 Sep 16 07:19 lib/
drwxr-xr-x+  4 rmills staff  136 Sep 16 07:19 share/
563 rmills@rmillsmm:~/temp/exiv2-0.27.0.0-Darwin $ 
```

**Comment by clanmills** [comment]
Sure.  Dead, dead, dead.  Beaten to death.
