### ISSUE TITLE
Unable to set Exif resolution metadata in tiff files

### ISSUE THREAD

**Issue by henryborchers** [Exiv2/exiv2#463]
Using the API, I'm unable to set the following Exif metadata with tiff files: 

- Exif.Image.XResolution
- Exif.Image.YResolution
- Exif.Image.ResolutionUnit

I can read them but not write. Any changes I make or add are ignored and untouched for those fields. 

I've tried it with png, jpg, and jp2 files and it works there. Just with tiff files.

Tested on Windows 7. Compiled with VS14 MSVC and MSYS2 (MinGW/GCC)

**Comment by clanmills** [comment]
Henry: This is correct behaviour.  Some of the metadata cannot be changes.  For example, you can't change the number of row and columns in the image as this would require resampling the image.

There's a function isImageTag() in every image handler that determines if a metadatum can be edited.  In the case of XResolution, it doesn't see unreasonable to allow it to be edited.  Somebody did request this 2 or 3 years ago.  It's tricky because of the units and other metadata that may have to changed in sync.  For that case, I suggested that the user modify inImageTag() in their local copy of the code.

I'm going to close this issue.  I'm happy to continue to discuss this if you wish. 

Robin

**Comment by clanmills** [comment]
I've had a discussion on Messenger with Henry about this.  XResolution can be set for JPEG, JP2 and others.  It's not working for Tiff.  We have a work around:  http://dev.exiv2.org/issues/1371

I'm going to leave this issue closed.  When we release Exiv2 v0.27 GM, we'll import issues from Redmine and this issue will be addressed early in Exiv2 v0.28.

@henryborchers It would be very help for you to state which tags you wish to see "fixed".  You can document this here, or (preferably) register with our Redmine site and update: http://dev.exiv2.org/issues/1371
