### ISSUE TITLE
Exiv2 0.27 : Regex dependency : do not use PKG_CONFIG with Mingw but cmake script instead

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#466]
As the whole project is based on Cmake, no need to use PKG_Config with cmake to configure. PKG_config is and older Unix based tool, and With Mingw the introduce complexity and problem.

No need to re-invent the wheel. Cmake can find expected dependency files as well. 

The patch given in this file fix the Regex lib detection and use a Find.cmake script to do the job in place.
Now, the compilation under MinGw become more portable and generic (and work as expected...)

[regex-cmake-detect.patch.txt](https://github.com/Exiv2/exiv2/files/2460876/regex-cmake-detect.patch.txt)

Gilles Caulier

**Comment by clanmills** [comment]
I suspect you are right about this, Gilles.  I spent an evening in Scotland on vacation suffering with the Regex stuff (on MinGW, I think).  I've added @piponazo to this issue as he's our CMake guy.

I suspect pkgconfig is no longer involved in Exiv2.  There are references to it in the release notes/platform/ReadMe.txt files.  If pkgconfig is now history, I'll update the release notes appropriately.

**Comment by piponazo** [comment]
Thanks @cgilles for the contribution, the patch goods good :wink: . I will create a PR with your commit to check if it works for all the supported platforms.

**Comment by clanmills** [comment]
Fixed by #471

**Comment by clanmills** [comment]
I'm put a note into README.md to say that MinGW builds never use <regex.h>.  We did this because there seem to be several versions of <regex.h> which involve linking the appropriate library.  This is a minor feature of Exiv2 and only used by the command-line option --grep which degenerates to substring match.

We are have added support to generate the file exiv2.pc #512
