### ISSUE TITLE
Attached a wmv file for the ASFVIDEO.cpp  the while loop continues and never stops

### ISSUE THREAD

**Issue by anmolvermamm** [Exiv2/exiv2#593]
https://github.com/Exiv2/exiv2/blob/af7ca268095258abe7df20b40ec1dc4b5c3d1c46/src/asfvideo.cpp#L362
[3_1__6557887998130913604972615.wmv.zip](https://github.com/Exiv2/exiv2/files/2671313/3_1__6557887998130913604972615.wmv.zip)

**Comment by clanmills** [comment]
Thanks for letting us know about this.  We're currently in "Code Freeze" for v0.27 which is scheduled to be released on 28 December 2018.  I'm going to assign the milestone 0.28.  We plan to have regular (quarterly) "dot" releases of Exiv2 v0.27 in 2019 and 2020.  It's very likely that this will be fixed in 0.27.1  which is scheduled for 31 March 2019.

**Comment by piponazo** [comment]
Just informing here. The VIDEO support has been marked as deprecated for 0.27.1 since not much people seemed to be using it (in fact, this is the first issue I see related to that part of the code).

The code has been actually already removed in master (see #694). 

I am not sure if we will have time to work on this since that part of the code is not the core of Exiv2. Please let us how important is for you the issue.

**Comment by piponazo** [comment]
@anmolvermamm Could you tell us the exact command that you used to have such issue? I just tried to open your file on windows in release and debug mode and I could not reproduce the issue:

```
$ bin/exiv2 /f/datasets/exiv2/2018-10-17__7M34864.ARW
File name       : F:/datasets/exiv2/2018-10-17__7M34864.ARW
File size       : 24972032 Bytes
MIME type       : image/tiff
Image size      : 6048 x 4024
Camera make     : SONY
Camera model    : ILCE-7M3
Image timestamp : 2018:10:17 08:55:12
Image number    :
Exposure time   : 1/100 s
Aperture        : F8
Exposure bias   : 0 EV
Flash           : No, compulsory
Flash bias      : 0 EV
Focal length    : 85.0 mm (35 mm equivalent: 85.0 mm)
Subject distance:
ISO speed       : 100
Exposure mode   : Manual
Metering mode   : Multi-segment
Macro mode      :
Image quality   : Raw + JPEG
Exif Resolution : 6048 x 4024
White balance   : Custom
Thumbnail       : image/jpeg, 7975 Bytes
Copyright       :
Exif comment    :
```

**Comment by anmolvermamm** [comment]
We can close this as it's no longer a priority for me now. Thanks!
