### ISSUE TITLE
How does the rename (mv) work in case of name clash?

### ISSUE THREAD

**Issue by notorand-it** [Exiv2/exiv2#662]
In case I want the tool to rename all files in a directory accordingly to the timestamps (but the question would apply to all cases, IHMO), how does the tool behaves?
If I have more photos with the same EXIF timestamps, will they be all overwritten but the last one?

**Comment by clanmills** [comment]
I see nobody has attempted to answer your question.  The honest answer is "read the code" which is in src/actions.cpp The function that does the work is named `renameFile()`.

It typically generates a name such as ` 20190101_161356.jpg`,

I tried a little test and here's what happened:
```
695 rmills@rmillsmbp:~/temp/January $ exiv2 -pa --grep DateTime 9150.jpg 
Exif.Image.DateTime                          Ascii      20  2019:01:01 17:28:20
Exif.Photo.DateTimeOriginal                  Ascii      20  2019:01:01 17:17:17
Exif.Photo.DateTimeDigitized                 Ascii      20  2019:01:01 17:17:17
696 rmills@rmillsmbp:~/temp/January $ exiv2 --verbose mv *.jpg
File  1/19: 9150.jpg
Renaming file to ./20190101_171717.jpg
File  2/19: dsc_9150.jpg
exiv2: File `./20190101_171717.jpg' exists. [O]verwrite, [r]ename or [s]kip? y
File  3/19: dsc_9152.jpg
Renaming file to ./20190109_143208.jpg
File  4/19: dsc_9153.jpg
...
```
So, it seems to prompt the user by default.  If you don't want to be prompted use the --force option.  The program will keep incrementing the "seconds" until there is no name collision.

Because the name format is derived from the time stamp, collisions shouldn't be common.  However if you are taking "bracketed" photos, you have many collisions.  If that's your use case, you'll probably find this feature of exiv2 isn't for you and I can suggest two remedies:

1) Write a new

**Comment by notorand-it** [comment]
> The program will keep incrementing the "seconds" until there is no name collision.

While this can be a good workaround (as the metadata won't be affected), I think this is just a ... workaround. Not a solution.
I cannot promise I will do it, but I'd like to spend some of my spare time to see if I can code an extra option to add a "sequence number" at the end of the file name, right before the ".ext" part.

Thanks a lot for the details, though.

**Comment by clanmills** [comment]
I've been working with Exiv2 for 11 years and you're the first person who has mentioned this feature.  It probably hasn't been given any thought since Andreas wrote this in 2004!

You are welcome to work with the code and suggest changes, and to submit PRs if you wish.  I think adding a "sequence" would be quite straight forward.  I see there's a feature to enable the user to define their own format.  You should also consider how a unique sequence number could be applied to a user defined format.

The exiv2 command-line utility has a lot of features, however it's primary goal is to test exiv2 library functions.  This kind of capability doesn't get much love and attention. 

Thank for using Exiv2.  I'm going to close this issue and we can reopen it if you find time to pursue this.

**Comment by notorand-it** [comment]
> the first person who has mentioned this feature. 
I collect and store photos from a number of different devices organised by event date.
So file name clashes aren't that uncommon.

**Comment by clanmills** [comment]
I've looked at the code a little more.  There is a "sequence" number already implemented!  There are two types of `force`
1) -f brutal
2) -F benign

**Comment by notorand-it** [comment]
I can't any of them in the [manual](http://www.exiv2.org/manpage.html)!

**Comment by clanmills** [comment]
For sure, the man page hardly explains this.  I suspect this is because the man page was provided by a contributor who didn't know about all this subtle behaviour.  None-the-less, it is covered in a very terse way.  I'll reopen this issue and update the man page for Milestone Exiv2 v0.27.1 which is scheduled for 2019-03-31 (and on-track).

Here's what I believe/understand from reading the code and some experimentation.  There are three settings:
```
575 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ grep -i policy src/*.hpp
src/exiv2app.hpp:    enum FileExistsPolicy { overwritePolicy, renamePolicy, askPolicy };
```

1) The default is "ask"
2) -f overwrite
3) -F rename 

Here they are in action:

**Default** askPolicy

```
579 rmills@rmillsmbp:~/temp/January $ cp ~/Pictures/2019/January/*.jpg .
581 rmills@rmillsmbp:~/temp/January $ cp dsc_9150.jpg 9150.jpg
582 rmills@rmillsmbp:~/temp/January $ ls -l | wc
      20     173    1206  <--- 20 files.  One is a duplicate
583 rmills@rmillsmbp:~/temp/January $ exiv2 --verbose mv *.jpg
File  1/19: 9150.jpg
Renaming file to ./20190101_171717.jpg
File  2/19: dsc_9150.jpg
exiv2: File `./20190101_171717.jpg' exists. [O]verwrite, [r]ename or [s]kip? r
Renaming file to ./20190101_171717_1.jpg
File  3/19: dsc_9152.jpg
...
584 rmills@rmillsmbp:~/temp/January $ $ ls -l | wc
      20     173    1345  <--- 20 files.
585 rmills@rmillsmbp:~/temp/January $ ls -l | sort
...
-rw-r--r--  1 rmills  staff  6585366 22 Jan 15:10 20190121_160159.jpg
-rw-r--r--  1 rmills  staff  6603761 22 Jan 15:10 20190101_171717_1.jpg
-rw-r--r--  1 rmills  staff  6603761 22 Jan 15:11 20190101_171717.jpg
-rw-r--r--  1 rmills  staff  6673457 22 Jan 15:10 20190121_161133.jpg
...
```

**-f** overwritePolicy

```
586 rmills@rmillsmbp:~/temp/January $ del *.jpg
587 rmills@rmillsmbp:~/temp/January $ cp ~/Pictures/2019/January/*.jpg .
588 rmills@rmillsmbp:~/temp/January $ cp dsc_9150.jpg 9150.jpg
589 rmills@rmillsmbp:~/temp/January $ ls -l | wc
      20     173    1206  <--- 20 files.  One is a duplicate
590 rmills@rmillsmbp:~/temp/January $ exiv2 --verbose -f mv *.jpg
File  1/19: 9150.jpg
Renaming file to ./20190101_171717.jpg
File  2/19: dsc_9150.jpg
Renaming file to ./20190101_171717.jpg
591 rmills@rmillsmbp:~/temp/January $ ls -l | wc
      19     164    1273     <--- We've lost a file
592 rmills@rmillsmbp:~/temp/January $ 
```

**-F** renamePolicy

```
592 rmills@rmillsmbp:~/temp/January $ del *.jpg
593 rmills@rmillsmbp:~/temp/January $ cp ~/Pictures/2019/January/*.jpg .
594 rmills@rmillsmbp:~/temp/January $ cp dsc_9150.jpg 9150.jpg
595 rmills@rmillsmbp:~/temp/January $ ls -l | wc
      20     173    1206  <--- 20 files.  One is a duplicate
596 rmills@rmillsmbp:~/temp/January $ exiv2 --verbose -F mv *.jpg
File  1/19: 9150.jpg
Renaming file to ./20190101_171717.jpg
File  2/19: dsc_9150.jpg
Renaming file to ./20190101_171717_1.jpg
...
597 rmills@rmillsmbp:~/temp/January $ ls -l | wc
      20     173    1345  <--- 20 files.
598 rmills@rmillsmbp:~/temp/January $ ls -l | sort
...
-rw-r--r--  1 rmills  staff  6603761 22 Jan 15:18 20190101_171717.jpg
-rw-r--r--  1 rmills  staff  6603761 22 Jan 15:18 20190101_171717_1.jpg
-rw-r--r--  1 rmills  staff  6673457 22 Jan 15:18 20190121_161133.jpg
...
599 rmills@rmillsmbp:~/temp/January $ 
```

**Specifying your own format**

Man page says:
```
-r  fmt		--rename     Filename format for the 'rename' action. ...
```

And provides this example:
```
       -r fmt Filename	format for the 'rename' action. The format string fol-
	      lows strftime(3) and supports the following keywords:

	      :basename:     original filename without extension
	      :dirname:      name of the directory holding the original file
	      :parentname:   name of parent directory
	      Default filename format is %Y%m%d_%H%M%S.
```

When "renamePolicy" is used, it appends _Seq# to the generated filename.  We saw above:

```
-rw-r--r--  1 rmills  staff  6603761 22 Jan 15:18 20190101_171717.jpg
-rw-r--r--  1 rmills  staff  6603761 22 Jan 15:18 20190101_171717_1.jpg
```

Q) What happens if `20190101_171717_1.jpg` already exists?
A) I don't know.

**Comment by notorand-it** [comment]
> Q) What happens if 20190101_171717_1.jpg already exists?
G) It will be called 20190101_171717_1_1.jpg! (G stands for "guess")

In the near future I could be asked to rename a full image library (12+ years) all with different names but all with metadata.
The ability to handle name clash is crucial as the "renameat2()" system call is unforgivable without the RENAME_NOREPLACE flag!
Again, I will try to give a look to the code and see whether I can find some time for coding.

**Comment by notorand-it** [comment]
By the way...

> 598 rmills@rmillsmbp:~/temp/January $ ls -l | sort

The command "ls" normally sorts the list lexycographically, so there's no need for sort. Which would sort the whole output lines, not just the file name.
You can do "ls -lt" to sort by ascending modification time, "lr -ltr" to sort by descending modification time, "ls -ls" to sort by ascending size and "ls -lsr" to sort by descending size.

**Comment by clanmills** [comment]
Thanks for the tip about ls.  I've never understood ls's sorting and much prefer the dos dir command syntax.

As you are aware, you have to satisfy yourself about "fitness for purpose".  I didn't write the `mv` code.

I hope you feel confident that exiv2 is a good open-source product.

**Comment by clanmills** [comment]
PR Submitted.  https://github.com/Exiv2/exiv2/pull/889 

This change will be in Exiv2 v0.27.2 which is on schedule for release on 2019-06-30

The behaviour of `$ exiv2 --Force rename image` is conservative.  It should never overwrite an image.  It does this by incrementing a counter until a new filename is found.

```
$ cp ~/Stonehenge.jpg .
$ exiv2 --verbose --Force rename Stonehenge.jpg 
File 1/1: Stonehenge.jpg
Renaming file to ./20150716_153854.jpg
$ exiv2 --verbose --Force rename 20150716_153854.jpg 
File 1/1: 20150716_153854.jpg
This file already has the correct name
$ cp ~/Stonehenge.jpg .
$ exiv2 --verbose --Force rename Stonehenge.jpg 
File 1/1: Stonehenge.jpg
Renaming file to ./20150716_153854_1.jpg
$ cp ~/Stonehenge.jpg .
$ exiv2 --verbose --Force rename Stonehenge.jpg 
File 1/1: Stonehenge.jpg
Renaming file to ./20150716_153854_2.jpg
$ 
```
