### ISSUE TITLE
[proposal] Use mergify.io for backporting

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#669]
We are currently backporting a lot of stuff to the 0.27 branch, and doing that manually is tedious. I propose that we automate this process. One possible service is https://mergify.io/. 

While mergify's main selling point is to automatically merge pull requests, once they fit a certain set of rules (e.g. two approvals, CI passes, moon is in the right phase, etc.), it can also backport pull requests that get a certain label. 

See: https://doc.mergify.io/examples.html#using-labels-to-backport-pull-requests and https://doc.mergify.io/actions.html#backport

And while we are at it, we could also consider using mergify for other stuff, like automatically deleting the branch from which a pull request came.

**Comment by clanmills** [comment]
@D4N Yes.  It would be good to automate this, or push less to v0.27 branch.  In some ways, you could say that v0.27.0 GM is really RC4!  It's only 5 weeks since GM, perhaps we will soon back-port less.  Currently 33 issues for 0.27.1  https://github.com/Exiv2/exiv2/milestone/3

I intended to do the back porting from 'master/0.28' to enable you and Luis to focus on moving forward.  Luis has been as helpful as always in digging me out of git-hell.  If mergify is lots of work, perhaps @Kicer86 and I do the back-porting.

**Comment by D4N** [comment]
@piponazo The process you are describing looks a little bit like the way some projects do it, see: https://yastgithubio.readthedocs.io/en/latest/maintenance-branches/ (although they do it differently, afaik they don't cherry-pick but do forward merges instead).

I think that mergify should be able to do "forward" backports, too. In the end you just tell it which branch to merge into and what label to use. I'll take a look at that. As long as we don't allow the bot to merge anything, there's very little danger.
