### ISSUE TITLE
gettext include issue on macOS

### ISSUE THREAD

**Issue by csparker247** [Exiv2/exiv2#684]
I'm running macOS 10.14.2 (Mojave) and I have `gettext 0.19.8.1` installed via Homebrew. I can't use the `exiv2` provided by Homebrew for various reasons, so I'm trying to build `exiv2 0.27.0` with `CMake 3.12.3`. I run the following configuration command so that CMake can find `gettext`:

```Shell
cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/gettext/ ..
```
CMake configuration works fine, but when I go to build, I get the following error:

```Shell
Scanning dependencies of target exiv2lib_int
[ 12%] Building CXX object src/CMakeFiles/exiv2lib_int.dir/canonmn_int.cpp.o
In file included from /Users/seth/source/exiv2/src/canonmn_int.cpp:34:
/Users/seth/source/exiv2/src/i18n.h:33:11: fatal error: 'libintl.h' file not found
# include <libintl.h>
          ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/exiv2lib_int.dir/canonmn_int.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/exiv2lib_int.dir/all] Error 2
make: *** [all] Error 2
```

To get `exiv2lib` to build, I had to add:
```Diff
 if( EXIV2_ENABLE_NLS )
     target_link_libraries(exiv2lib PRIVATE ${Intl_LIBRARIES})
     target_include_directories(exiv2lib PRIVATE ${Intl_INCLUDE_DIRS})
+    target_include_directories(exiv2lib_int PRIVATE ${Intl_INCLUDE_DIRS})
     # Definition needed for translations
     target_compile_definitions(exiv2lib PUBLIC EXV_LOCALEDIR="/../${CMAKE_INSTALL_LOCALEDIR}")
 endif()
```
and to get the `exiv2` cli to build, I had to modify:
```Diff
     if( EXIV2_ENABLE_NLS )
         target_link_libraries(exiv2 PRIVATE ${Intl_LIBRARIES})
-        target_include_directories(exiv2lib PRIVATE ${Intl_INCLUDE_DIRS})
+        target_include_directories(exiv2 PRIVATE ${Intl_INCLUDE_DIRS})
     endif()
 
     if (USING_CONAN AND WIN32 AND EXISTS ${PROJECT_BINARY_DIR}/conanDlls)
```

[This patch to the 0.27 tag](https://github.com/Exiv2/exiv2/files/2837751/macos-missing-libintl-fix.txt) contains the two lines of code I had to change in order to get the build to work.

I'm not sure why I'm seeing this issue when others aren't. For instance, I don't see that the Homebrew formula is doing anything special to account for this. If this is actually a bug and not user error, let me know and I can open pull request off of the master branch.

**Comment by clanmills** [comment]
Thanks for reporting this and providing a patch.  I'm rather surprised by this because I develop Exiv2 on MacOS-X.  However, I seldom use home-brew.  Here's where I have libintl.h
```
1085 rmills@rmillsmbp:/usr $ find . -name libintl.h 2>/dev/null
./local/include/libintl.h
./local/Cellar/gettext/0.18.3.1/include/libintl.h
./local/Cellar/gettext/0.19.8.1/include/libintl.h
1086 rmills@rmillsmbp:/usr $ cd /opt
1087 rmills@rmillsmbp:/opt $ find . -name libintl.h 2>/dev/null
./local/include/libintl.h
1088 rmills@rmillsmbp:/opt $
```

I think your patch is correct.  The directory /usr/local/include/ is already on the header search path.  However, you'll need a "alien" path such as /usr/local/opt/gettext/include (or something like this).

I'm in Florida on vacation had having coffee in McDonalds.  I'll spend more time in the hotel this evening and give you an update.

Thanks very much for getting involved.  The only way to discover and fix strange build issues is by working together. Thanks very much.

**Comment by clanmills** [comment]
This looks good to me.  I've build on Mojave and Linux with your fix and everything seems fine.

I added a MESSAGE to confirm my diagnosis:
```
    if( EXIV2_ENABLE_NLS )
        target_link_libraries(exiv2 PRIVATE ${Intl_LIBRARIES})
        target_include_directories(exiv2 PRIVATE ${Intl_INCLUDE_DIRS})
MESSAGE("Intl_INCLUDE_DIRS = " ${Intl_INCLUDE_DIRS})
    endif()
```

and cmake reported: `Intl_INCLUDE_DIRS = /usr/local/include`

I'm assigning this to @piponazo to integrate (into both 0.27 and master) because I always make mistakes with git and PRs!

**Comment by piponazo** [comment]
Thanks @csparker247 for reporting this issue (and the patch). The changes look good to me. If you have the time to create the PR pointing to 0.27, please do it, we will incorporate the fix for the next 0.27.1. Otherwise, I could do it for you when I find some spare time.

We try to test exiv2 in many different OSs and configurations (with different CI approaches), but we keep finding issues like this one from time to time. Together, we are making the next exiv2 releases stronger 💪

**Comment by csparker247** [comment]
Sounds good. I should be able to put together a PR today.

**Comment by D4N** [comment]
This should be fixed then @csparker247, right?

**Comment by csparker247** [comment]
Yes, this is all done!
