### ISSUE TITLE
Sigma 14-24mm f/2.8 DG HSM Art Nikon

### ISSUE THREAD

**Issue by xkomczax** [Exiv2/exiv2#811]
Hi, 
Sigma 14-24mm f/2.8 DG HSM Art Nikon is not properly detected yet. Here is info about this lens:
* Sigma 14-24mm f/2.8 DG HSM Art Nikon
* exiv2 -pt DSC_2525.JPG | grep -ai lens 
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  14-24mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  193
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
* https://www.sigmaphoto.com/14-24mm-f2-8-dg-hsm-a
* 
![DSC_2525](https://user-images.githubusercontent.com/3698242/56868294-ba4a2680-69f0-11e9-8855-f9d0056702d0.JPG)

Let me know if I can help you by including more information.

**Comment by clanmills** [comment]
Good News.  You can fix this for yourself with the file ~/.exiv2.  The LensID is 193 and you can define it in the [nikon] section of ~/.exiv2.  This is described in the exiv2 man page.
```
600 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep lens/i 56868294-ba4a2680-69f0-11e9-8855-f9d0056702d0.JPG 
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  14-24mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  193
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
601 rmills@rmillsmbp:~/Downloads $ ce ~/.exiv2 
bbedit "/Users/rmills/.exiv2"

602 rmills@rmillsmbp:~/Downloads $ exiv2 -pv --grep lens/i 56868294-ba4a2680-69f0-11e9-8855-f9d0056702d0.JPG 
0x0083 Nikon3       LensType                    Byte        1  70
0x0084 Nikon3       Lens                        Rational    4  140/10 240/10 28/10 28/10
0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
0x000c NikonLd3     LensIDNumber                Byte        1  193
0x000d NikonLd3     LensFStops                  Byte        1  72
603 rmills@rmillsmbp:~/Downloads $ cat ~/.exiv2
[nikon]
193=Sigma 14-24mm f/2.8 DG HSM Art Nikon

604 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep lens/i 56868294-ba4a2680-69f0-11e9-8855-f9d0056702d0.JPG 
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  14-24mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  Sigma 14-24mm f/2.8 DG HSM Art Nikon
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
605 rmills@rmillsmbp:~/Downloads $ 
```

**Comment by xkomczax** [comment]
Thanks for your suggestion, I will do it! 
However, is the lens going to make it to the master release one day? I cannot see the lens in any branch in this repo.

**Comment by clanmills** [comment]
It's unlikely that we'll add this lens to the "built in" lens table, although you are welcome to prepare a PR if you wish.  Here's a recent investigation into another Nikon lens #743

Lens recognition is a troubling matter.  The Lens is not explicitly/uniquely identified in the metadata.  Different manufacturers do this in different ways.  In the case of your Nikon lens, there is a LensID (an integer).  Sometimes as many as 20 different lens use the same LensID and we have to look at other data such min/max focal length to "guess" the lens.

You can understand that we get many requests to add new lenses and a couple of years ago, I added the ~/.exiv2 mechanism to enable users to fix this at home.  If I add a lens to the code today, it could be 3 or 4 years depending on various release cycles.  Putting your lens in ~/.exiv2 is instant and works with every version of Exiv2 since v0.26!
