### ISSUE TITLE
Denial of service in XMPUtils AdjustTimeOverflow()

### ISSUE THREAD

**Issue by kevinbackhouse** [Exiv2/exiv2#851]
There is a denial of service bug in the loop at [XMPUtils.cpp:245](https://github.com/Exiv2/exiv2/blob/c0ecc2ae36f34462be98623deb85ba1747ae2175/xmpsdk/src/XMPUtils.cpp#L245) because `time->day` can be very large. This loop adjusts out-of-bounds days by subtracting one month at a time. Since the type of `time->day` is `long`, this can take a very long time.

![issue_851_poc](https://user-images.githubusercontent.com/4358136/57687373-41bfa880-7633-11e9-9e47-167ef28bd19c.jpg)

Reproducible on the 0.27-maintenance branch ([c0ecc2a](https://github.com/Exiv2/exiv2/commit/c0ecc2ae36f34462be98623deb85ba1747ae2175)):

```
exiv2 issue_851_poc.jpg
```

**Comment by D4N** [comment]
As I said in #852: this is a bug in xmpsdk and while we can certainly patch this bug, this really should be fixed upstream.

**Comment by piponazo** [comment]
Kevin mentioned that we would also report the issue to Adobe. Thanks again for your amazing contributions! :heart:

**Comment by kevinbackhouse** [comment]
I sent an email to PSIRT@adobe.com yesterday and I already got an acknowledgement email back from them. So hopefully there will be a new XMP toolkit available in time for v0.28. In the meantime though, I think we should probably include this fix in v0.27.

**Comment by D4N** [comment]
Awesome job @kevinbackhouse!

**Comment by clanmills** [comment]
Great Work, @kevinbackhouse

For v0.27, @piponazo added an option to the build using an "external" XMPsdk.  This is documented in README-CONAN.md  So, it is possible to build Exiv2 with Adobe's XMPsdk 2016 Edition.  For v0.27 we continued to support the existing xmpsdk/ code because it has given solid service for at least 10 years most users will build exiv2 without even know it's there!

We haven't discussed how XMPsdk code will be supported for v0.28.  As v0.28 is "moderisation", I think we should remove the xmpsdk/ directory and download/build Adobe's latest and greatest XMPsdk.  

I can't explain how or why the xmpsdk/ directory was added to Exiv2 in the first place.  I suspect it was to avoid using Adobe's bash build scripts which required CMake.  I think @cgilles added the initial Exiv2/ CMake code sometime after xmpsdk/ was added.

A major change in v0.27 was to adopt CMake as the only build environment for Exiv2 and we removed both autotools on Linix/Cygwin/MinGW and the msvc/ project+solution files used to build with Visual Studio.

So applying a security fix to xmpsdk/ code has great value.  Thank You for undertaking this work.
