### ISSUE TITLE
Announcement platform for API changes

### ISSUE THREAD

**Issue by phako** [Exiv2/exiv2#883]
Sorry to do this via an issue...

I just noticed by my CI failing that master introduced an API change (long -> size_t). Do you provide a way to get notified about this by some kind of mailinglist etc? If not, consider this a feature request for providing this or something similar

**Comment by clanmills** [comment]
@phako Does this reference 'master' or the `0.27-maintenance` branch (or both)?

@D4N talked about having a mail server and I think @nehaljwani offered to get it set up.

Perhaps you can offer suggestions about our work-flow.  We're making regular "dot" releases on the 0.27-maintenance branch and hope to avoid API changes.  We provide RCs of the "dot" releases and I was hoping to get feedback if we disturb anybody's builds against the RCs.

0.28 ('master') is a development branch and the API will change during development.

Are you asking us to notify you about API changes with on 'master' or '0.27-maintenance' or both.  How do other projects deal with this.  Do you know of a script generate this report possibly using something such as `$ nm --demangle -voodoo-options libexiv2.so` and we could include it in our test suite to alert us to changes in the API (and possibly ABI)?

**Comment by phako** [comment]
This is really about master and I'm well aware that it might change, I just would like to find out about it before my CI breaks (but then again that's why I set up the CI in the first place). Maybe I can also simply subscribe to some kind of commit digest from github, I need to figure that out

If it is any help to you, I do have a weekly pipeline running against 0.26, 0.27 and master branches here: https://gitlab.gnome.org/GNOME/gexiv2/pipeline_schedules

**Comment by clanmills** [comment]
Thank You, Jens.  I'll look at your pipelines this evening.  I'll try to motivate @nehaljwani to undertake the challenge of both the mailing list, and adding something to the test suite to look for changes in the ABI (and possibly API).

As you've said, one of the purposes of CI is to know if a change has broken your build.  However it would be good for us to be "pro-active" in monitoring and notifying changes in the API.

@nehaljwani would you like to undertake this challenge?

**Comment by clanmills** [comment]
@phako Team Exiv2 have a Slack channel on which we chat "off-line".  Mostly it's about vacations and stuff like that as the "formal" discussions take place in GitHub issues.  If you'd like to join our channel (we have several other "friends" as well as Team Members), please email me: robin@clanmills.com and I will send you an invitation.

**Comment by clanmills** [comment]
I'm getting a '404' from the pipeline_schedules.  I can see:  https://gitlab.gnome.org/GNOME/gexiv2/, however I'm not familiar with GitLab, so I'm not sure what I am looking at!

Incidentally, Exiv2 also uses GitLab to build many different distributions.  @D4N and @piponazo are the experts.  I have a Jenkins server running on my MacMini and use that to build the supported platforms (Visual Studio 2008+, MacOS-X, Ubuntu, Cygwin, MinGW).  For v0.27.2 I have added FreeBSD and NetBSD.

I'm going to close this issue as it's a discussion/request for a new service from Team Exiv2.  I hope we will find the time and resources to achieve this.  We (like you) are all volunteers and there are more demands on the project than resources to service every request.  For sure, since the arrival of Dan and Luis in the team in 2017, we've been able to do much more than I could on my own.  We also have another 4 regular contributors.  So life is good and getting better.  We might be able to do this for you.

For your information, we're in good shape for v0.27.2.  Alison and I are going to Scotland on family business for 10 days.  We return early June and I hope to release v0.27.2-RC1 by mid-June and v0.27.2 on schedule on 2019-06-30.

**Comment by D4N** [comment]
I plan to setup a list on sourcehut (https://lists.sr.ht/~d4n/), but haven't created and announced it yet. 

Also, I'm not sure if we'll announce every API change for master there, as we are currently experimenting on master and things haven't settled down yet. The size_t change is bound to stay though.

**Comment by phako** [comment]
> I'm getting a '404' from the pipeline_schedules. I can see: https://gitlab.gnome.org/GNOME/gexiv2/, however I'm not familiar with GitLab, so I'm not sure what I am looking at!

Oh right, sorry, that seems for project owners only.

No worries. It was a merely a suggestion and as you said, there's only so much time. And I have the CI to catch issues as a fall-back

**Comment by clanmills** [comment]
Thanks, Dan.  I'm hoping to persuade @nehaljwani to take on this challenge.  There are two different matters:

1) The mailing list/server/users and spam monitor
2) What are we going to announce on the mailing list?
@phako is asking for API changes and I'd like Nehal to add something to the test suite to monitor the API.

**Comment by clanmills** [comment]
@phako Thanks for pointing me to the flatpak code.  I've no idea what that does, however it looks and smells beautiful!
![DSC_9217](https://user-images.githubusercontent.com/529982/58018619-34a32d80-7afb-11e9-849a-fdf904bec254.jpg)
