### ISSUE TITLE
'exiv2 mv -r' not accepting format

### ISSUE THREAD

**Issue by rokezu** [Exiv2/exiv2#895]
**Describe the bug**
When using exiv2 0.27.1, and renaming a file, the format string is now treated as a filename and ignored, also a temporal file remains in the directory, and new ICC Profile error messages appear.  

**To Reproduce**
```
exiv2 mv -F -t -r '%Y%m%d' PHOTO.JPG
Exiv2 exception in rename action for file -F:
Not a valid ICC Profile
Exiv2 exception in rename action for file -t:
Not a valid ICC Profile
Exiv2 exception in rename action for file -r:
Not a valid ICC Profile
%Y%m%d: Failed to open the file
exiv2: File `./20190529_171831.JPG' exists. [O]verwrite, [r]ename or [s]kip? O
```
(In this example, the file was previously renamed to the default format string, even when a new string is used, as in the example)

Also, files with names like `1559227727.exiv2_temp` are kept in the directory after finishing. Didn't happened before. 

**Expected behavior**
The format string should be accepted and in the example, renamed to `20190529.JPG`

**Desktop (please complete the following information):**
 - OS: Arch Linux
Using prepackaged file from https://www.archlinux.org/packages/extra/x86_64/exiv2/ 

**Additional context**
Noticed after a script I use when connecting the camera failed to produce the expected results. The script used the parameters as above.

**Comment by clanmills** [comment]
Thanks for reporting this.  I'm on vacation at the moment and will investigate next week.  The schedule for Exiv2 v0.27.2 is 2019-06-30 and I hope to include a fix for this into that release.

**Comment by clanmills** [comment]
This isn't a bug.  The action **`'mv'`** should follow the options:

The syntax of the exiv2 command is:
```
exiv2 [options] [action] file ...
where:
action := 
       pr | print
       ex | extract
       in | insert
       rm | delete
       ad | adjust
       mo | modify
       mv | rename
       fi | fixiso
       fc | fixcom
```
All the 'options' you have used following **`'mv'`** have been treated as files,  so:
```
%Y%m%d: Failed to open the file
```
has been correctly diagnosed: "Failed to open the file"

Warnings such as:
```
Exiv2 exception in rename action for file -F:
Not a valid ICC Profile
```
Are emitting the wrong message and I will investigate and fix that.

The command-line syntax could be modified to allow options before and after the **`'action'`**, however this syntax was established before I joined the project in 2007 and changing it may have unexpected consequences.

**Comment by rokezu** [comment]
Oh, thanks for pointing that out, perhaps the command line format got more strict recently? I will update my scripts, they were working with `exiv2 mv -F -t -r '<format>'` for years maybe, I have changed them to `exiv2 -F -t -r '<format>' mv`.  and work fine now. 

After using the correct arguments, neither the ICC Profile errors continue nor the temporary file remains. 

My bad, seemed to a bug to me because the behaviour changed suddenly with the new version.

**Comment by clanmills** [comment]
There was a substantial change to the command-line parser for v0.27.  We used to use the system's `::getopt()` on most platforms and had some code (of unknown origin) to implement `::getopt()` on Windows.  We adopted the `getopt()` code for every platform to guarantee consistent parsing on all platforms.  Although we didn't intend side effects, it is possible that the pre-0.27 parsing was more forgiving.

Fixing the *`ICC Profile`* message is straightforward and I will submit the PR early next week.

I'll ensure that temporary files are never left in the file system when the action 'mv' is in the incorrect location in the command-line. 

Thank you for closing the issue.  I'll reopen it until I submit the PR concerning the *`ICC Profile`* message.

**Comment by clanmills** [comment]
There is a bug in the handling of a file which begin with **`-`** such as **`-F`**.  These are being incorrectly interpreted as stdin.  The fix for this is in `src/futils.cpp` in function `Protocol fileProtocol(const std::string& path)` and `Protocol fileProtocol(const std::wstring& wpath)`.

I've made some additional changes to `src/basicio.cpp`.  These changes aren't essential, however I believe they have merit and I have included them in the PR.

I've discovered a False "ICCProfile" warning with the command:
```$ exiv2 -pr -```

Fixed in`XPathIo::ReadStdin()` and `XPathIo::writeDataToFile()` by throwing `kerInputDataReadFailed`

The bug report discusses temporary files being left in the filesystem.  The fix in `fileProtocol()` is sufficient to prevent this.  However the function `XPathIo::writeDataToFile()` should be less enthusiastic to use `std::ofstream fs` as this creates a temporary file.  I believe XPathIo class has something to do with Extended file-system attributes which are supported on MacOS-X (and possibly some Linux 'advanced' file systems).  

I'm going to close this issue.  I'm sure there will be polish/changes to the PR and these will be discussed in #899.
