### ISSUE TITLE
Why is Exif.Sony2Fp not just called Sony2?

### ISSUE THREAD

**Issue by cryptomilk** [Exiv2/exiv2#942]
**Describe the bug**

Looks like the whole space is called Sony2Fp which seems to stand for FocusPosistion.

Exif.Sony2Fp.AmbientTemperature              SByte       1  18
Exif.Sony2Fp.FocusMode                       Byte        1  0
Exif.Sony2Fp.AFAreaMode                      Byte        1  255
Exif.Sony2Fp.FocusPosition2                  Byte        1  235

Shouldn't this be just Exif.Sony2.*?

**Comment by cryptomilk** [comment]
Just asking ...

**Comment by clanmills** [comment]
There's an an answer in the architecture of Exiv2.  I'm on a boat in the Baltic and I'll reply properly next week.Robinhttps://clanmills.comOn 1 Jul 2019 15:33, Andreas Schneider <notifications@github.com> wrote:Just asking ...

**Comment by clanmills** [comment]
@cryptomilk Exiv2 uses the scheme:  Family.Group.Tag to identify metadata.

Family: { Exif | Iptc | Xmp }
Group:  hundreds of groups to subdivide a family
Tag: some tags within a group

Example, the GPSInfo group:
```
715 rmills@rmillsmbp:~/clanmills $ exiv2 -pa --grep GPSInfo http://clanmills.com/Stonehenge.jpg 
Exif.GPSInfo.GPSVersionID                    Byte        4  2.3.0.0
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  51deg 10.69690' 
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  West
Exif.GPSInfo.GPSLongitude                    Rational    3  1deg 49.59840' 
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSAltitude                     Rational    1  97 m
Exif.GPSInfo.GPSTimeStamp                    Rational    3  14:38:55.9
Exif.GPSInfo.GPSSatellites                   Ascii       3  09
Exif.GPSInfo.GPSMapDatum                     Ascii      17  WGS-84          
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2015:07:16
716 rmills@rmillsmbp:~/clanmills $ 
```

That data is normally stored in binary in Exif.Photo.MakerNote tag:
```
717 rmills@rmillsmbp:~/clanmills $ exiv2 -pa --grep maker/i  http://clanmills.com/Stonehenge.jpg 
Exif.Photo.MakerNote                         Undefined 3152  (Binary value suppressed)
Exif.MakerNote.Offset                        Long        1  820
Exif.MakerNote.ByteOrder                     Ascii       3  II
718 rmills@rmillsmbp:~/clanmills $ 
```

When we decode the MakerNote in your file, we use Exif.Sony2 to decode the tags.  Your data is encoded in binary and known to exiv2 as Sony2Fp.
```
TagInfo(  0x2d, "FocusPosition2"    , N_("Focus Position 2")   , N_("Focus Position 2")   , sony2FpId, makerTags, unsignedByte, 1, printValue),
```

It's very common for tags to be known to several groups:
```
src/nikonmn_int.cpp:        TagInfo( 8, "FocusPosition", N_("Focus Position"), N_("Focus position"), nikonLd2Id, makerTags, unsignedByte, 1, printValue),
src/nikonmn_int.cpp:        TagInfo( 8, "FocusPosition", N_("Focus Position"), N_("Focus position"), nikonLd3Id, makerTags, unsignedByte, 1, printValue),
```

So, depending on the camera model, the FocusPosition for a Nikon Camera could be reported in group NikonLd3 or NikonLd2.  For my D530, it's:
```
724 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -pa --grep FocusPosition  http://clanmills.com/Stonehenge.jpg | grep -i Foc
Exif.NikonLd3.FocusPosition                  Byte        1  148
725 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```

In your case, FocusPosition is only known in group sony2Fp, and we could hide that group from the user and report it as Exif.Sony2.FocusPosition.  However the code for such "slight of hand" isn't in Exiv2.

The design Family.Group.Tag has been in Exiv2 since before I arrived in 2008.  It's rather inflexible.  We've been asked to support multiple page format (such as tiff and pdf) and there's no obvious way to extend this scheme to cover multiple pages.

I've made up my mind to write a book about Exiv2 and document how everything works.  One day Exiv2 1.0 will appear with a smaller/fixed API, extensible tag scheme, multiple pages, better lens recognition, bigtiff support and new video code.  My contribution is to document what already exists and hope to  motivate/inspire others to undertake the challenge.  I'm thinking about running a workshop at LGM in 2020 in Rennes to address this subject.

I'm going to close this issue, as I've given you a response.  I am happy to discuss this further if you wish.

**Comment by cryptomilk** [comment]
Thanks for the explanation!
