### ISSUE TITLE
Consider moving lens db to a separate module, for easier updating

### ISSUE THREAD

**Issue by milasudril** [Exiv2/exiv2#970]
**Describe the bug**
It appears that libexiv in popular distros get outdated too fast. My lens is in version 0.27, but not in 0.25, which is provided by Ubuntu. I tried to build the latest version and use it with the installed version of darktable but failed. It would be good to move such things out so it would be trivial to update the database.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install for example 19.04, and you will still get an out-of-date lens db

**Expected behavior**
A simple file that can be stored in /usr/local/shared, that contains all required information for lens correction.

**Desktop (please complete the following information):**
 - OS: Debian, Mint, RedHat, Ubuntu (ie distros with slow upgrades, probably not Arch, and Gentoo)
 - Compiler & Version: NA
 - Compilation mode and/or compiler flags: NA

**Comment by clanmills** [comment]
Thank you for reporting this issue and thank you for using Exiv2.

I am very aware of this issue.  About 50% of issues in Exiv2 concern lens recognition.  In v0.26, we added a feature for you to declare you own lens in the file ~/.exiv2

https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/

**Comment by milasudril** [comment]
Good work. Now just waiting for Ubuntu to upgrade to latest version so this changes is distributed.

**Comment by D4N** [comment]
Moving the lens database into a separate file/package is actually not going to solve a lot, as (unless we invest a lot more energy in keeping the lens db compatible across versions) it will be impossible to use 0.27's lens db in 0.25 (that would furthermore require a backport of that feature).

Please also note that many of the new lenses actually require additional code, which would make distribution via a lens database package problematic.

And at last: the actual issue here is that Ubuntu is **exceptionally** slow at upgrading core libraries. RHEL/CentOS 7 is actually running the latest exiv2 release, because their maintainers keep it up to date although they have a much longer release cycle.
