### ISSUE TITLE
Pentax lens samples

### ISSUE THREAD

**Issue by mikelygee** [Exiv2/exiv2#995]
Here are three sample files from a Pentax K-500:

IMGP9815.JPG: Sigma Zoom 28-88mm MACRO 1:3.5-5.6; exiv2 identifies it as "Tamron 35-90mm F4 AF"

IMGP9816.JPG: Tokina AF 100-300mm 1:5.6-6.7; exiv2 identifies it as "Cosina AF 100-300mm F5.6-6.7". This may be correct; the Tokina may be a re-branded Cosina, but I don't know how to check.

IMGP9816.JPG: smc Pentax-DA 50mm f1.8; exiv2 correctly identifies it

![IMGP9815](https://user-images.githubusercontent.com/5974219/64213408-ff331c00-cf00-11e9-85dc-7555a7720dc8.JPG)
![IMGP9816](https://user-images.githubusercontent.com/5974219/64213409-ffcbb280-cf00-11e9-816c-daf2ebe95323.JPG)
![IMGP9817](https://user-images.githubusercontent.com/5974219/64213410-ffcbb280-cf00-11e9-973d-4cbdc545b9a4.JPG)

**Comment by clanmills** [comment]
Thanks for reporting this and providing the test files.  Here's what I see:
```
$ ls -l *.JPG
-rw-r--r--@ 1 rmills  staff  207185  4 Sep 07:23 IMG_9815.JPG
-rw-r--r--@ 1 rmills  staff  207177  4 Sep 07:23 IMG_9816.JPG
-rw-r--r--@ 1 rmills  staff  207146  4 Sep 07:23 IMG_9817.JPG
$ exiv2 -pa --grep lens/i IMG_98*.JPG
IMG_9815.JPG          Exif.Pentax.LensType                         Byte        4  Tamron 35-90mm F4 AF
IMG_9815.JPG          Exif.Pentax.LensInfo                         Undefined  80  0 131 128 0 0 44 1 39 0 0 0 0 0 0 0 0 40 148 55 149 145 70 247 65 236 137 122 82 1 65 108 251 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
IMG_9816.JPG          Exif.Pentax.LensType                         Byte        4  Cosina AF 100-300mm F5.6-6.7
IMG_9816.JPG          Exif.Pentax.LensInfo                         Undefined  80  0 132 128 114 0 21 3 32 0 0 0 0 0 0 0 0 40 212 99 253 100 39 17 97 161 170 160 40 1 80 124 251 255 255 255 21 1 131 40 19 0 172 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
IMG_9817.JPG          Exif.Pentax.LensType                         Byte        4  smc PENTAX-DA 50mm F1.8
IMG_9817.JPG          Exif.Pentax.LensInfo                         Undefined  80  0 135 176 2 0 212 1 144 0 0 0 0 0 0 0 0 24 214 47 201 117 4 20 33 81 56 104 69 17 28 140 251 255 255 255 212 33 115 5 112 32 132 68 0 0 0 32 0 255 255 212 152 0 24 12 48 7 0 0 202 0 0 0 0 4 127 109 254 111 232 4 2 8 254 128 128 0 0 0 3
$ 
```
You can fix this for yourself using the file ~/.exiv2 with the following information (note the option **-pv** which I will discuss in a moment.
```
551 rmills@rmillsmbp:~/Downloads $ exiv2 -pv --grep lenstype/i IMG_98*.JPG
IMG_9815.JPG          0x003f Pentax       LensType                    Byte        4  3 44 0 0
IMG_9816.JPG          0x003f Pentax       LensType                    Byte        4  4 21 0 0
IMG_9817.JPG          0x003f Pentax       LensType                    Byte        4  7 212 0 0
552 rmills@rmillsmbp:~/Downloads $ 
```
```
554 rmills@rmillsmbp:~/Downloads $ cat ~/.exiv2
[pentax]
3 44 0 0=Sigma Zoom 28-88mm MACRO 1:3.5-5.6
4 21 0 0=Tokina AF 100-300mm 1:5.6-6.7
7 212 0 0=IMGP9816.JPG: smc Pentax-DA 50mm f1.8


555 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep lenstype/i IMG_98*.JPG
IMG_9815.JPG          Exif.Pentax.LensType                         Byte        4  Sigma Zoom 28-88mm MACRO 1:3.5-5.6
IMG_9816.JPG          Exif.Pentax.LensType                         Byte        4  Tokina AF 100-300mm 1:5.6-6.7
IMG_9817.JPG          Exif.Pentax.LensType                         Byte        4  IMGP9816.JPG: smc Pentax-DA 50mm f1.8
556 rmills@rmillsmbp:~/Downloads $ 
```
Lens recognition is troublesome because it is not actually part of the metadata.  We have to deduce the lens by inspecting other metadata.  In your case with a Pentax, the manufacturer has stored a 4 byte LensType in the MakerNote.  It's very likely that Pentax use the same LensType for more that one lens.  So, if I change the code in src/pentax_int.cpp, I will break the lens recognition for another user.

The print flag **-Pv** reveals the value of tags (as stored). The print flag **-Pt** reveals the "interpreted" value, which prints the strings from the code.  When you declare a lens in ~/.exiv2, we skip the built-in recognition and use your declaration.

The use of the file ~/.exiv2 was added to Exiv2 v0.26 (April 2017) and is documented here:  https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/

**Comment by clanmills** [comment]
As there is no user feedback, I'm going to close this issue.  @mikelygee If you wish to discuss this further, I will reopen this issue.
